project:
  type: website
  output-dir: _site

website:
  title: "ISSS626-GAA"
  navbar:
    background: "#dce7f3"
    foreground: "#4c5e7e"
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 1A"
            href: hands-on-exercise-1a.qmd
          - text: "Hands-on Exercise 1B"
            href: hands-on-exercise-1b.qmd
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
  search:
    location: navbar
    type: overlay

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    smooth-scroll: true

execute:
  freeze: auto
  warning: false
  message: false

