[build]
  publish = "_site"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/404.html"
  to = "/404.html"
  status = 404

