{
  "hash": "6a07886bea9b91c00ec59c2def2ab51e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Hands-on Exercise 2A\"\nsubtitle: \"First-order spatial point patterns and childcare intensity\"\nauthor: \"Zhenhua Liu\"\ndate: \"2026-09-19\"\nbody-classes: exercise-page\ntoc: true\ntoc-location: right\ncode-fold: false\ncode-tools: true\nexecute:\n  echo: true\n  warning: true\n  message: false\n  error: false\n---\n\n\n\n## Overview\n\nWhere are childcare services concentrated, and how much does the answer depend\non the observation window and smoothing method? I use Singapore's childcare\nlocations to examine intensity at national and planning-area scales. A nearest-neighbour\ntest provides a benchmark against spatial randomness; kernel density estimation\n(KDE) then shows where concentrations occur. These are complementary summaries,\nnot a measure of whether local demand is adequately served.\n\nThis exercise follows the workflow in [course Chapter 4](https://r4gdsa.netlify.app/chap04.html).\nThe next page, [Hands-on Exercise 2B](../handson2B/index.qmd), examines spatial\nrelationships over a range of distances.\n\n## 1. Setup and source data\n\n`sf` handles vector geometry, the `spatstat` component packages provide planar\npoint-pattern analysis, and `terra` carries the density raster into `tmap`.\n`dplyr` supplies the attribute filtering used to define the study region.\nPackages are installed before rendering, so the page never changes its environment\nhalfway through an analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(sf)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLinking to GEOS 3.14.1, GDAL 3.12.1, PROJ 9.7.1; sf_use_s2() is TRUE\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'dplyr'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(spatstat.geom)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: spatstat.data\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: spatstat.univar\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nspatstat.univar 3.2-0\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nspatstat.geom 3.8-3\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(spatstat.explore)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: spatstat.random\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nspatstat.random 3.5-1\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: nlme\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'nlme'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:dplyr':\n\n    collapse\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nspatstat.explore 3.8-2\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(spatstat.random)\nlibrary(terra)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nterra 1.9.50\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'terra'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:spatstat.geom':\n\n    area, delaunay, is.empty, rescale, rotate, shift, where.max,\n    where.min\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(tmap)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRegistered S3 method overwritten by 'stars':\n  method                  from\n  st_interpolate_aw.stars sf  \n```\n\n\n:::\n:::\n\n\nI use the official [ECDA Child Care Services GeoJSON](https://data.gov.sg/datasets/d_5d668e3f544335f8028f546827b773b4/view)\nand [URA Master Plan 2019 Subzone Boundary (No Sea)](https://data.gov.sg/datasets/d_8594ae9ff96d0c708bc2af633048edfb/view).\nThe download routine is provided in [`R/download-data.R`](R/download-data.R).\n`NAME` and `ADDRESSSTREETNAME` describe each service; `PLN_AREA_N` and `SUBZONE_N`\nidentify the administrative units.\n\n::: {.callout-note title=\"The data date is not the download date\"}\nThe ECDA portal describes this layer as **December 2021 data**, despite its\n2026 portal update. These maps describe that historical service snapshot,\ndownloaded in September 2026. They should not be presented as a current inventory.\nBoth GeoJSON files already contain separate attributes, so no HTML-description\nparsing is needed.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraw_dir <- \"handson2A/data/raw\"\nrequired <- file.path(raw_dir, c(\"childcare.geojson\", \"mp19-subzone.geojson\"))\nif (!all(file.exists(required))) stop(\"Run source('handson2A/R/download-data.R') first.\")\nchildcare_raw <- st_read(required[1], quiet = TRUE)\nsubzones_raw <- st_read(required[2], quiet = TRUE)\ninput_audit <- data.frame(\n  dataset = c(\"Child Care Services\", \"MP2019 subzones\"),\n  records = c(nrow(childcare_raw), nrow(subzones_raw)),\n  geometry = c(as.character(unique(st_geometry_type(childcare_raw))),\n               as.character(unique(st_geometry_type(subzones_raw)))),\n  epsg = c(st_crs(childcare_raw)$epsg, st_crs(subzones_raw)$epsg),\n  empty = c(sum(st_is_empty(childcare_raw)), sum(st_is_empty(subzones_raw))),\n  invalid = c(sum(!st_is_valid(childcare_raw)), sum(!st_is_valid(subzones_raw)))\n)\ninput_audit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              dataset records     geometry epsg empty invalid\n1 Child Care Services    1925        POINT 4326     0       0\n2     MP2019 subzones     332 MULTIPOLYGON 4326     0       6\n```\n\n\n:::\n:::\n\n\n## 2. Geometry, CRS and the observation window\n\nI transform both layers to **SVY21 / Singapore TM (EPSG:3414)** so coordinates\nand distances are in metres. `st_transform()` changes coordinate values;\nassigning a CRS label alone would not perform that conversion. I validate the\npolygons and use the course's exclusions for the Southern Group, Western Islands\nand North-Eastern Islands. This is a specified administrative study window,\nnot a claim that every remaining square metre is habitable land.\n\nDissolving subzone boundaries with `st_union()` produces one region for\n`as.owin()`. An `owin` stores the observation boundary; a `ppp` stores events\ninside that boundary. Using the points' bounding rectangle instead would include\nunobserved sea and change both expected density and simulated patterns.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstopifnot(!any(st_is_empty(childcare_raw)), !any(st_is_empty(subzones_raw)),\n          all(st_geometry_type(childcare_raw) == \"POINT\"))\nchildcare <- st_transform(childcare_raw, 3414)\nsubzones <- st_transform(st_make_valid(subzones_raw), 3414)\nsubzones <- filter(subzones, SUBZONE_N != \"SOUTHERN GROUP\",\n                   !PLN_AREA_N %in% c(\"WESTERN ISLANDS\", \"NORTH-EASTERN ISLANDS\"))\nstopifnot(st_crs(childcare) == st_crs(subzones), !st_is_longlat(childcare))\nsingapore <- st_union(subzones)\nsg_window <- as.owin(singapore)\nxy <- st_coordinates(childcare)\ninside <- inside.owin(xy[, 1], xy[, 2], sg_window)\nduplicate_location <- duplicated(as.data.frame(xy))\n# Co-located records may be different operators. Keep them for service intensity.\nchildcare_ppp <- ppp(xy[inside, 1], xy[inside, 2], window = sg_window,\n                     checkdup = FALSE)\nunitname(childcare_ppp) <- c(\"metre\", \"metres\")\nchildcare_unique <- unique(childcare_ppp)\nquality_audit <- data.frame(\n  measure = c(\"Imported records\", \"Retained subzones\", \"Outside study window\",\n              \"Records at repeated coordinates (beyond first)\", \"Records in window\",\n              \"Distinct locations in window\", \"Study area (km2)\"),\n  value = c(nrow(childcare), nrow(subzones), sum(!inside), sum(duplicate_location),\n            npoints(childcare_ppp), npoints(childcare_unique), area.owin(sg_window) / 1e6)\n)\nquality_audit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                         measure     value\n1                               Imported records 1925.0000\n2                              Retained subzones  327.0000\n3                           Outside study window    0.0000\n4 Records at repeated coordinates (beyond first)  187.0000\n5                              Records in window 1925.0000\n6                   Distinct locations in window 1738.0000\n7                               Study area (km2)  669.5167\n```\n\n\n:::\n\n```{.r .cell-code}\ndir.create(\"handson2A/data/derived\", recursive = TRUE, showWarnings = FALSE)\nsaveRDS(subzones, \"handson2A/data/derived/subzones-clean.rds\")\n```\n:::\n\n\nThe audit retains **1925 service records** at\n**1738 distinct coordinates**. There are\n187 records beyond the first at repeated coordinates and\n0 points outside the window. Repeated coordinates are not enough\nevidence to delete a service: several operators or records can share a building.\nI retain records for provision intensity and also test distinct locations as a\nsensitivity check. No random jitter is added to manufacture separation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nℹ tmap modes \"plot\" - \"view\"\nℹ toggle with `tmap::ttm()`\n```\n\n\n:::\n\n```{.r .cell-code}\ntm_shape(subzones) + tm_polygons(fill = \"#eef3f8\", col = \"white\", lwd = 0.2) +\n  tm_shape(childcare[inside, ]) + tm_dots(col = \"#465d91\", size = 0.025) +\n  tm_title(\"Childcare service records in Singapore\") +\n  tm_scalebar(position = tm_pos_in(\"left\", \"bottom\")) +\n  tm_compass(position = tm_pos_in(\"right\", \"top\"))\n```\n\n::: {.cell-output-display}\n![Historical childcare service records within the selected MP2019 study window.](index_files/figure-html/national-map-1.png){fig-alt='Map of Singapore subzones overlaid with childcare service points.' width=1350}\n:::\n:::\n\n\nThe overlay checks spatial alignment and reveals uneven concentrations. Large\nlow-density areas include land that is not primarily residential, so national\nhomogeneous randomness is a deliberately simple reference model.\n\n## 3. Nearest-neighbour analysis\n\nThe Clark–Evans ratio compares observed mean nearest-neighbour distance with\nthe homogeneous Poisson expectation. Values below one indicate shorter\nseparations. I specify a one-sided clustering alternative for this national\nquestion, with a 5% significance threshold.\n\nI show both the asymptotic approximation and 999 Monte Carlo simulations.\nThe latter places the same number of points uniformly inside the actual\nwindow and applies the same uncorrected statistic to observed and simulated\npatterns. This accounts for window shape in the reference distribution, although\nthe uncorrected ratio itself still has edge bias. Nearest-neighbour statistics\ninvolve interpoint distances; their inclusion here follows the course's sequence,\nwhile KDE is the main first-order intensity method.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(20260919)\nce_z <- clarkevans.test(childcare_ppp, correction = \"none\",\n                       alternative = \"clustered\", method = \"asymptotic\")\nce_mc <- clarkevans.test(childcare_ppp, correction = \"none\",\n                        alternative = \"clustered\", method = \"MonteCarlo\", nsim = 999)\nce_unique <- clarkevans.test(childcare_unique, correction = \"none\",\n                            alternative = \"clustered\", method = \"MonteCarlo\", nsim = 999)\nce_table <- data.frame(\n  analysis = c(\"Service records: normal approximation\", \"Service records: Monte Carlo\",\n               \"Distinct locations: Monte Carlo\"),\n  R = c(unname(ce_z$statistic), unname(ce_mc$statistic), unname(ce_unique$statistic)),\n  p = c(ce_z$p.value, ce_mc$p.value, ce_unique$p.value)\n)\nce_table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                               analysis         R     p\n1 Service records: normal approximation 0.5353162 0.000\n2          Service records: Monte Carlo 0.5353162 0.001\n3       Distinct locations: Monte Carlo 0.6104213 0.001\n```\n\n\n:::\n:::\n\n\nThe record-level ratio is **0.535**, with simulated\np = **0.001**. After collapsing co-located\nrecords, R becomes **0.61** and p becomes\n**0.001**. The comparison separates\nthe contribution of shared coordinates from the broader geographic pattern.\nWith 999 simulations, the smallest attainable one-sided Monte Carlo p-value is\n0.001; it is never zero.\n\nFor planning, a departure from uniform randomness means that service locations\nare spatially uneven. It does not establish oversupply, undersupply, or a causal\nattraction between providers. Residential distribution is an obvious omitted factor.\n\n## 4. Bandwidth selection and density units\n\nBandwidth controls the scale at which a concentration is visible. I compute four\nselectors rather than importing the numerical bandwidth printed in the lesson.\nScott's rule returns separate x and y smoothing scales, so its two values should\nnot be mistaken for two competing scalar solutions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchildcare_km <- spatstat.geom::rescale(childcare_ppp, 1000, \"km\")\nbw_diggle <- bw.diggle(childcare_km)\nbw_ppl <- bw.ppl(childcare_km)\nbw_cvl <- bw.CvL(childcare_km)\nbw_scott <- bw.scott(childcare_km)\nbandwidth_table <- data.frame(\n  method = c(\"Diggle\", \"Likelihood cross-validation\", \"Cronie-van Lieshout\", \"Scott x\", \"Scott y\"),\n  bandwidth_km = c(bw_diggle, bw_ppl, bw_cvl, bw_scott)\n)\nbandwidth_table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                       method bandwidth_km\n1                      Diggle    0.2959711\n2 Likelihood cross-validation    0.3789970\n3         Cronie-van Lieshout    4.3572094\n4                     Scott x    2.1597490\n5                     Scott y    1.3964550\n```\n\n\n:::\n:::\n\n\nThe Diggle result is **296 m**; likelihood\ncross-validation gives **379 m**. The table\ndocuments how far alternative selectors move the scale of the question.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 100 m square cells resolve the smoothing surface more clearly than a 128x128 default grid.\nkde_m <- density(childcare_ppp, sigma = as.numeric(bw_diggle) * 1000,\n                 edge = TRUE, kernel = \"gaussian\", eps = 100)\nkde_km <- density(childcare_km, sigma = as.numeric(bw_diggle),\n                  edge = TRUE, kernel = \"gaussian\", eps = 0.1)\nstopifnot(isTRUE(all.equal(kde_m$v * 1e6, kde_km$v, tolerance = 1e-6)))\ndata.frame(units = c(\"records / m2\", \"records / km2\"),\n           maximum = c(max(kde_m$v, na.rm = TRUE), max(kde_km$v, na.rm = TRUE)),\n           integrated_records = c(integral.im(kde_m), integral.im(kde_km)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          units      maximum integrated_records\n1  records / m2 3.586835e-05           1928.254\n2 records / km2 3.586835e+01           1928.254\n```\n\n\n:::\n:::\n\n\nThe two computations describe the same surface. Rescaling coordinates from\nmetres to kilometres multiplies density values by one million. I verify that\nidentity numerically, using matched 100 m cells. The raster integral is a useful\ndiagnostic against the input count; pixel discretisation and boundary correction\nmean it need not reproduce the count exactly. Small negative values close to\nmachine precision are numerical convolution artefacts, not negative services.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkde_ppl <- density(childcare_km, sigma = as.numeric(bw_ppl), edge = TRUE, eps = 0.1)\nplot_surfaces <- function(surfaces, titles, ncol = 2) {\n  old <- par(mfrow = c(ceiling(length(surfaces) / ncol), ncol), mar = c(2, 2, 3, 3))\n  on.exit(par(old))\n  common_range <- range(unlist(lapply(surfaces, function(x) x$v)), na.rm = TRUE)\n  for (i in seq_along(surfaces)) {\n    plot(surfaces[[i]], main = titles[i], zlim = common_range,\n         col = hcl.colors(100, \"Viridis\"), ribargs = list(las = 1))\n  }\n}\nplot_surfaces(list(kde_km, kde_ppl), c(\"Diggle bandwidth\", \"Likelihood bandwidth\"))\n```\n\n::: {.cell-output-display}\n![Diggle and likelihood bandwidths, with a shared intensity scale in records per km². Map coordinates are kilometres.](index_files/figure-html/bandwidth-comparison-1.png){fig-alt='Two comparable childcare kernel density maps using different bandwidth selectors.' width=1350}\n:::\n:::\n\n\nA narrower bandwidth preserves more local peaks; a wider bandwidth merges nearby\npeaks into broader concentrations. I use the same colour limits so differences\nare not created by separately stretched legends.\n\n## 5. Kernel shape, fixed and adaptive smoothing\n\nFirst I hold bandwidth constant and change the kernel. This isolates kernel\nshape from bandwidth selection, with the same spatial resolution and intensity\nscale throughout.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkernels <- c(\"gaussian\", \"epanechnikov\", \"quartic\", \"disc\")\nkernel_maps <- lapply(kernels, function(k) density(childcare_km,\n  sigma = as.numeric(bw_diggle), kernel = k, edge = TRUE, eps = 0.1))\nplot_surfaces(kernel_maps, tools::toTitleCase(kernels))\n```\n\n::: {.cell-output-display}\n![Gaussian, Epanechnikov, quartic and disc kernels at the same Diggle bandwidth; records per km².](index_files/figure-html/kernel-comparison-1.png){fig-alt='Four childcare density surfaces comparing kernel shapes.' width=1350}\n:::\n:::\n\n\nThe compact-support kernels assign no contribution beyond their support, whereas\na Gaussian kernel decays gradually. Broad concentrations should be read across\nthe panels; an isolated bright pixel is not evidence of a statistically significant hotspot.\n\nNext I compare the lesson's **600 m fixed bandwidth** with an adaptive kernel\nestimate. The adaptive method allows local smoothing scales to vary with the\npilot intensity, which can retain detail where records are dense.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkde_fixed <- density(childcare_km, sigma = 0.6, edge = TRUE, eps = 0.1)\nkde_adaptive <- adaptive.density(childcare_km, method = \"kernel\",\n                                 h0 = as.numeric(bw_ppl), eps = 0.1)\nplot_surfaces(list(kde_fixed, kde_adaptive), c(\"Fixed: 600 m\", \"Adaptive kernel\"))\n```\n\n::: {.cell-output-display}\n![Fixed 600 m and adaptive kernel estimates on a shared records-per-km² scale.](index_files/figure-html/adaptive-kde-1.png){fig-alt='Side-by-side fixed and adaptive childcare density estimates.' width=1350}\n:::\n:::\n\n\nAdaptive smoothing changes the estimator, so differences cannot be attributed\nonly to a single bandwidth value. Neither surface adjusts for population or\ncentre capacity. A high value describes many records per land area.\n\n## 6. A geographically correct KDE map\n\n::: {.callout-important title=\"Raster values and map coordinates use different units\"}\nEPSG:3414 requires metre coordinates. Assigning it to an image whose coordinates\nwere divided by 1,000 would put the raster in the wrong place. I convert the\n**metre-coordinate image** to `SpatRaster`, multiply only its **density values**\nby one million, and then attach EPSG:3414. The subzone overlay and scale bar are\ntherefore geographically consistent.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Keep the raster coordinates in metres, but convert its VALUES to records/km2.\nkde_raster <- rast(kde_m) * 1e6\ncrs(kde_raster) <- \"EPSG:3414\"\nnames(kde_raster) <- \"records_km2\"\nstopifnot(all(abs(as.vector(ext(kde_raster)) -\n                    c(kde_m$xrange, kde_m$yrange)) < 1e-5))\ntm_shape(kde_raster) +\n  tm_raster(col = \"records_km2\", col.scale = tm_scale_continuous(values = \"viridis\"),\n            col.legend = tm_legend(title = \"Records per km²\")) +\n  tm_shape(subzones) + tm_borders(col = \"white\", lwd = 0.2) +\n  tm_title(\"Childcare intensity: Diggle bandwidth\") +\n  tm_compass(position = tm_pos_in(\"right\", \"top\")) +\n  tm_scalebar(position = tm_pos_in(\"left\", \"bottom\")) +\n  tm_layout(frame = FALSE)\n```\n\n::: {.cell-output-display}\n![Childcare service intensity, with correctly aligned MP2019 boundaries and a continuous sequential legend.](index_files/figure-html/cartographic-kde-1.png){fig-alt='Cartographic childcare kernel density map with boundaries, compass and scale bar.' width=1350}\n:::\n:::\n\n\nI retain a continuous sequential palette because KDE is a continuous estimate.\nDiscretising it into quantiles would change the visual message to relative\nranks and hide the numeric gap between intensities.\n\n## 7. Planning-area comparison\n\nThe four local windows are Punggol, Tampines, Choa Chu Kang and Jurong West.\nAlthough the source boundary contains subzones, the comparisons below are at\n**planning-area** level after dissolving the relevant subzones.\n\n\n::: {.cell}\n\n```{.r .cell-code}\narea_names <- c(\"PUNGGOL\", \"TAMPINES\", \"CHOA CHU KANG\", \"JURONG WEST\")\nareas <- lapply(area_names, function(nm) st_union(filter(subzones, PLN_AREA_N == nm)))\nnames(areas) <- area_names\narea_windows <- lapply(areas, as.owin)\narea_patterns <- lapply(area_windows, function(w) childcare_ppp[w])\narea_summary <- data.frame(\n  planning_area = area_names,\n  records = vapply(area_patterns, npoints, integer(1)),\n  locations = vapply(area_patterns, function(x) npoints(unique(x)), integer(1)),\n  km2 = vapply(area_windows, area.owin, numeric(1)) / 1e6\n) |>\n  mutate(records_per_km2 = records / km2)\narea_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              planning_area records locations       km2 records_per_km2\nPUNGGOL             PUNGGOL      72        65  9.374274        7.680595\nTAMPINES           TAMPINES     117       105 20.795431        5.626236\nCHOA CHU KANG CHOA CHU KANG      74        67  6.117294       12.096852\nJURONG WEST     JURONG WEST     110        99 14.680536        7.492914\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nold <- par(mfrow = c(2, 2), mar = c(2, 2, 3, 1))\nfor (nm in area_names) plot(spatstat.geom::rescale(area_patterns[[nm]], 1000, \"km\"),\n                           main = tools::toTitleCase(tolower(nm)), pch = 16, cex = 0.5)\n```\n\n::: {.cell-output-display}\n![Service records in the four planning-area windows; coordinates are kilometres.](index_files/figure-html/area-pattern-map-1.png){fig-alt='Childcare point patterns in Punggol, Tampines, Choa Chu Kang and Jurong West.' width=1350}\n:::\n\n```{.r .cell-code}\npar(old)\n```\n:::\n\n\nChoa Chu Kang has 12.1\nrecords/km² compared with 5.6\nin Tampines. This is an area-normalised comparison, not a ranking of service\nadequacy. The actual distribution inside each polygon is still important.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(20260920)\narea_ce <- lapply(area_patterns[c(\"CHOA CHU KANG\", \"TAMPINES\")], function(x)\n  clarkevans.test(x, correction = \"none\", alternative = \"two.sided\",\n                 method = \"MonteCarlo\", nsim = 999))\ndata.frame(area = names(area_ce), R = vapply(area_ce, function(x) unname(x$statistic), numeric(1)),\n           p = vapply(area_ce, function(x) x$p.value, numeric(1)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                       area         R     p\nCHOA CHU KANG CHOA CHU KANG 0.8409673 0.002\nTAMPINES           TAMPINES 0.6681710 0.002\n```\n\n\n:::\n:::\n\n\nHere the alternative is two-sided: either unusually short or unusually long\nnearest-neighbour distances would be relevant. I explicitly select\n`method = \"MonteCarlo\"`; supplying `nsim` alone does not change the default\nasymptotic method. These two comparisons are exploratory.\n\n\n::: {.cell}\n\n```{.r .cell-code}\narea_km <- lapply(area_patterns, spatstat.geom::rescale, s = 1000, unitname = \"km\")\narea_bw <- vapply(area_km, function(x) as.numeric(bw.diggle(x)), numeric(1))\narea_kde <- Map(function(x, b) density(x, sigma = b, edge = TRUE, eps = 0.05), area_km, area_bw)\ndata.frame(area = area_names, bandwidth_m = 1000 * area_bw)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                       area bandwidth_m\nPUNGGOL             PUNGGOL    207.8854\nTAMPINES           TAMPINES    118.9279\nCHOA CHU KANG CHOA CHU KANG    164.9062\nJURONG WEST     JURONG WEST    239.2470\n```\n\n\n:::\n\n```{.r .cell-code}\nplot_surfaces(area_kde, tools::toTitleCase(tolower(area_names)))\n```\n\n::: {.cell-output-display}\n![Planning-area KDE with area-specific Diggle bandwidths and common intensity limits; records per km².](index_files/figure-html/area-kde-1.png){fig-alt='Four planning-area childcare kernel density maps.' width=1350}\n:::\n:::\n\n\nEach bandwidth is fitted within its own window, so fine detail is not equally\nresolved in all panels. The common legend supports intensity comparison; a\ncommon fixed bandwidth would be preferable for a strictly matched smoothing\ncomparison. Local boundary correction cannot represent cross-boundary access\nto a nearby centre in another planning area.\n\n## 8. Interactive lookup\n\nThe map supports centre-name and address lookup. External background tiles\nrequire an internet connection; the analytical figures above are locally\nrendered assets and remain available independently of the tile provider.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"view\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nℹ tmap modes \"plot\" - \"view\"\n```\n\n\n:::\n\n```{.r .cell-code}\ninteractive_points <- tm_shape(subzones) + tm_borders(col = \"#6f82aa\") +\n  tm_shape(childcare[inside, ]) +\n  tm_dots(col = \"#465d91\", popup = tm_popup(\n    vars = c(\"Centre\" = \"NAME\", \"Address\" = \"ADDRESSSTREETNAME\")))\nprint(interactive_points)\ntmap_mode(\"plot\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nℹ tmap modes \"plot\" - \"view\"\n```\n\n\n:::\n:::\n\n\n## 9. What I learned\n\nThe observation window is part of the statistical model, not just a cartographic\nframe. Counting service records and counting distinct locations are different\nquestions, especially when several records share a coordinate. I also found that\ndensity units and coordinate units must be checked separately: a convincing\ncolour surface can still be geographically wrong if its extent is mislabelled.\n\nThe most useful next extension would relate service capacity to the residential\npopulation of young children and realistic travel distances. This exercise alone\ncannot identify unmet demand or explain why providers locate together.\n\n## Reproducibility and references\n\nAll executed code is supplied in [`R/prepare.R`](R/prepare.R) and\n[`R/analysis.R`](R/analysis.R). The page reads those labelled sections directly,\nso the displayed code and executed code have one source. Run the download script\nonce, then `quarto render . --execute` from the repository root to rebuild the\nwhole site. The shared preparation also allows 2B to render independently.\nRaw and derived data stay in ignored folders. [`data/README.md`](data/README.md)\nrecords the sources, checksums and assumptions.\n\nMethod references: [course Chapter 4](https://r4gdsa.netlify.app/chap04.html),\n[spatstat documentation](https://spatstat.org/),\n[adaptive density reference](https://search.r-project.org/CRAN/refmans/spatstat.explore/html/adaptive.density.html),\nand [sf coordinate transformations](https://r-spatial.github.io/sf/reference/st_transform.html).\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.5.3 (2026-03-11 ucrt)\nPlatform: x86_64-w64-mingw32/x64\nRunning under: Windows 11 x64 (build 26200)\n\nMatrix products: default\n  LAPACK version 3.12.1\n\nlocale:\n[1] LC_COLLATE=English_United States.utf8 \n[2] LC_CTYPE=English_United States.utf8   \n[3] LC_MONETARY=English_United States.utf8\n[4] LC_NUMERIC=C                          \n[5] LC_TIME=English_United States.utf8    \n\ntime zone: Asia/Shanghai\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n [1] tmap_4.4-1             terra_1.9-50           spatstat.explore_3.8-2\n [4] nlme_3.1-168           spatstat.random_3.5-1  spatstat.geom_3.8-3   \n [7] spatstat.univar_3.2-0  spatstat.data_3.1-9    dplyr_1.2.1           \n[10] sf_1.1-3              \n\nloaded via a namespace (and not attached):\n [1] xfun_0.60               raster_3.6-32           htmlwidgets_1.6.4      \n [4] leafgl_0.2.4            spatstat.sparse_3.2-0   lattice_0.22-9         \n [7] yyjsonr_0.1.22          leaflet.providers_3.0.0 vctrs_0.7.3            \n[10] tools_4.5.3             crosstalk_1.2.2         spatstat.utils_3.2-5   \n[13] generics_0.1.4          parallel_4.5.3          goftest_1.2-3          \n[16] tibble_3.3.1            proxy_0.4-29            pkgconfig_2.0.3        \n[19] Matrix_1.7-4            KernSmooth_2.23-26      data.table_1.18.6.1    \n[22] leaflet_2.2.3           lifecycle_1.0.5         compiler_4.5.3         \n[25] deldir_2.0-4            codetools_0.2-20        leafsync_0.1.0         \n[28] leaflegend_1.2.8        stars_0.7-3             htmltools_0.5.9        \n[31] class_7.3-23            yaml_2.3.12             jquerylib_0.1.4        \n[34] pillar_1.11.1           classInt_0.4-11         lwgeom_0.2-17          \n[37] wk_0.9.5                abind_1.4-8             tidyselect_1.2.1       \n[40] digest_0.6.39           polyclip_1.10-7         fastmap_1.2.0          \n[43] grid_4.5.3              colorspace_2.1-3        cli_3.6.6              \n[46] logger_0.4.3            magrittr_2.0.5          maptiles_0.12.0        \n[49] base64enc_0.1-6         XML_3.99-0.24           cols4all_0.10          \n[52] leafem_0.2.5            e1071_1.7-17            tensor_1.5.1           \n[55] sp_2.2-3                rmarkdown_2.31          otel_0.2.0             \n[58] png_0.1-9               evaluate_1.0.5          knitr_1.51             \n[61] tmaptools_3.3           s2_1.1.12               rlang_1.3.0            \n[64] Rcpp_1.1.2              glue_1.8.1              DBI_1.3.0              \n[67] rstudioapi_0.19.0       jsonlite_2.0.0          R6_2.6.1               \n[70] spacesXYZ_1.6-0         units_1.0-1            \n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}