<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Zhenhua Liu">
<meta name="dcterms.date" content="2026-09-19">

<title>Hands-on Exercise 2A – ISSS626-GAA</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-d89924325737da961fd3c7ac1ec1be2d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed exercise-page quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">ISSS626-GAA</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Hands-on Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercise">    
        <li>
    <a class="dropdown-item" href="../hands-on-exercise-1a/index.html">
 <span class="dropdown-text">Hands-on Exercise 1A</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../hands-on-exercise-1b/index.html">
 <span class="dropdown-text">Hands-on Exercise 1B</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../handson2A/index.html">
 <span class="dropdown-text">Hands-on Exercise 2A</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../handson2B/index.html">
 <span class="dropdown-text">Hands-on Exercise 2B</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#setup-and-source-data" id="toc-setup-and-source-data" class="nav-link" data-scroll-target="#setup-and-source-data">1. Setup and source data</a></li>
  <li><a href="#geometry-crs-and-the-observation-window" id="toc-geometry-crs-and-the-observation-window" class="nav-link" data-scroll-target="#geometry-crs-and-the-observation-window">2. Geometry, CRS and the observation window</a></li>
  <li><a href="#nearest-neighbour-analysis" id="toc-nearest-neighbour-analysis" class="nav-link" data-scroll-target="#nearest-neighbour-analysis">3. Nearest-neighbour analysis</a></li>
  <li><a href="#bandwidth-selection-and-density-units" id="toc-bandwidth-selection-and-density-units" class="nav-link" data-scroll-target="#bandwidth-selection-and-density-units">4. Bandwidth selection and density units</a></li>
  <li><a href="#kernel-shape-fixed-and-adaptive-smoothing" id="toc-kernel-shape-fixed-and-adaptive-smoothing" class="nav-link" data-scroll-target="#kernel-shape-fixed-and-adaptive-smoothing">5. Kernel shape, fixed and adaptive smoothing</a></li>
  <li><a href="#a-geographically-correct-kde-map" id="toc-a-geographically-correct-kde-map" class="nav-link" data-scroll-target="#a-geographically-correct-kde-map">6. A geographically correct KDE map</a></li>
  <li><a href="#planning-area-comparison" id="toc-planning-area-comparison" class="nav-link" data-scroll-target="#planning-area-comparison">7. Planning-area comparison</a></li>
  <li><a href="#interactive-lookup" id="toc-interactive-lookup" class="nav-link" data-scroll-target="#interactive-lookup">8. Interactive lookup</a></li>
  <li><a href="#what-i-learned" id="toc-what-i-learned" class="nav-link" data-scroll-target="#what-i-learned">9. What I learned</a></li>
  <li><a href="#reproducibility-and-references" id="toc-reproducibility-and-references" class="nav-link" data-scroll-target="#reproducibility-and-references">Reproducibility and references</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Hands-on Exercise 2A</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
<p class="subtitle lead">First-order spatial point patterns and childcare intensity</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Zhenhua Liu </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 19, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">Overview</h2>
<p>Where are childcare services concentrated, and how much does the answer depend on the observation window and smoothing method? I use Singapore’s childcare locations to examine intensity at national and planning-area scales. A nearest-neighbour test provides a benchmark against spatial randomness; kernel density estimation (KDE) then shows where concentrations occur. These are complementary summaries, not a measure of whether local demand is adequately served.</p>
<p>This exercise follows the workflow in <a href="https://r4gdsa.netlify.app/chap04.html">course Chapter 4</a>. The next page, <a href="../handson2B/index.html">Hands-on Exercise 2B</a>, examines spatial relationships over a range of distances.</p>
</section>
<section id="setup-and-source-data" class="level2">
<h2 class="anchored" data-anchor-id="setup-and-source-data">1. Setup and source data</h2>
<p><code>sf</code> handles vector geometry, the <code>spatstat</code> component packages provide planar point-pattern analysis, and <code>terra</code> carries the density raster into <code>tmap</code>. <code>dplyr</code> supplies the attribute filtering used to define the study region. Packages are installed before rendering, so the page never changes its environment halfway through an analysis.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Linking to GEOS 3.14.1, GDAL 3.12.1, PROJ 9.7.1; sf_use_s2() is TRUE</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(spatstat.geom)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: spatstat.data</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: spatstat.univar</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>spatstat.univar 3.2-0</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>spatstat.geom 3.8-3</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(spatstat.explore)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: spatstat.random</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>spatstat.random 3.5-1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: nlme</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'nlme'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    collapse</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>spatstat.explore 3.8-2</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(spatstat.random)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(terra)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>terra 1.9.50</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'terra'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:spatstat.geom':

    area, delaunay, is.empty, rescale, rotate, shift, where.max,
    where.min</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tmap)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 method overwritten by 'stars':
  method                  from
  st_interpolate_aw.stars sf  </code></pre>
</div>
</div>
<p>I use the official <a href="https://data.gov.sg/datasets/d_5d668e3f544335f8028f546827b773b4/view">ECDA Child Care Services GeoJSON</a> and <a href="https://data.gov.sg/datasets/d_8594ae9ff96d0c708bc2af633048edfb/view">URA Master Plan 2019 Subzone Boundary (No Sea)</a>. The download routine is provided in <a href="R/download-data.R"><code>R/download-data.R</code></a>. <code>NAME</code> and <code>ADDRESSSTREETNAME</code> describe each service; <code>PLN_AREA_N</code> and <code>SUBZONE_N</code> identify the administrative units.</p>
<div class="callout callout-style-default callout-note callout-titled" title="The data date is not the download date">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>The data date is not the download date
</div>
</div>
<div class="callout-body-container callout-body">
<p>The ECDA portal describes this layer as <strong>December 2021 data</strong>, despite its 2026 portal update. These maps describe that historical service snapshot, downloaded in September 2026. They should not be presented as a current inventory. Both GeoJSON files already contain separate attributes, so no HTML-description parsing is needed.</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>raw_dir <span class="ot">&lt;-</span> <span class="st">"handson2A/data/raw"</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>required <span class="ot">&lt;-</span> <span class="fu">file.path</span>(raw_dir, <span class="fu">c</span>(<span class="st">"childcare.geojson"</span>, <span class="st">"mp19-subzone.geojson"</span>))</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">all</span>(<span class="fu">file.exists</span>(required))) <span class="fu">stop</span>(<span class="st">"Run source('handson2A/R/download-data.R') first."</span>)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>childcare_raw <span class="ot">&lt;-</span> <span class="fu">st_read</span>(required[<span class="dv">1</span>], <span class="at">quiet =</span> <span class="cn">TRUE</span>)</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>subzones_raw <span class="ot">&lt;-</span> <span class="fu">st_read</span>(required[<span class="dv">2</span>], <span class="at">quiet =</span> <span class="cn">TRUE</span>)</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>input_audit <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">dataset =</span> <span class="fu">c</span>(<span class="st">"Child Care Services"</span>, <span class="st">"MP2019 subzones"</span>),</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">records =</span> <span class="fu">c</span>(<span class="fu">nrow</span>(childcare_raw), <span class="fu">nrow</span>(subzones_raw)),</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">geometry =</span> <span class="fu">c</span>(<span class="fu">as.character</span>(<span class="fu">unique</span>(<span class="fu">st_geometry_type</span>(childcare_raw))),</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>               <span class="fu">as.character</span>(<span class="fu">unique</span>(<span class="fu">st_geometry_type</span>(subzones_raw)))),</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">epsg =</span> <span class="fu">c</span>(<span class="fu">st_crs</span>(childcare_raw)<span class="sc">$</span>epsg, <span class="fu">st_crs</span>(subzones_raw)<span class="sc">$</span>epsg),</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">empty =</span> <span class="fu">c</span>(<span class="fu">sum</span>(<span class="fu">st_is_empty</span>(childcare_raw)), <span class="fu">sum</span>(<span class="fu">st_is_empty</span>(subzones_raw))),</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">invalid =</span> <span class="fu">c</span>(<span class="fu">sum</span>(<span class="sc">!</span><span class="fu">st_is_valid</span>(childcare_raw)), <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">st_is_valid</span>(subzones_raw)))</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>input_audit</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>              dataset records     geometry epsg empty invalid
1 Child Care Services    1925        POINT 4326     0       0
2     MP2019 subzones     332 MULTIPOLYGON 4326     0       6</code></pre>
</div>
</div>
</section>
<section id="geometry-crs-and-the-observation-window" class="level2">
<h2 class="anchored" data-anchor-id="geometry-crs-and-the-observation-window">2. Geometry, CRS and the observation window</h2>
<p>I transform both layers to <strong>SVY21 / Singapore TM (EPSG:3414)</strong> so coordinates and distances are in metres. <code>st_transform()</code> changes coordinate values; assigning a CRS label alone would not perform that conversion. I validate the polygons and use the course’s exclusions for the Southern Group, Western Islands and North-Eastern Islands. This is a specified administrative study window, not a claim that every remaining square metre is habitable land.</p>
<p>Dissolving subzone boundaries with <code>st_union()</code> produces one region for <code>as.owin()</code>. An <code>owin</code> stores the observation boundary; a <code>ppp</code> stores events inside that boundary. Using the points’ bounding rectangle instead would include unobserved sea and change both expected density and simulated patterns.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="sc">!</span><span class="fu">any</span>(<span class="fu">st_is_empty</span>(childcare_raw)), <span class="sc">!</span><span class="fu">any</span>(<span class="fu">st_is_empty</span>(subzones_raw)),</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>          <span class="fu">all</span>(<span class="fu">st_geometry_type</span>(childcare_raw) <span class="sc">==</span> <span class="st">"POINT"</span>))</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>childcare <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(childcare_raw, <span class="dv">3414</span>)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>subzones <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(<span class="fu">st_make_valid</span>(subzones_raw), <span class="dv">3414</span>)</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>subzones <span class="ot">&lt;-</span> <span class="fu">filter</span>(subzones, SUBZONE_N <span class="sc">!=</span> <span class="st">"SOUTHERN GROUP"</span>,</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>                   <span class="sc">!</span>PLN_AREA_N <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"WESTERN ISLANDS"</span>, <span class="st">"NORTH-EASTERN ISLANDS"</span>))</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">st_crs</span>(childcare) <span class="sc">==</span> <span class="fu">st_crs</span>(subzones), <span class="sc">!</span><span class="fu">st_is_longlat</span>(childcare))</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>singapore <span class="ot">&lt;-</span> <span class="fu">st_union</span>(subzones)</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>sg_window <span class="ot">&lt;-</span> <span class="fu">as.owin</span>(singapore)</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>xy <span class="ot">&lt;-</span> <span class="fu">st_coordinates</span>(childcare)</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>inside <span class="ot">&lt;-</span> <span class="fu">inside.owin</span>(xy[, <span class="dv">1</span>], xy[, <span class="dv">2</span>], sg_window)</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>duplicate_location <span class="ot">&lt;-</span> <span class="fu">duplicated</span>(<span class="fu">as.data.frame</span>(xy))</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Co-located records may be different operators. Keep them for service intensity.</span></span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>childcare_ppp <span class="ot">&lt;-</span> <span class="fu">ppp</span>(xy[inside, <span class="dv">1</span>], xy[inside, <span class="dv">2</span>], <span class="at">window =</span> sg_window,</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>                     <span class="at">checkdup =</span> <span class="cn">FALSE</span>)</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a><span class="fu">unitname</span>(childcare_ppp) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"metre"</span>, <span class="st">"metres"</span>)</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>childcare_unique <span class="ot">&lt;-</span> <span class="fu">unique</span>(childcare_ppp)</span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>quality_audit <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">measure =</span> <span class="fu">c</span>(<span class="st">"Imported records"</span>, <span class="st">"Retained subzones"</span>, <span class="st">"Outside study window"</span>,</span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a>              <span class="st">"Records at repeated coordinates (beyond first)"</span>, <span class="st">"Records in window"</span>,</span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a>              <span class="st">"Distinct locations in window"</span>, <span class="st">"Study area (km2)"</span>),</span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">value =</span> <span class="fu">c</span>(<span class="fu">nrow</span>(childcare), <span class="fu">nrow</span>(subzones), <span class="fu">sum</span>(<span class="sc">!</span>inside), <span class="fu">sum</span>(duplicate_location),</span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a>            <span class="fu">npoints</span>(childcare_ppp), <span class="fu">npoints</span>(childcare_unique), <span class="fu">area.owin</span>(sg_window) <span class="sc">/</span> <span class="fl">1e6</span>)</span>
<span id="cb27-24"><a href="#cb27-24" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-25"><a href="#cb27-25" aria-hidden="true" tabindex="-1"></a>quality_audit</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                         measure     value
1                               Imported records 1925.0000
2                              Retained subzones  327.0000
3                           Outside study window    0.0000
4 Records at repeated coordinates (beyond first)  187.0000
5                              Records in window 1925.0000
6                   Distinct locations in window 1738.0000
7                               Study area (km2)  669.5167</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dir.create</span>(<span class="st">"handson2A/data/derived"</span>, <span class="at">recursive =</span> <span class="cn">TRUE</span>, <span class="at">showWarnings =</span> <span class="cn">FALSE</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">saveRDS</span>(subzones, <span class="st">"handson2A/data/derived/subzones-clean.rds"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The audit retains <strong>1925 service records</strong> at <strong>1738 distinct coordinates</strong>. There are 187 records beyond the first at repeated coordinates and 0 points outside the window. Repeated coordinates are not enough evidence to delete a service: several operators or records can share a building. I retain records for provision intensity and also test distinct locations as a sensitivity check. No random jitter is added to manufacture separation.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>ℹ tmap modes "plot" - "view"
ℹ toggle with `tmap::ttm()`</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(subzones) <span class="sc">+</span> <span class="fu">tm_polygons</span>(<span class="at">fill =</span> <span class="st">"#eef3f8"</span>, <span class="at">col =</span> <span class="st">"white"</span>, <span class="at">lwd =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(childcare[inside, ]) <span class="sc">+</span> <span class="fu">tm_dots</span>(<span class="at">col =</span> <span class="st">"#465d91"</span>, <span class="at">size =</span> <span class="fl">0.025</span>) <span class="sc">+</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_title</span>(<span class="st">"Childcare service records in Singapore"</span>) <span class="sc">+</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_scalebar</span>(<span class="at">position =</span> <span class="fu">tm_pos_in</span>(<span class="st">"left"</span>, <span class="st">"bottom"</span>)) <span class="sc">+</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_compass</span>(<span class="at">position =</span> <span class="fu">tm_pos_in</span>(<span class="st">"right"</span>, <span class="st">"top"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/national-map-1.png" class="img-fluid figure-img" alt="Map of Singapore subzones overlaid with childcare service points." width="1350"></p>
<figcaption>Historical childcare service records within the selected MP2019 study window.</figcaption>
</figure>
</div>
</div>
</div>
<p>The overlay checks spatial alignment and reveals uneven concentrations. Large low-density areas include land that is not primarily residential, so national homogeneous randomness is a deliberately simple reference model.</p>
</section>
<section id="nearest-neighbour-analysis" class="level2">
<h2 class="anchored" data-anchor-id="nearest-neighbour-analysis">3. Nearest-neighbour analysis</h2>
<p>The Clark–Evans ratio compares observed mean nearest-neighbour distance with the homogeneous Poisson expectation. Values below one indicate shorter separations. I specify a one-sided clustering alternative for this national question, with a 5% significance threshold.</p>
<p>I show both the asymptotic approximation and 999 Monte Carlo simulations. The latter places the same number of points uniformly inside the actual window and applies the same uncorrected statistic to observed and simulated patterns. This accounts for window shape in the reference distribution, although the uncorrected ratio itself still has edge bias. Nearest-neighbour statistics involve interpoint distances; their inclusion here follows the course’s sequence, while KDE is the main first-order intensity method.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">20260919</span>)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>ce_z <span class="ot">&lt;-</span> <span class="fu">clarkevans.test</span>(childcare_ppp, <span class="at">correction =</span> <span class="st">"none"</span>,</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">alternative =</span> <span class="st">"clustered"</span>, <span class="at">method =</span> <span class="st">"asymptotic"</span>)</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>ce_mc <span class="ot">&lt;-</span> <span class="fu">clarkevans.test</span>(childcare_ppp, <span class="at">correction =</span> <span class="st">"none"</span>,</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>                        <span class="at">alternative =</span> <span class="st">"clustered"</span>, <span class="at">method =</span> <span class="st">"MonteCarlo"</span>, <span class="at">nsim =</span> <span class="dv">999</span>)</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>ce_unique <span class="ot">&lt;-</span> <span class="fu">clarkevans.test</span>(childcare_unique, <span class="at">correction =</span> <span class="st">"none"</span>,</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>                            <span class="at">alternative =</span> <span class="st">"clustered"</span>, <span class="at">method =</span> <span class="st">"MonteCarlo"</span>, <span class="at">nsim =</span> <span class="dv">999</span>)</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>ce_table <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">analysis =</span> <span class="fu">c</span>(<span class="st">"Service records: normal approximation"</span>, <span class="st">"Service records: Monte Carlo"</span>,</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>               <span class="st">"Distinct locations: Monte Carlo"</span>),</span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">R =</span> <span class="fu">c</span>(<span class="fu">unname</span>(ce_z<span class="sc">$</span>statistic), <span class="fu">unname</span>(ce_mc<span class="sc">$</span>statistic), <span class="fu">unname</span>(ce_unique<span class="sc">$</span>statistic)),</span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">p =</span> <span class="fu">c</span>(ce_z<span class="sc">$</span>p.value, ce_mc<span class="sc">$</span>p.value, ce_unique<span class="sc">$</span>p.value)</span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a>ce_table</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                               analysis         R     p
1 Service records: normal approximation 0.5353162 0.000
2          Service records: Monte Carlo 0.5353162 0.001
3       Distinct locations: Monte Carlo 0.6104213 0.001</code></pre>
</div>
</div>
<p>The record-level ratio is <strong>0.535</strong>, with simulated p = <strong>0.001</strong>. After collapsing co-located records, R becomes <strong>0.61</strong> and p becomes <strong>0.001</strong>. The comparison separates the contribution of shared coordinates from the broader geographic pattern. With 999 simulations, the smallest attainable one-sided Monte Carlo p-value is 0.001; it is never zero.</p>
<p>For planning, a departure from uniform randomness means that service locations are spatially uneven. It does not establish oversupply, undersupply, or a causal attraction between providers. Residential distribution is an obvious omitted factor.</p>
</section>
<section id="bandwidth-selection-and-density-units" class="level2">
<h2 class="anchored" data-anchor-id="bandwidth-selection-and-density-units">4. Bandwidth selection and density units</h2>
<p>Bandwidth controls the scale at which a concentration is visible. I compute four selectors rather than importing the numerical bandwidth printed in the lesson. Scott’s rule returns separate x and y smoothing scales, so its two values should not be mistaken for two competing scalar solutions.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>childcare_km <span class="ot">&lt;-</span> spatstat.geom<span class="sc">::</span><span class="fu">rescale</span>(childcare_ppp, <span class="dv">1000</span>, <span class="st">"km"</span>)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>bw_diggle <span class="ot">&lt;-</span> <span class="fu">bw.diggle</span>(childcare_km)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>bw_ppl <span class="ot">&lt;-</span> <span class="fu">bw.ppl</span>(childcare_km)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>bw_cvl <span class="ot">&lt;-</span> <span class="fu">bw.CvL</span>(childcare_km)</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>bw_scott <span class="ot">&lt;-</span> <span class="fu">bw.scott</span>(childcare_km)</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>bandwidth_table <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="fu">c</span>(<span class="st">"Diggle"</span>, <span class="st">"Likelihood cross-validation"</span>, <span class="st">"Cronie-van Lieshout"</span>, <span class="st">"Scott x"</span>, <span class="st">"Scott y"</span>),</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">bandwidth_km =</span> <span class="fu">c</span>(bw_diggle, bw_ppl, bw_cvl, bw_scott)</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>bandwidth_table</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                       method bandwidth_km
1                      Diggle    0.2959711
2 Likelihood cross-validation    0.3789970
3         Cronie-van Lieshout    4.3572094
4                     Scott x    2.1597490
5                     Scott y    1.3964550</code></pre>
</div>
</div>
<p>The Diggle result is <strong>296 m</strong>; likelihood cross-validation gives <strong>379 m</strong>. The table documents how far alternative selectors move the scale of the question.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 100 m square cells resolve the smoothing surface more clearly than a 128x128 default grid.</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>kde_m <span class="ot">&lt;-</span> <span class="fu">density</span>(childcare_ppp, <span class="at">sigma =</span> <span class="fu">as.numeric</span>(bw_diggle) <span class="sc">*</span> <span class="dv">1000</span>,</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">edge =</span> <span class="cn">TRUE</span>, <span class="at">kernel =</span> <span class="st">"gaussian"</span>, <span class="at">eps =</span> <span class="dv">100</span>)</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>kde_km <span class="ot">&lt;-</span> <span class="fu">density</span>(childcare_km, <span class="at">sigma =</span> <span class="fu">as.numeric</span>(bw_diggle),</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">edge =</span> <span class="cn">TRUE</span>, <span class="at">kernel =</span> <span class="st">"gaussian"</span>, <span class="at">eps =</span> <span class="fl">0.1</span>)</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">isTRUE</span>(<span class="fu">all.equal</span>(kde_m<span class="sc">$</span>v <span class="sc">*</span> <span class="fl">1e6</span>, kde_km<span class="sc">$</span>v, <span class="at">tolerance =</span> <span class="fl">1e-6</span>)))</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">units =</span> <span class="fu">c</span>(<span class="st">"records / m2"</span>, <span class="st">"records / km2"</span>),</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>           <span class="at">maximum =</span> <span class="fu">c</span>(<span class="fu">max</span>(kde_m<span class="sc">$</span>v, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="fu">max</span>(kde_km<span class="sc">$</span>v, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)),</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>           <span class="at">integrated_records =</span> <span class="fu">c</span>(<span class="fu">integral.im</span>(kde_m), <span class="fu">integral.im</span>(kde_km)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>          units      maximum integrated_records
1  records / m2 3.586835e-05           1928.254
2 records / km2 3.586835e+01           1928.254</code></pre>
</div>
</div>
<p>The two computations describe the same surface. Rescaling coordinates from metres to kilometres multiplies density values by one million. I verify that identity numerically, using matched 100 m cells. The raster integral is a useful diagnostic against the input count; pixel discretisation and boundary correction mean it need not reproduce the count exactly. Small negative values close to machine precision are numerical convolution artefacts, not negative services.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>kde_ppl <span class="ot">&lt;-</span> <span class="fu">density</span>(childcare_km, <span class="at">sigma =</span> <span class="fu">as.numeric</span>(bw_ppl), <span class="at">edge =</span> <span class="cn">TRUE</span>, <span class="at">eps =</span> <span class="fl">0.1</span>)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>plot_surfaces <span class="ot">&lt;-</span> <span class="cf">function</span>(surfaces, titles, <span class="at">ncol =</span> <span class="dv">2</span>) {</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  old <span class="ot">&lt;-</span> <span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="fu">ceiling</span>(<span class="fu">length</span>(surfaces) <span class="sc">/</span> ncol), ncol), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">3</span>))</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">on.exit</span>(<span class="fu">par</span>(old))</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>  common_range <span class="ot">&lt;-</span> <span class="fu">range</span>(<span class="fu">unlist</span>(<span class="fu">lapply</span>(surfaces, <span class="cf">function</span>(x) x<span class="sc">$</span>v)), <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq_along</span>(surfaces)) {</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">plot</span>(surfaces[[i]], <span class="at">main =</span> titles[i], <span class="at">zlim =</span> common_range,</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">col =</span> <span class="fu">hcl.colors</span>(<span class="dv">100</span>, <span class="st">"Viridis"</span>), <span class="at">ribargs =</span> <span class="fu">list</span>(<span class="at">las =</span> <span class="dv">1</span>))</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_surfaces</span>(<span class="fu">list</span>(kde_km, kde_ppl), <span class="fu">c</span>(<span class="st">"Diggle bandwidth"</span>, <span class="st">"Likelihood bandwidth"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/bandwidth-comparison-1.png" class="img-fluid figure-img" alt="Two comparable childcare kernel density maps using different bandwidth selectors." width="1350"></p>
<figcaption>Diggle and likelihood bandwidths, with a shared intensity scale in records per km². Map coordinates are kilometres.</figcaption>
</figure>
</div>
</div>
</div>
<p>A narrower bandwidth preserves more local peaks; a wider bandwidth merges nearby peaks into broader concentrations. I use the same colour limits so differences are not created by separately stretched legends.</p>
</section>
<section id="kernel-shape-fixed-and-adaptive-smoothing" class="level2">
<h2 class="anchored" data-anchor-id="kernel-shape-fixed-and-adaptive-smoothing">5. Kernel shape, fixed and adaptive smoothing</h2>
<p>First I hold bandwidth constant and change the kernel. This isolates kernel shape from bandwidth selection, with the same spatial resolution and intensity scale throughout.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>kernels <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"gaussian"</span>, <span class="st">"epanechnikov"</span>, <span class="st">"quartic"</span>, <span class="st">"disc"</span>)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>kernel_maps <span class="ot">&lt;-</span> <span class="fu">lapply</span>(kernels, <span class="cf">function</span>(k) <span class="fu">density</span>(childcare_km,</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">sigma =</span> <span class="fu">as.numeric</span>(bw_diggle), <span class="at">kernel =</span> k, <span class="at">edge =</span> <span class="cn">TRUE</span>, <span class="at">eps =</span> <span class="fl">0.1</span>))</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_surfaces</span>(kernel_maps, tools<span class="sc">::</span><span class="fu">toTitleCase</span>(kernels))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/kernel-comparison-1.png" class="img-fluid figure-img" alt="Four childcare density surfaces comparing kernel shapes." width="1350"></p>
<figcaption>Gaussian, Epanechnikov, quartic and disc kernels at the same Diggle bandwidth; records per km².</figcaption>
</figure>
</div>
</div>
</div>
<p>The compact-support kernels assign no contribution beyond their support, whereas a Gaussian kernel decays gradually. Broad concentrations should be read across the panels; an isolated bright pixel is not evidence of a statistically significant hotspot.</p>
<p>Next I compare the lesson’s <strong>600 m fixed bandwidth</strong> with an adaptive kernel estimate. The adaptive method allows local smoothing scales to vary with the pilot intensity, which can retain detail where records are dense.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>kde_fixed <span class="ot">&lt;-</span> <span class="fu">density</span>(childcare_km, <span class="at">sigma =</span> <span class="fl">0.6</span>, <span class="at">edge =</span> <span class="cn">TRUE</span>, <span class="at">eps =</span> <span class="fl">0.1</span>)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>kde_adaptive <span class="ot">&lt;-</span> <span class="fu">adaptive.density</span>(childcare_km, <span class="at">method =</span> <span class="st">"kernel"</span>,</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">h0 =</span> <span class="fu">as.numeric</span>(bw_ppl), <span class="at">eps =</span> <span class="fl">0.1</span>)</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_surfaces</span>(<span class="fu">list</span>(kde_fixed, kde_adaptive), <span class="fu">c</span>(<span class="st">"Fixed: 600 m"</span>, <span class="st">"Adaptive kernel"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/adaptive-kde-1.png" class="img-fluid figure-img" alt="Side-by-side fixed and adaptive childcare density estimates." width="1350"></p>
<figcaption>Fixed 600 m and adaptive kernel estimates on a shared records-per-km² scale.</figcaption>
</figure>
</div>
</div>
</div>
<p>Adaptive smoothing changes the estimator, so differences cannot be attributed only to a single bandwidth value. Neither surface adjusts for population or centre capacity. A high value describes many records per land area.</p>
</section>
<section id="a-geographically-correct-kde-map" class="level2">
<h2 class="anchored" data-anchor-id="a-geographically-correct-kde-map">6. A geographically correct KDE map</h2>
<div class="callout callout-style-default callout-important callout-titled" title="Raster values and map coordinates use different units">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Raster values and map coordinates use different units
</div>
</div>
<div class="callout-body-container callout-body">
<p>EPSG:3414 requires metre coordinates. Assigning it to an image whose coordinates were divided by 1,000 would put the raster in the wrong place. I convert the <strong>metre-coordinate image</strong> to <code>SpatRaster</code>, multiply only its <strong>density values</strong> by one million, and then attach EPSG:3414. The subzone overlay and scale bar are therefore geographically consistent.</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Keep the raster coordinates in metres, but convert its VALUES to records/km2.</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>kde_raster <span class="ot">&lt;-</span> <span class="fu">rast</span>(kde_m) <span class="sc">*</span> <span class="fl">1e6</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="fu">crs</span>(kde_raster) <span class="ot">&lt;-</span> <span class="st">"EPSG:3414"</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(kde_raster) <span class="ot">&lt;-</span> <span class="st">"records_km2"</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(<span class="fu">abs</span>(<span class="fu">as.vector</span>(<span class="fu">ext</span>(kde_raster)) <span class="sc">-</span></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">c</span>(kde_m<span class="sc">$</span>xrange, kde_m<span class="sc">$</span>yrange)) <span class="sc">&lt;</span> <span class="fl">1e-5</span>))</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(kde_raster) <span class="sc">+</span></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_raster</span>(<span class="at">col =</span> <span class="st">"records_km2"</span>, <span class="at">col.scale =</span> <span class="fu">tm_scale_continuous</span>(<span class="at">values =</span> <span class="st">"viridis"</span>),</span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">col.legend =</span> <span class="fu">tm_legend</span>(<span class="at">title =</span> <span class="st">"Records per km²"</span>)) <span class="sc">+</span></span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(subzones) <span class="sc">+</span> <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">"white"</span>, <span class="at">lwd =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_title</span>(<span class="st">"Childcare intensity: Diggle bandwidth"</span>) <span class="sc">+</span></span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_compass</span>(<span class="at">position =</span> <span class="fu">tm_pos_in</span>(<span class="st">"right"</span>, <span class="st">"top"</span>)) <span class="sc">+</span></span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_scalebar</span>(<span class="at">position =</span> <span class="fu">tm_pos_in</span>(<span class="st">"left"</span>, <span class="st">"bottom"</span>)) <span class="sc">+</span></span>
<span id="cb42-14"><a href="#cb42-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">frame =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/cartographic-kde-1.png" class="img-fluid figure-img" alt="Cartographic childcare kernel density map with boundaries, compass and scale bar." width="1350"></p>
<figcaption>Childcare service intensity, with correctly aligned MP2019 boundaries and a continuous sequential legend.</figcaption>
</figure>
</div>
</div>
</div>
<p>I retain a continuous sequential palette because KDE is a continuous estimate. Discretising it into quantiles would change the visual message to relative ranks and hide the numeric gap between intensities.</p>
</section>
<section id="planning-area-comparison" class="level2">
<h2 class="anchored" data-anchor-id="planning-area-comparison">7. Planning-area comparison</h2>
<p>The four local windows are Punggol, Tampines, Choa Chu Kang and Jurong West. Although the source boundary contains subzones, the comparisons below are at <strong>planning-area</strong> level after dissolving the relevant subzones.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>area_names <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"PUNGGOL"</span>, <span class="st">"TAMPINES"</span>, <span class="st">"CHOA CHU KANG"</span>, <span class="st">"JURONG WEST"</span>)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>areas <span class="ot">&lt;-</span> <span class="fu">lapply</span>(area_names, <span class="cf">function</span>(nm) <span class="fu">st_union</span>(<span class="fu">filter</span>(subzones, PLN_AREA_N <span class="sc">==</span> nm)))</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(areas) <span class="ot">&lt;-</span> area_names</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>area_windows <span class="ot">&lt;-</span> <span class="fu">lapply</span>(areas, as.owin)</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>area_patterns <span class="ot">&lt;-</span> <span class="fu">lapply</span>(area_windows, <span class="cf">function</span>(w) childcare_ppp[w])</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>area_summary <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">planning_area =</span> area_names,</span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">records =</span> <span class="fu">vapply</span>(area_patterns, npoints, <span class="fu">integer</span>(<span class="dv">1</span>)),</span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">locations =</span> <span class="fu">vapply</span>(area_patterns, <span class="cf">function</span>(x) <span class="fu">npoints</span>(<span class="fu">unique</span>(x)), <span class="fu">integer</span>(<span class="dv">1</span>)),</span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">km2 =</span> <span class="fu">vapply</span>(area_windows, area.owin, <span class="fu">numeric</span>(<span class="dv">1</span>)) <span class="sc">/</span> <span class="fl">1e6</span></span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">records_per_km2 =</span> records <span class="sc">/</span> km2)</span>
<span id="cb43-13"><a href="#cb43-13" aria-hidden="true" tabindex="-1"></a>area_summary</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>              planning_area records locations       km2 records_per_km2
PUNGGOL             PUNGGOL      72        65  9.374274        7.680595
TAMPINES           TAMPINES     117       105 20.795431        5.626236
CHOA CHU KANG CHOA CHU KANG      74        67  6.117294       12.096852
JURONG WEST     JURONG WEST     110        99 14.680536        7.492914</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>old <span class="ot">&lt;-</span> <span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">1</span>))</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (nm <span class="cf">in</span> area_names) <span class="fu">plot</span>(spatstat.geom<span class="sc">::</span><span class="fu">rescale</span>(area_patterns[[nm]], <span class="dv">1000</span>, <span class="st">"km"</span>),</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>                           <span class="at">main =</span> tools<span class="sc">::</span><span class="fu">toTitleCase</span>(<span class="fu">tolower</span>(nm)), <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">cex =</span> <span class="fl">0.5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/area-pattern-map-1.png" class="img-fluid figure-img" alt="Childcare point patterns in Punggol, Tampines, Choa Chu Kang and Jurong West." width="1350"></p>
<figcaption>Service records in the four planning-area windows; coordinates are kilometres.</figcaption>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(old)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Choa Chu Kang has 12.1 records/km² compared with 5.6 in Tampines. This is an area-normalised comparison, not a ranking of service adequacy. The actual distribution inside each polygon is still important.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">20260920</span>)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>area_ce <span class="ot">&lt;-</span> <span class="fu">lapply</span>(area_patterns[<span class="fu">c</span>(<span class="st">"CHOA CHU KANG"</span>, <span class="st">"TAMPINES"</span>)], <span class="cf">function</span>(x)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">clarkevans.test</span>(x, <span class="at">correction =</span> <span class="st">"none"</span>, <span class="at">alternative =</span> <span class="st">"two.sided"</span>,</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">method =</span> <span class="st">"MonteCarlo"</span>, <span class="at">nsim =</span> <span class="dv">999</span>))</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">area =</span> <span class="fu">names</span>(area_ce), <span class="at">R =</span> <span class="fu">vapply</span>(area_ce, <span class="cf">function</span>(x) <span class="fu">unname</span>(x<span class="sc">$</span>statistic), <span class="fu">numeric</span>(<span class="dv">1</span>)),</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>           <span class="at">p =</span> <span class="fu">vapply</span>(area_ce, <span class="cf">function</span>(x) x<span class="sc">$</span>p.value, <span class="fu">numeric</span>(<span class="dv">1</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                       area         R     p
CHOA CHU KANG CHOA CHU KANG 0.8409673 0.002
TAMPINES           TAMPINES 0.6681710 0.002</code></pre>
</div>
</div>
<p>Here the alternative is two-sided: either unusually short or unusually long nearest-neighbour distances would be relevant. I explicitly select <code>method = "MonteCarlo"</code>; supplying <code>nsim</code> alone does not change the default asymptotic method. These two comparisons are exploratory.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>area_km <span class="ot">&lt;-</span> <span class="fu">lapply</span>(area_patterns, spatstat.geom<span class="sc">::</span>rescale, <span class="at">s =</span> <span class="dv">1000</span>, <span class="at">unitname =</span> <span class="st">"km"</span>)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>area_bw <span class="ot">&lt;-</span> <span class="fu">vapply</span>(area_km, <span class="cf">function</span>(x) <span class="fu">as.numeric</span>(<span class="fu">bw.diggle</span>(x)), <span class="fu">numeric</span>(<span class="dv">1</span>))</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>area_kde <span class="ot">&lt;-</span> <span class="fu">Map</span>(<span class="cf">function</span>(x, b) <span class="fu">density</span>(x, <span class="at">sigma =</span> b, <span class="at">edge =</span> <span class="cn">TRUE</span>, <span class="at">eps =</span> <span class="fl">0.05</span>), area_km, area_bw)</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">area =</span> area_names, <span class="at">bandwidth_m =</span> <span class="dv">1000</span> <span class="sc">*</span> area_bw)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                       area bandwidth_m
PUNGGOL             PUNGGOL    207.8854
TAMPINES           TAMPINES    118.9279
CHOA CHU KANG CHOA CHU KANG    164.9062
JURONG WEST     JURONG WEST    239.2470</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_surfaces</span>(area_kde, tools<span class="sc">::</span><span class="fu">toTitleCase</span>(<span class="fu">tolower</span>(area_names)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/area-kde-1.png" class="img-fluid figure-img" alt="Four planning-area childcare kernel density maps." width="1350"></p>
<figcaption>Planning-area KDE with area-specific Diggle bandwidths and common intensity limits; records per km².</figcaption>
</figure>
</div>
</div>
</div>
<p>Each bandwidth is fitted within its own window, so fine detail is not equally resolved in all panels. The common legend supports intensity comparison; a common fixed bandwidth would be preferable for a strictly matched smoothing comparison. Local boundary correction cannot represent cross-boundary access to a nearby centre in another planning area.</p>
</section>
<section id="interactive-lookup" class="level2">
<h2 class="anchored" data-anchor-id="interactive-lookup">8. Interactive lookup</h2>
<p>The map supports centre-name and address lookup. External background tiles require an internet connection; the analytical figures above are locally rendered assets and remain available independently of the tile provider.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"view"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>ℹ tmap modes "plot" - "view"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>interactive_points <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(subzones) <span class="sc">+</span> <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">"#6f82aa"</span>) <span class="sc">+</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(childcare[inside, ]) <span class="sc">+</span></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>(<span class="at">col =</span> <span class="st">"#465d91"</span>, <span class="at">popup =</span> <span class="fu">tm_popup</span>(</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">vars =</span> <span class="fu">c</span>(<span class="st">"Centre"</span> <span class="ot">=</span> <span class="st">"NAME"</span>, <span class="st">"Address"</span> <span class="ot">=</span> <span class="st">"ADDRESSSTREETNAME"</span>)))</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(interactive_points)</span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>ℹ tmap modes "plot" - "view"</code></pre>
</div>
</div>
</section>
<section id="what-i-learned" class="level2">
<h2 class="anchored" data-anchor-id="what-i-learned">9. What I learned</h2>
<p>The observation window is part of the statistical model, not just a cartographic frame. Counting service records and counting distinct locations are different questions, especially when several records share a coordinate. I also found that density units and coordinate units must be checked separately: a convincing colour surface can still be geographically wrong if its extent is mislabelled.</p>
<p>The most useful next extension would relate service capacity to the residential population of young children and realistic travel distances. This exercise alone cannot identify unmet demand or explain why providers locate together.</p>
</section>
<section id="reproducibility-and-references" class="level2">
<h2 class="anchored" data-anchor-id="reproducibility-and-references">Reproducibility and references</h2>
<p>All executed code is supplied in <a href="R/prepare.R"><code>R/prepare.R</code></a> and <a href="R/analysis.R"><code>R/analysis.R</code></a>. The page reads those labelled sections directly, so the displayed code and executed code have one source. Run the download script once, then <code>quarto render . --execute</code> from the repository root to rebuild the whole site. The shared preparation also allows 2B to render independently. Raw and derived data stay in ignored folders. <a href="data/README.md"><code>data/README.md</code></a> records the sources, checksums and assumptions.</p>
<p>Method references: <a href="https://r4gdsa.netlify.app/chap04.html">course Chapter 4</a>, <a href="https://spatstat.org/">spatstat documentation</a>, <a href="https://search.r-project.org/CRAN/refmans/spatstat.explore/html/adaptive.density.html">adaptive density reference</a>, and <a href="https://r-spatial.github.io/sf/reference/st_transform.html">sf coordinate transformations</a>.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>R version 4.5.3 (2026-03-11 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 11 x64 (build 26200)

Matrix products: default
  LAPACK version 3.12.1

locale:
[1] LC_COLLATE=English_United States.utf8 
[2] LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

time zone: Asia/Shanghai
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] tmap_4.4-1             terra_1.9-50           spatstat.explore_3.8-2
 [4] nlme_3.1-168           spatstat.random_3.5-1  spatstat.geom_3.8-3   
 [7] spatstat.univar_3.2-0  spatstat.data_3.1-9    dplyr_1.2.1           
[10] sf_1.1-3              

loaded via a namespace (and not attached):
 [1] xfun_0.60               raster_3.6-32           htmlwidgets_1.6.4      
 [4] leafgl_0.2.4            spatstat.sparse_3.2-0   lattice_0.22-9         
 [7] yyjsonr_0.1.22          leaflet.providers_3.0.0 vctrs_0.7.3            
[10] tools_4.5.3             crosstalk_1.2.2         spatstat.utils_3.2-5   
[13] generics_0.1.4          parallel_4.5.3          goftest_1.2-3          
[16] tibble_3.3.1            proxy_0.4-29            pkgconfig_2.0.3        
[19] Matrix_1.7-4            KernSmooth_2.23-26      data.table_1.18.6.1    
[22] leaflet_2.2.3           lifecycle_1.0.5         compiler_4.5.3         
[25] deldir_2.0-4            codetools_0.2-20        leafsync_0.1.0         
[28] leaflegend_1.2.8        stars_0.7-3             htmltools_0.5.9        
[31] class_7.3-23            yaml_2.3.12             jquerylib_0.1.4        
[34] pillar_1.11.1           classInt_0.4-11         lwgeom_0.2-17          
[37] wk_0.9.5                abind_1.4-8             tidyselect_1.2.1       
[40] digest_0.6.39           polyclip_1.10-7         fastmap_1.2.0          
[43] grid_4.5.3              colorspace_2.1-3        cli_3.6.6              
[46] logger_0.4.3            magrittr_2.0.5          maptiles_0.12.0        
[49] base64enc_0.1-6         XML_3.99-0.24           cols4all_0.10          
[52] leafem_0.2.5            e1071_1.7-17            tensor_1.5.1           
[55] sp_2.2-3                rmarkdown_2.31          otel_0.2.0             
[58] png_0.1-9               evaluate_1.0.5          knitr_1.51             
[61] tmaptools_3.3           s2_1.1.12               rlang_1.3.0            
[64] Rcpp_1.1.2              glue_1.8.1              DBI_1.3.0              
[67] rstudioapi_0.19.0       jsonlite_2.0.0          R6_2.6.1               
[70] spacesXYZ_1.6-0         units_1.0-1            </code></pre>
</div>
</div>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const cellDetails = window.document.querySelectorAll(".cell details.code-fold");
        for (let i=0; i<cellDetails.length; i++) {
          const details = cellDetails[i];
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell div.sourceCode.cell-code");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb57" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Hands-on Exercise 2A"</span></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a><span class="an">subtitle:</span><span class="co"> "First-order spatial point patterns and childcare intensity"</span></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Zhenhua Liu"</span></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "2026-09-19"</span></span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a><span class="an">body-classes:</span><span class="co"> exercise-page</span></span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a><span class="an">toc:</span><span class="co"> true</span></span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a><span class="an">toc-location:</span><span class="co"> right</span></span>
<span id="cb57-9"><a href="#cb57-9" aria-hidden="true" tabindex="-1"></a><span class="an">code-fold:</span><span class="co"> false</span></span>
<span id="cb57-10"><a href="#cb57-10" aria-hidden="true" tabindex="-1"></a><span class="an">code-tools:</span><span class="co"> true</span></span>
<span id="cb57-11"><a href="#cb57-11" aria-hidden="true" tabindex="-1"></a><span class="an">execute:</span></span>
<span id="cb57-12"><a href="#cb57-12" aria-hidden="true" tabindex="-1"></a><span class="co">  freeze: true</span></span>
<span id="cb57-13"><a href="#cb57-13" aria-hidden="true" tabindex="-1"></a><span class="co">  echo: true</span></span>
<span id="cb57-14"><a href="#cb57-14" aria-hidden="true" tabindex="-1"></a><span class="co">  warning: true</span></span>
<span id="cb57-15"><a href="#cb57-15" aria-hidden="true" tabindex="-1"></a><span class="co">  message: false</span></span>
<span id="cb57-16"><a href="#cb57-16" aria-hidden="true" tabindex="-1"></a><span class="co">  error: false</span></span>
<span id="cb57-17"><a href="#cb57-17" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb57-18"><a href="#cb57-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-21"><a href="#cb57-21" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb57-22"><a href="#cb57-22" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: register-code</span></span>
<span id="cb57-23"><a href="#cb57-23" aria-hidden="true" tabindex="-1"></a><span class="co">#| include: false</span></span>
<span id="cb57-24"><a href="#cb57-24" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">read_chunk</span>(<span class="st">"handson2A/R/prepare.R"</span>)</span>
<span id="cb57-25"><a href="#cb57-25" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">read_chunk</span>(<span class="st">"handson2A/R/analysis.R"</span>)</span>
<span id="cb57-26"><a href="#cb57-26" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">fig.width =</span> <span class="dv">9</span>, <span class="at">fig.height =</span> <span class="dv">6</span>, <span class="at">dpi =</span> <span class="dv">150</span>)</span>
<span id="cb57-27"><a href="#cb57-27" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb57-28"><a href="#cb57-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-29"><a href="#cb57-29" aria-hidden="true" tabindex="-1"></a><span class="fu">## Overview</span></span>
<span id="cb57-30"><a href="#cb57-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-31"><a href="#cb57-31" aria-hidden="true" tabindex="-1"></a>Where are childcare services concentrated, and how much does the answer depend</span>
<span id="cb57-32"><a href="#cb57-32" aria-hidden="true" tabindex="-1"></a>on the observation window and smoothing method? I use Singapore's childcare</span>
<span id="cb57-33"><a href="#cb57-33" aria-hidden="true" tabindex="-1"></a>locations to examine intensity at national and planning-area scales. A nearest-neighbour</span>
<span id="cb57-34"><a href="#cb57-34" aria-hidden="true" tabindex="-1"></a>test provides a benchmark against spatial randomness; kernel density estimation</span>
<span id="cb57-35"><a href="#cb57-35" aria-hidden="true" tabindex="-1"></a>(KDE) then shows where concentrations occur. These are complementary summaries,</span>
<span id="cb57-36"><a href="#cb57-36" aria-hidden="true" tabindex="-1"></a>not a measure of whether local demand is adequately served.</span>
<span id="cb57-37"><a href="#cb57-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-38"><a href="#cb57-38" aria-hidden="true" tabindex="-1"></a>This exercise follows the workflow in <span class="co">[</span><span class="ot">course Chapter 4</span><span class="co">](https://r4gdsa.netlify.app/chap04.html)</span>.</span>
<span id="cb57-39"><a href="#cb57-39" aria-hidden="true" tabindex="-1"></a>The next page, <span class="co">[</span><span class="ot">Hands-on Exercise 2B</span><span class="co">](../handson2B/index.qmd)</span>, examines spatial</span>
<span id="cb57-40"><a href="#cb57-40" aria-hidden="true" tabindex="-1"></a>relationships over a range of distances.</span>
<span id="cb57-41"><a href="#cb57-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-42"><a href="#cb57-42" aria-hidden="true" tabindex="-1"></a><span class="fu">## 1. Setup and source data</span></span>
<span id="cb57-43"><a href="#cb57-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-44"><a href="#cb57-44" aria-hidden="true" tabindex="-1"></a><span class="in">`sf`</span> handles vector geometry, the <span class="in">`spatstat`</span> component packages provide planar</span>
<span id="cb57-45"><a href="#cb57-45" aria-hidden="true" tabindex="-1"></a>point-pattern analysis, and <span class="in">`terra`</span> carries the density raster into <span class="in">`tmap`</span>.</span>
<span id="cb57-46"><a href="#cb57-46" aria-hidden="true" tabindex="-1"></a><span class="in">`dplyr`</span> supplies the attribute filtering used to define the study region.</span>
<span id="cb57-47"><a href="#cb57-47" aria-hidden="true" tabindex="-1"></a>Packages are installed before rendering, so the page never changes its environment</span>
<span id="cb57-48"><a href="#cb57-48" aria-hidden="true" tabindex="-1"></a>halfway through an analysis.</span>
<span id="cb57-49"><a href="#cb57-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-52"><a href="#cb57-52" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb57-53"><a href="#cb57-53" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: packages</span></span>
<span id="cb57-54"><a href="#cb57-54" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb57-55"><a href="#cb57-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-56"><a href="#cb57-56" aria-hidden="true" tabindex="-1"></a>I use the official <span class="co">[</span><span class="ot">ECDA Child Care Services GeoJSON</span><span class="co">](https://data.gov.sg/datasets/d_5d668e3f544335f8028f546827b773b4/view)</span></span>
<span id="cb57-57"><a href="#cb57-57" aria-hidden="true" tabindex="-1"></a>and <span class="co">[</span><span class="ot">URA Master Plan 2019 Subzone Boundary (No Sea)</span><span class="co">](https://data.gov.sg/datasets/d_8594ae9ff96d0c708bc2af633048edfb/view)</span>.</span>
<span id="cb57-58"><a href="#cb57-58" aria-hidden="true" tabindex="-1"></a>The download routine is provided in <span class="co">[</span><span class="ot">`R/download-data.R`</span><span class="co">](R/download-data.R)</span>.</span>
<span id="cb57-59"><a href="#cb57-59" aria-hidden="true" tabindex="-1"></a><span class="in">`NAME`</span> and <span class="in">`ADDRESSSTREETNAME`</span> describe each service; <span class="in">`PLN_AREA_N`</span> and <span class="in">`SUBZONE_N`</span></span>
<span id="cb57-60"><a href="#cb57-60" aria-hidden="true" tabindex="-1"></a>identify the administrative units.</span>
<span id="cb57-61"><a href="#cb57-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-62"><a href="#cb57-62" aria-hidden="true" tabindex="-1"></a>::: {.callout-note title="The data date is not the download date"}</span>
<span id="cb57-63"><a href="#cb57-63" aria-hidden="true" tabindex="-1"></a>The ECDA portal describes this layer as **December 2021 data**, despite its</span>
<span id="cb57-64"><a href="#cb57-64" aria-hidden="true" tabindex="-1"></a>2026 portal update. These maps describe that historical service snapshot,</span>
<span id="cb57-65"><a href="#cb57-65" aria-hidden="true" tabindex="-1"></a>downloaded in September 2026. They should not be presented as a current inventory.</span>
<span id="cb57-66"><a href="#cb57-66" aria-hidden="true" tabindex="-1"></a>Both GeoJSON files already contain separate attributes, so no HTML-description</span>
<span id="cb57-67"><a href="#cb57-67" aria-hidden="true" tabindex="-1"></a>parsing is needed.</span>
<span id="cb57-68"><a href="#cb57-68" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb57-69"><a href="#cb57-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-72"><a href="#cb57-72" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb57-73"><a href="#cb57-73" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: import</span></span>
<span id="cb57-74"><a href="#cb57-74" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb57-75"><a href="#cb57-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-76"><a href="#cb57-76" aria-hidden="true" tabindex="-1"></a><span class="fu">## 2. Geometry, CRS and the observation window</span></span>
<span id="cb57-77"><a href="#cb57-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-78"><a href="#cb57-78" aria-hidden="true" tabindex="-1"></a>I transform both layers to **SVY21 / Singapore TM (EPSG:3414)** so coordinates</span>
<span id="cb57-79"><a href="#cb57-79" aria-hidden="true" tabindex="-1"></a>and distances are in metres. <span class="in">`st_transform()`</span> changes coordinate values;</span>
<span id="cb57-80"><a href="#cb57-80" aria-hidden="true" tabindex="-1"></a>assigning a CRS label alone would not perform that conversion. I validate the</span>
<span id="cb57-81"><a href="#cb57-81" aria-hidden="true" tabindex="-1"></a>polygons and use the course's exclusions for the Southern Group, Western Islands</span>
<span id="cb57-82"><a href="#cb57-82" aria-hidden="true" tabindex="-1"></a>and North-Eastern Islands. This is a specified administrative study window,</span>
<span id="cb57-83"><a href="#cb57-83" aria-hidden="true" tabindex="-1"></a>not a claim that every remaining square metre is habitable land.</span>
<span id="cb57-84"><a href="#cb57-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-85"><a href="#cb57-85" aria-hidden="true" tabindex="-1"></a>Dissolving subzone boundaries with <span class="in">`st_union()`</span> produces one region for</span>
<span id="cb57-86"><a href="#cb57-86" aria-hidden="true" tabindex="-1"></a><span class="in">`as.owin()`</span>. An <span class="in">`owin`</span> stores the observation boundary; a <span class="in">`ppp`</span> stores events</span>
<span id="cb57-87"><a href="#cb57-87" aria-hidden="true" tabindex="-1"></a>inside that boundary. Using the points' bounding rectangle instead would include</span>
<span id="cb57-88"><a href="#cb57-88" aria-hidden="true" tabindex="-1"></a>unobserved sea and change both expected density and simulated patterns.</span>
<span id="cb57-89"><a href="#cb57-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-92"><a href="#cb57-92" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb57-93"><a href="#cb57-93" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: prepare-window</span></span>
<span id="cb57-94"><a href="#cb57-94" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb57-95"><a href="#cb57-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-96"><a href="#cb57-96" aria-hidden="true" tabindex="-1"></a>The audit retains **`r npoints(childcare_ppp)` service records** at</span>
<span id="cb57-97"><a href="#cb57-97" aria-hidden="true" tabindex="-1"></a>**`r npoints(childcare_unique)` distinct coordinates**. There are</span>
<span id="cb57-98"><a href="#cb57-98" aria-hidden="true" tabindex="-1"></a><span class="in">`r sum(duplicate_location)`</span> records beyond the first at repeated coordinates and</span>
<span id="cb57-99"><a href="#cb57-99" aria-hidden="true" tabindex="-1"></a><span class="in">`r sum(!inside)`</span> points outside the window. Repeated coordinates are not enough</span>
<span id="cb57-100"><a href="#cb57-100" aria-hidden="true" tabindex="-1"></a>evidence to delete a service: several operators or records can share a building.</span>
<span id="cb57-101"><a href="#cb57-101" aria-hidden="true" tabindex="-1"></a>I retain records for provision intensity and also test distinct locations as a</span>
<span id="cb57-102"><a href="#cb57-102" aria-hidden="true" tabindex="-1"></a>sensitivity check. No random jitter is added to manufacture separation.</span>
<span id="cb57-103"><a href="#cb57-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-106"><a href="#cb57-106" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb57-107"><a href="#cb57-107" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: national-map</span></span>
<span id="cb57-108"><a href="#cb57-108" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Historical childcare service records within the selected MP2019 study window."</span></span>
<span id="cb57-109"><a href="#cb57-109" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-alt: "Map of Singapore subzones overlaid with childcare service points."</span></span>
<span id="cb57-110"><a href="#cb57-110" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb57-111"><a href="#cb57-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-112"><a href="#cb57-112" aria-hidden="true" tabindex="-1"></a>The overlay checks spatial alignment and reveals uneven concentrations. Large</span>
<span id="cb57-113"><a href="#cb57-113" aria-hidden="true" tabindex="-1"></a>low-density areas include land that is not primarily residential, so national</span>
<span id="cb57-114"><a href="#cb57-114" aria-hidden="true" tabindex="-1"></a>homogeneous randomness is a deliberately simple reference model.</span>
<span id="cb57-115"><a href="#cb57-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-116"><a href="#cb57-116" aria-hidden="true" tabindex="-1"></a><span class="fu">## 3. Nearest-neighbour analysis</span></span>
<span id="cb57-117"><a href="#cb57-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-118"><a href="#cb57-118" aria-hidden="true" tabindex="-1"></a>The Clark–Evans ratio compares observed mean nearest-neighbour distance with</span>
<span id="cb57-119"><a href="#cb57-119" aria-hidden="true" tabindex="-1"></a>the homogeneous Poisson expectation. Values below one indicate shorter</span>
<span id="cb57-120"><a href="#cb57-120" aria-hidden="true" tabindex="-1"></a>separations. I specify a one-sided clustering alternative for this national</span>
<span id="cb57-121"><a href="#cb57-121" aria-hidden="true" tabindex="-1"></a>question, with a 5% significance threshold.</span>
<span id="cb57-122"><a href="#cb57-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-123"><a href="#cb57-123" aria-hidden="true" tabindex="-1"></a>I show both the asymptotic approximation and 999 Monte Carlo simulations.</span>
<span id="cb57-124"><a href="#cb57-124" aria-hidden="true" tabindex="-1"></a>The latter places the same number of points uniformly inside the actual</span>
<span id="cb57-125"><a href="#cb57-125" aria-hidden="true" tabindex="-1"></a>window and applies the same uncorrected statistic to observed and simulated</span>
<span id="cb57-126"><a href="#cb57-126" aria-hidden="true" tabindex="-1"></a>patterns. This accounts for window shape in the reference distribution, although</span>
<span id="cb57-127"><a href="#cb57-127" aria-hidden="true" tabindex="-1"></a>the uncorrected ratio itself still has edge bias. Nearest-neighbour statistics</span>
<span id="cb57-128"><a href="#cb57-128" aria-hidden="true" tabindex="-1"></a>involve interpoint distances; their inclusion here follows the course's sequence,</span>
<span id="cb57-129"><a href="#cb57-129" aria-hidden="true" tabindex="-1"></a>while KDE is the main first-order intensity method.</span>
<span id="cb57-130"><a href="#cb57-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-133"><a href="#cb57-133" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb57-134"><a href="#cb57-134" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: nearest-neighbour</span></span>
<span id="cb57-135"><a href="#cb57-135" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb57-136"><a href="#cb57-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-137"><a href="#cb57-137" aria-hidden="true" tabindex="-1"></a>The record-level ratio is **`r round(unname(ce_mc$statistic), 3)`**, with simulated</span>
<span id="cb57-138"><a href="#cb57-138" aria-hidden="true" tabindex="-1"></a>p = **`r format(ce_mc$p.value, scientific = FALSE)`**. After collapsing co-located</span>
<span id="cb57-139"><a href="#cb57-139" aria-hidden="true" tabindex="-1"></a>records, R becomes **`r round(unname(ce_unique$statistic), 3)`** and p becomes</span>
<span id="cb57-140"><a href="#cb57-140" aria-hidden="true" tabindex="-1"></a>**`r format(ce_unique$p.value, scientific = FALSE)`**. The comparison separates</span>
<span id="cb57-141"><a href="#cb57-141" aria-hidden="true" tabindex="-1"></a>the contribution of shared coordinates from the broader geographic pattern.</span>
<span id="cb57-142"><a href="#cb57-142" aria-hidden="true" tabindex="-1"></a>With 999 simulations, the smallest attainable one-sided Monte Carlo p-value is</span>
<span id="cb57-143"><a href="#cb57-143" aria-hidden="true" tabindex="-1"></a>0.001; it is never zero.</span>
<span id="cb57-144"><a href="#cb57-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-145"><a href="#cb57-145" aria-hidden="true" tabindex="-1"></a>For planning, a departure from uniform randomness means that service locations</span>
<span id="cb57-146"><a href="#cb57-146" aria-hidden="true" tabindex="-1"></a>are spatially uneven. It does not establish oversupply, undersupply, or a causal</span>
<span id="cb57-147"><a href="#cb57-147" aria-hidden="true" tabindex="-1"></a>attraction between providers. Residential distribution is an obvious omitted factor.</span>
<span id="cb57-148"><a href="#cb57-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-149"><a href="#cb57-149" aria-hidden="true" tabindex="-1"></a><span class="fu">## 4. Bandwidth selection and density units</span></span>
<span id="cb57-150"><a href="#cb57-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-151"><a href="#cb57-151" aria-hidden="true" tabindex="-1"></a>Bandwidth controls the scale at which a concentration is visible. I compute four</span>
<span id="cb57-152"><a href="#cb57-152" aria-hidden="true" tabindex="-1"></a>selectors rather than importing the numerical bandwidth printed in the lesson.</span>
<span id="cb57-153"><a href="#cb57-153" aria-hidden="true" tabindex="-1"></a>Scott's rule returns separate x and y smoothing scales, so its two values should</span>
<span id="cb57-154"><a href="#cb57-154" aria-hidden="true" tabindex="-1"></a>not be mistaken for two competing scalar solutions.</span>
<span id="cb57-155"><a href="#cb57-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-158"><a href="#cb57-158" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb57-159"><a href="#cb57-159" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: bandwidths</span></span>
<span id="cb57-160"><a href="#cb57-160" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb57-161"><a href="#cb57-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-162"><a href="#cb57-162" aria-hidden="true" tabindex="-1"></a>The Diggle result is **`r round(as.numeric(bw_diggle) * 1000)` m**; likelihood</span>
<span id="cb57-163"><a href="#cb57-163" aria-hidden="true" tabindex="-1"></a>cross-validation gives **`r round(as.numeric(bw_ppl) * 1000)` m**. The table</span>
<span id="cb57-164"><a href="#cb57-164" aria-hidden="true" tabindex="-1"></a>documents how far alternative selectors move the scale of the question.</span>
<span id="cb57-165"><a href="#cb57-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-168"><a href="#cb57-168" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb57-169"><a href="#cb57-169" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: kde-units</span></span>
<span id="cb57-170"><a href="#cb57-170" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb57-171"><a href="#cb57-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-172"><a href="#cb57-172" aria-hidden="true" tabindex="-1"></a>The two computations describe the same surface. Rescaling coordinates from</span>
<span id="cb57-173"><a href="#cb57-173" aria-hidden="true" tabindex="-1"></a>metres to kilometres multiplies density values by one million. I verify that</span>
<span id="cb57-174"><a href="#cb57-174" aria-hidden="true" tabindex="-1"></a>identity numerically, using matched 100 m cells. The raster integral is a useful</span>
<span id="cb57-175"><a href="#cb57-175" aria-hidden="true" tabindex="-1"></a>diagnostic against the input count; pixel discretisation and boundary correction</span>
<span id="cb57-176"><a href="#cb57-176" aria-hidden="true" tabindex="-1"></a>mean it need not reproduce the count exactly. Small negative values close to</span>
<span id="cb57-177"><a href="#cb57-177" aria-hidden="true" tabindex="-1"></a>machine precision are numerical convolution artefacts, not negative services.</span>
<span id="cb57-178"><a href="#cb57-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-181"><a href="#cb57-181" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb57-182"><a href="#cb57-182" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: bandwidth-comparison</span></span>
<span id="cb57-183"><a href="#cb57-183" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Diggle and likelihood bandwidths, with a shared intensity scale in records per km². Map coordinates are kilometres."</span></span>
<span id="cb57-184"><a href="#cb57-184" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-alt: "Two comparable childcare kernel density maps using different bandwidth selectors."</span></span>
<span id="cb57-185"><a href="#cb57-185" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb57-186"><a href="#cb57-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-187"><a href="#cb57-187" aria-hidden="true" tabindex="-1"></a>A narrower bandwidth preserves more local peaks; a wider bandwidth merges nearby</span>
<span id="cb57-188"><a href="#cb57-188" aria-hidden="true" tabindex="-1"></a>peaks into broader concentrations. I use the same colour limits so differences</span>
<span id="cb57-189"><a href="#cb57-189" aria-hidden="true" tabindex="-1"></a>are not created by separately stretched legends.</span>
<span id="cb57-190"><a href="#cb57-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-191"><a href="#cb57-191" aria-hidden="true" tabindex="-1"></a><span class="fu">## 5. Kernel shape, fixed and adaptive smoothing</span></span>
<span id="cb57-192"><a href="#cb57-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-193"><a href="#cb57-193" aria-hidden="true" tabindex="-1"></a>First I hold bandwidth constant and change the kernel. This isolates kernel</span>
<span id="cb57-194"><a href="#cb57-194" aria-hidden="true" tabindex="-1"></a>shape from bandwidth selection, with the same spatial resolution and intensity</span>
<span id="cb57-195"><a href="#cb57-195" aria-hidden="true" tabindex="-1"></a>scale throughout.</span>
<span id="cb57-196"><a href="#cb57-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-199"><a href="#cb57-199" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb57-200"><a href="#cb57-200" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: kernel-comparison</span></span>
<span id="cb57-201"><a href="#cb57-201" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 8</span></span>
<span id="cb57-202"><a href="#cb57-202" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Gaussian, Epanechnikov, quartic and disc kernels at the same Diggle bandwidth; records per km²."</span></span>
<span id="cb57-203"><a href="#cb57-203" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-alt: "Four childcare density surfaces comparing kernel shapes."</span></span>
<span id="cb57-204"><a href="#cb57-204" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb57-205"><a href="#cb57-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-206"><a href="#cb57-206" aria-hidden="true" tabindex="-1"></a>The compact-support kernels assign no contribution beyond their support, whereas</span>
<span id="cb57-207"><a href="#cb57-207" aria-hidden="true" tabindex="-1"></a>a Gaussian kernel decays gradually. Broad concentrations should be read across</span>
<span id="cb57-208"><a href="#cb57-208" aria-hidden="true" tabindex="-1"></a>the panels; an isolated bright pixel is not evidence of a statistically significant hotspot.</span>
<span id="cb57-209"><a href="#cb57-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-210"><a href="#cb57-210" aria-hidden="true" tabindex="-1"></a>Next I compare the lesson's **600 m fixed bandwidth** with an adaptive kernel</span>
<span id="cb57-211"><a href="#cb57-211" aria-hidden="true" tabindex="-1"></a>estimate. The adaptive method allows local smoothing scales to vary with the</span>
<span id="cb57-212"><a href="#cb57-212" aria-hidden="true" tabindex="-1"></a>pilot intensity, which can retain detail where records are dense.</span>
<span id="cb57-213"><a href="#cb57-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-216"><a href="#cb57-216" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb57-217"><a href="#cb57-217" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: adaptive-kde</span></span>
<span id="cb57-218"><a href="#cb57-218" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Fixed 600 m and adaptive kernel estimates on a shared records-per-km² scale."</span></span>
<span id="cb57-219"><a href="#cb57-219" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-alt: "Side-by-side fixed and adaptive childcare density estimates."</span></span>
<span id="cb57-220"><a href="#cb57-220" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb57-221"><a href="#cb57-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-222"><a href="#cb57-222" aria-hidden="true" tabindex="-1"></a>Adaptive smoothing changes the estimator, so differences cannot be attributed</span>
<span id="cb57-223"><a href="#cb57-223" aria-hidden="true" tabindex="-1"></a>only to a single bandwidth value. Neither surface adjusts for population or</span>
<span id="cb57-224"><a href="#cb57-224" aria-hidden="true" tabindex="-1"></a>centre capacity. A high value describes many records per land area.</span>
<span id="cb57-225"><a href="#cb57-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-226"><a href="#cb57-226" aria-hidden="true" tabindex="-1"></a><span class="fu">## 6. A geographically correct KDE map</span></span>
<span id="cb57-227"><a href="#cb57-227" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-228"><a href="#cb57-228" aria-hidden="true" tabindex="-1"></a>::: {.callout-important title="Raster values and map coordinates use different units"}</span>
<span id="cb57-229"><a href="#cb57-229" aria-hidden="true" tabindex="-1"></a>EPSG:3414 requires metre coordinates. Assigning it to an image whose coordinates</span>
<span id="cb57-230"><a href="#cb57-230" aria-hidden="true" tabindex="-1"></a>were divided by 1,000 would put the raster in the wrong place. I convert the</span>
<span id="cb57-231"><a href="#cb57-231" aria-hidden="true" tabindex="-1"></a>**metre-coordinate image** to `SpatRaster`, multiply only its **density values**</span>
<span id="cb57-232"><a href="#cb57-232" aria-hidden="true" tabindex="-1"></a>by one million, and then attach EPSG:3414. The subzone overlay and scale bar are</span>
<span id="cb57-233"><a href="#cb57-233" aria-hidden="true" tabindex="-1"></a>therefore geographically consistent.</span>
<span id="cb57-234"><a href="#cb57-234" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb57-235"><a href="#cb57-235" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-238"><a href="#cb57-238" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb57-239"><a href="#cb57-239" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: cartographic-kde</span></span>
<span id="cb57-240"><a href="#cb57-240" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 7</span></span>
<span id="cb57-241"><a href="#cb57-241" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Childcare service intensity, with correctly aligned MP2019 boundaries and a continuous sequential legend."</span></span>
<span id="cb57-242"><a href="#cb57-242" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-alt: "Cartographic childcare kernel density map with boundaries, compass and scale bar."</span></span>
<span id="cb57-243"><a href="#cb57-243" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb57-244"><a href="#cb57-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-245"><a href="#cb57-245" aria-hidden="true" tabindex="-1"></a>I retain a continuous sequential palette because KDE is a continuous estimate.</span>
<span id="cb57-246"><a href="#cb57-246" aria-hidden="true" tabindex="-1"></a>Discretising it into quantiles would change the visual message to relative</span>
<span id="cb57-247"><a href="#cb57-247" aria-hidden="true" tabindex="-1"></a>ranks and hide the numeric gap between intensities.</span>
<span id="cb57-248"><a href="#cb57-248" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-249"><a href="#cb57-249" aria-hidden="true" tabindex="-1"></a><span class="fu">## 7. Planning-area comparison</span></span>
<span id="cb57-250"><a href="#cb57-250" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-251"><a href="#cb57-251" aria-hidden="true" tabindex="-1"></a>The four local windows are Punggol, Tampines, Choa Chu Kang and Jurong West.</span>
<span id="cb57-252"><a href="#cb57-252" aria-hidden="true" tabindex="-1"></a>Although the source boundary contains subzones, the comparisons below are at</span>
<span id="cb57-253"><a href="#cb57-253" aria-hidden="true" tabindex="-1"></a>**planning-area** level after dissolving the relevant subzones.</span>
<span id="cb57-254"><a href="#cb57-254" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-257"><a href="#cb57-257" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb57-258"><a href="#cb57-258" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: planning-areas</span></span>
<span id="cb57-259"><a href="#cb57-259" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb57-260"><a href="#cb57-260" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-263"><a href="#cb57-263" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb57-264"><a href="#cb57-264" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: area-pattern-map</span></span>
<span id="cb57-265"><a href="#cb57-265" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 8</span></span>
<span id="cb57-266"><a href="#cb57-266" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Service records in the four planning-area windows; coordinates are kilometres."</span></span>
<span id="cb57-267"><a href="#cb57-267" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-alt: "Childcare point patterns in Punggol, Tampines, Choa Chu Kang and Jurong West."</span></span>
<span id="cb57-268"><a href="#cb57-268" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb57-269"><a href="#cb57-269" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-270"><a href="#cb57-270" aria-hidden="true" tabindex="-1"></a>Choa Chu Kang has <span class="in">`r round(area_summary$records_per_km2[area_summary$planning_area == 'CHOA CHU KANG'], 1)`</span></span>
<span id="cb57-271"><a href="#cb57-271" aria-hidden="true" tabindex="-1"></a>records/km² compared with <span class="in">`r round(area_summary$records_per_km2[area_summary$planning_area == 'TAMPINES'], 1)`</span></span>
<span id="cb57-272"><a href="#cb57-272" aria-hidden="true" tabindex="-1"></a>in Tampines. This is an area-normalised comparison, not a ranking of service</span>
<span id="cb57-273"><a href="#cb57-273" aria-hidden="true" tabindex="-1"></a>adequacy. The actual distribution inside each polygon is still important.</span>
<span id="cb57-274"><a href="#cb57-274" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-277"><a href="#cb57-277" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb57-278"><a href="#cb57-278" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: area-tests</span></span>
<span id="cb57-279"><a href="#cb57-279" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb57-280"><a href="#cb57-280" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-281"><a href="#cb57-281" aria-hidden="true" tabindex="-1"></a>Here the alternative is two-sided: either unusually short or unusually long</span>
<span id="cb57-282"><a href="#cb57-282" aria-hidden="true" tabindex="-1"></a>nearest-neighbour distances would be relevant. I explicitly select</span>
<span id="cb57-283"><a href="#cb57-283" aria-hidden="true" tabindex="-1"></a><span class="in">`method = "MonteCarlo"`</span>; supplying <span class="in">`nsim`</span> alone does not change the default</span>
<span id="cb57-284"><a href="#cb57-284" aria-hidden="true" tabindex="-1"></a>asymptotic method. These two comparisons are exploratory.</span>
<span id="cb57-285"><a href="#cb57-285" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-288"><a href="#cb57-288" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb57-289"><a href="#cb57-289" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: area-kde</span></span>
<span id="cb57-290"><a href="#cb57-290" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 8</span></span>
<span id="cb57-291"><a href="#cb57-291" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Planning-area KDE with area-specific Diggle bandwidths and common intensity limits; records per km²."</span></span>
<span id="cb57-292"><a href="#cb57-292" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-alt: "Four planning-area childcare kernel density maps."</span></span>
<span id="cb57-293"><a href="#cb57-293" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb57-294"><a href="#cb57-294" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-295"><a href="#cb57-295" aria-hidden="true" tabindex="-1"></a>Each bandwidth is fitted within its own window, so fine detail is not equally</span>
<span id="cb57-296"><a href="#cb57-296" aria-hidden="true" tabindex="-1"></a>resolved in all panels. The common legend supports intensity comparison; a</span>
<span id="cb57-297"><a href="#cb57-297" aria-hidden="true" tabindex="-1"></a>common fixed bandwidth would be preferable for a strictly matched smoothing</span>
<span id="cb57-298"><a href="#cb57-298" aria-hidden="true" tabindex="-1"></a>comparison. Local boundary correction cannot represent cross-boundary access</span>
<span id="cb57-299"><a href="#cb57-299" aria-hidden="true" tabindex="-1"></a>to a nearby centre in another planning area.</span>
<span id="cb57-300"><a href="#cb57-300" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-301"><a href="#cb57-301" aria-hidden="true" tabindex="-1"></a><span class="fu">## 8. Interactive lookup</span></span>
<span id="cb57-302"><a href="#cb57-302" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-303"><a href="#cb57-303" aria-hidden="true" tabindex="-1"></a>The map supports centre-name and address lookup. External background tiles</span>
<span id="cb57-304"><a href="#cb57-304" aria-hidden="true" tabindex="-1"></a>require an internet connection; the analytical figures above are locally</span>
<span id="cb57-305"><a href="#cb57-305" aria-hidden="true" tabindex="-1"></a>rendered assets and remain available independently of the tile provider.</span>
<span id="cb57-306"><a href="#cb57-306" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-309"><a href="#cb57-309" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb57-310"><a href="#cb57-310" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: interactive-points</span></span>
<span id="cb57-311"><a href="#cb57-311" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb57-312"><a href="#cb57-312" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-313"><a href="#cb57-313" aria-hidden="true" tabindex="-1"></a><span class="fu">## 9. What I learned</span></span>
<span id="cb57-314"><a href="#cb57-314" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-315"><a href="#cb57-315" aria-hidden="true" tabindex="-1"></a>The observation window is part of the statistical model, not just a cartographic</span>
<span id="cb57-316"><a href="#cb57-316" aria-hidden="true" tabindex="-1"></a>frame. Counting service records and counting distinct locations are different</span>
<span id="cb57-317"><a href="#cb57-317" aria-hidden="true" tabindex="-1"></a>questions, especially when several records share a coordinate. I also found that</span>
<span id="cb57-318"><a href="#cb57-318" aria-hidden="true" tabindex="-1"></a>density units and coordinate units must be checked separately: a convincing</span>
<span id="cb57-319"><a href="#cb57-319" aria-hidden="true" tabindex="-1"></a>colour surface can still be geographically wrong if its extent is mislabelled.</span>
<span id="cb57-320"><a href="#cb57-320" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-321"><a href="#cb57-321" aria-hidden="true" tabindex="-1"></a>The most useful next extension would relate service capacity to the residential</span>
<span id="cb57-322"><a href="#cb57-322" aria-hidden="true" tabindex="-1"></a>population of young children and realistic travel distances. This exercise alone</span>
<span id="cb57-323"><a href="#cb57-323" aria-hidden="true" tabindex="-1"></a>cannot identify unmet demand or explain why providers locate together.</span>
<span id="cb57-324"><a href="#cb57-324" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-325"><a href="#cb57-325" aria-hidden="true" tabindex="-1"></a><span class="fu">## Reproducibility and references</span></span>
<span id="cb57-326"><a href="#cb57-326" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-327"><a href="#cb57-327" aria-hidden="true" tabindex="-1"></a>All executed code is supplied in <span class="co">[</span><span class="ot">`R/prepare.R`</span><span class="co">](R/prepare.R)</span> and</span>
<span id="cb57-328"><a href="#cb57-328" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">`R/analysis.R`</span><span class="co">](R/analysis.R)</span>. The page reads those labelled sections directly,</span>
<span id="cb57-329"><a href="#cb57-329" aria-hidden="true" tabindex="-1"></a>so the displayed code and executed code have one source. Run the download script</span>
<span id="cb57-330"><a href="#cb57-330" aria-hidden="true" tabindex="-1"></a>once, then <span class="in">`quarto render . --execute`</span> from the repository root to rebuild the</span>
<span id="cb57-331"><a href="#cb57-331" aria-hidden="true" tabindex="-1"></a>whole site. The shared preparation also allows 2B to render independently.</span>
<span id="cb57-332"><a href="#cb57-332" aria-hidden="true" tabindex="-1"></a>Raw and derived data stay in ignored folders. <span class="co">[</span><span class="ot">`data/README.md`</span><span class="co">](data/README.md)</span></span>
<span id="cb57-333"><a href="#cb57-333" aria-hidden="true" tabindex="-1"></a>records the sources, checksums and assumptions.</span>
<span id="cb57-334"><a href="#cb57-334" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-335"><a href="#cb57-335" aria-hidden="true" tabindex="-1"></a>Method references: <span class="co">[</span><span class="ot">course Chapter 4</span><span class="co">](https://r4gdsa.netlify.app/chap04.html)</span>,</span>
<span id="cb57-336"><a href="#cb57-336" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">spatstat documentation</span><span class="co">](https://spatstat.org/)</span>,</span>
<span id="cb57-337"><a href="#cb57-337" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">adaptive density reference</span><span class="co">](https://search.r-project.org/CRAN/refmans/spatstat.explore/html/adaptive.density.html)</span>,</span>
<span id="cb57-338"><a href="#cb57-338" aria-hidden="true" tabindex="-1"></a>and <span class="co">[</span><span class="ot">sf coordinate transformations</span><span class="co">](https://r-spatial.github.io/sf/reference/st_transform.html)</span>.</span>
<span id="cb57-339"><a href="#cb57-339" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-342"><a href="#cb57-342" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb57-343"><a href="#cb57-343" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: session-info</span></span>
<span id="cb57-344"><a href="#cb57-344" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb57-345"><a href="#cb57-345" aria-hidden="true" tabindex="-1"></a><span class="fu">sessionInfo</span>()</span>
<span id="cb57-346"><a href="#cb57-346" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>