{
  "hash": "bd43cf2a79e658eb41cf8e78e737101d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Hands-on Exercise 5A\"\nsubtitle: \"Global spatial autocorrelation of Hunan GDP per capita\"\nauthor: \"Zhenhua Liu\"\ndate: \"2026-10-03\"\nbody-classes: exercise-page\ntoc: true\ntoc-location: right\ncode-tools: true\nexecute:\n  freeze: auto\n  error: false\n---\n\n\n\n## 1. Purpose and workflow\n\nDoes GDP per capita show a province-wide spatial pattern among Hunan's counties in 2012? I follow [Chapter 9: Global Measures of Spatial Autocorrelation](https://r4gdsa.netlify.app/chap09.html) to compare Moran's I and Geary's C, check their significance through permutation, and examine how association changes across neighbour orders.\n\nThis page builds on [Hands-on Exercise 4](../handson4/index.qmd), which introduced spatial weights. [Exercise 5B](../handson4B/index.qmd) then locates clusters and spatial outliers. A province-wide statistic establishes evidence of association; local methods are needed to identify where that association occurs.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(sf)\nlibrary(spdep)\nlibrary(tmap)\nlibrary(dplyr)\nlibrary(readr)\nlibrary(ggplot2)\nlibrary(knitr)\ntmap_mode(\"plot\")\noptions(scipen = 5)\n```\n:::\n\n\n## 2. Import, join and validate the inputs\n\nThe county shapefile and `Hunan_2012.csv` are stored in `handson4/data`. They match the shapefile and 2012 CSV supplied at `C:/zhenhuaArhci/my_Project/data` (SHA-256 checked on 3 October 2026). I reuse these tracked inputs so the exercise also runs from a GitHub checkout. The data provenance is documented in [the existing data notes](../handson4/data/README.md).\n\nJoining explicitly on `County` prevents unintended matching on other fields. The checks require unique county keys, complete matches, valid geometry and finite GDPPC. The original geographic CRS is retained for this chapter's contiguity analysis; drawing the neighbour graph uses a projected copy.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan <- st_read(\"handson4/data/geospatial\", layer = \"Hunan\", quiet = TRUE)\nhunan2012 <- read_csv(\"handson4/data/aspatial/Hunan_2012.csv\",\n                      show_col_types = FALSE)\nstopifnot(!anyDuplicated(hunan$County), !anyDuplicated(hunan2012$County),\n          setequal(hunan$County, hunan2012$County))\nhunan <- left_join(hunan, hunan2012, by = \"County\") |>\n  select(NAME_2, ID_3, NAME_3, County, GDPPC)\nstopifnot(nrow(hunan) == 88L, !anyNA(hunan$GDPPC),\n          all(is.finite(hunan$GDPPC)), all(st_is_valid(hunan)),\n          isTRUE(st_is_longlat(hunan)))\nkable(head(st_drop_geometry(hunan)), caption = \"Joined Hunan county data, 2012\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Joined Hunan county data, 2012\n\n|NAME_2  |  ID_3|NAME_3  |County  | GDPPC|\n|:-------|-----:|:-------|:-------|-----:|\n|Changde | 21098|Anxiang |Anxiang | 23667|\n|Changde | 21100|Hanshou |Hanshou | 20981|\n|Changde | 21101|Jinshi  |Jinshi  | 34592|\n|Changde | 21102|Li      |Li      | 24473|\n|Changde | 21103|Linli   |Linli   | 25554|\n|Changde | 21104|Shimen  |Shimen  | 27137|\n\n\n:::\n\n```{.r .cell-code}\nst_crs(hunan)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: WGS 84 \n  wkt:\nGEOGCRS[\"WGS 84\",\n    DATUM[\"World Geodetic System 1984\",\n        ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n            LENGTHUNIT[\"metre\",1]]],\n    PRIMEM[\"Greenwich\",0,\n        ANGLEUNIT[\"degree\",0.0174532925199433]],\n    CS[ellipsoidal,2],\n        AXIS[\"latitude\",north,\n            ORDER[1],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        AXIS[\"longitude\",east,\n            ORDER[2],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n    ID[\"EPSG\",4326]]\n```\n\n\n:::\n\n```{.r .cell-code}\ngdppc_summary <- tibble(Counties = nrow(hunan), Mean = mean(hunan$GDPPC),\n  Median = median(hunan$GDPPC), SD = sd(hunan$GDPPC),\n  Minimum = min(hunan$GDPPC), Maximum = max(hunan$GDPPC))\nkable(gdppc_summary, digits = 2)\n```\n\n::: {.cell-output-display}\n\n\n| Counties|     Mean| Median|       SD| Minimum| Maximum|\n|--------:|--------:|------:|--------:|-------:|-------:|\n|       88| 24404.81|  20433| 14994.26|    8497|   88656|\n\n\n:::\n:::\n\n\nGDPPC varies from 8497 to 88656, with a county mean of 24404.81. This mean treats every county equally and is not a population-weighted provincial estimate.\n\n## 3. Visualise the development indicator\n\n\n::: {.cell}\n\n```{.r .cell-code}\nequal_map <- tm_shape(hunan) +\n  tm_polygons(fill = \"GDPPC\",\n    fill.scale = tm_scale_intervals(style = \"equal\", n = 5,\n                                    values = \"brewer.blues\"),\n    fill.legend = tm_legend(title = \"GDPPC\", position = tm_pos_out())) +\n  tm_title(\"Equal intervals\")\nquantile_map <- tm_shape(hunan) +\n  tm_polygons(fill = \"GDPPC\",\n    fill.scale = tm_scale_intervals(style = \"quantile\", n = 5,\n                                    values = \"brewer.blues\"),\n    fill.legend = tm_legend(title = \"GDPPC\", position = tm_pos_out())) +\n  tm_title(\"Quantiles\")\ntmap_arrange(equal_map, quantile_map, ncol = 2)\n```\n\n::: {.cell-output-display}\n![Two classifications of the same 2012 GDPPC values.](index_files/figure-html/a-baseline-1.png){fig-alt='Hunan county GDPPC maps using equal intervals and quantiles.' width=1600}\n:::\n:::\n\n\nEqual intervals retain a common numerical width, while quantiles place approximately the same number of counties in each class. Their different appearance is a classification effect. Neither map alone tests spatial association, and a quantile class should not be read as an equally spaced income band.\n\n## 4. Define Queen neighbours and row-standardised weights\n\nQueen contiguity links counties that share an edge or vertex. `style = \"W\"` assigns each neighbour the reciprocal of the county's neighbour count, so each nonempty row sums to one. Self-neighbours are excluded. County order must remain aligned with the weights throughout the analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_q <- poly2nb(hunan, queen = TRUE, row.names = hunan$County)\nsummary(wm_q)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 448 \nPercentage nonzero weights: 5.785124 \nAverage number of links: 5.090909 \nLink number distribution:\n\n 1  2  3  4  5  6  7  8  9 11 \n 2  2 12 16 24 14 11  4  2  1 \n2 least connected regions:\nXinhuang Linxiang with 1 link\n1 most connected region:\nTaoyuan with 11 links\n```\n\n\n:::\n\n```{.r .cell-code}\nrswm_q <- nb2listw(wm_q, style = \"W\", zero.policy = TRUE)\nrswm_q\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCharacteristics of weights list object:\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 448 \nPercentage nonzero weights: 5.785124 \nAverage number of links: 5.090909 \n\nWeights style: W \nWeights constants summary:\n   n   nn S0       S1       S2\nW 88 7744 88 37.86334 365.9147\n```\n\n\n:::\n\n```{.r .cell-code}\nstopifnot(all(card(wm_q) > 0L),\n          all(abs(vapply(rswm_q$weights, sum, numeric(1)) - 1) < 1e-10),\n          identical(attr(wm_q, \"region.id\"), hunan$County))\ncoords <- st_coordinates(st_centroid(st_transform(hunan, 32650)))\nplot(st_geometry(st_transform(hunan, 32650)), col = \"#f0f4f8\",\n     border = \"#bac7d1\", main = \"Queen contiguity between Hunan counties\")\nplot(wm_q, coords, add = TRUE, col = \"#456b89\", pch = 20, cex = 0.4)\n```\n\n::: {.cell-output-display}\n![Queen neighbour links drawn between projected county centroids.](index_files/figure-html/a-weights-1.png){width=1600}\n:::\n:::\n\n\nThere are 88 counties and 448 directed links, with an average of 5.09 neighbours. The neighbour count ranges from 1 to 11; no county is isolated. Edge counties have fewer neighbours, so their spatial averages describe a smaller surrounding set.\n\n## 5. Moran's I: global similarity\n\n### Analytical and permutation tests\n\nThe null is that GDPPC labels are spatially exchangeable over the fixed county neighbourhood graph. The one-sided alternative seeks positive association. A positive I indicates that similar GDPPC values tend to be neighbours; it does not establish the cause of this arrangement.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmoran_result <- moran.test(hunan$GDPPC, listw = rswm_q,\n  alternative = \"greater\", zero.policy = TRUE, na.action = na.fail)\nmoran_result\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  hunan$GDPPC  \nweights: rswm_q    \n\nMoran I statistic standard deviate = 4.7351, p-value = 0.000001095\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.300749970      -0.011494253       0.004348351 \n```\n\n\n:::\n\n```{.r .cell-code}\nset.seed(1234)\nmoran_perm <- moran.mc(hunan$GDPPC, listw = rswm_q, nsim = 999,\n  alternative = \"greater\", zero.policy = TRUE, na.action = na.fail)\nmoran_perm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  hunan$GDPPC \nweights: rswm_q  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.30075, observed rank = 1000, p-value = 0.001\nalternative hypothesis: greater\n```\n\n\n:::\n:::\n\n\nThe observed I is **0.30075**, against a null expectation of **-0.01149**. The analytical p-value is 0.00000109 and the 999-permutation p-value is 0.001. At the 5% level, the permutation test supports positive global spatial association.\n\n### Moran scatterplot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nz_gdppc <- as.numeric(scale(hunan$GDPPC))\nmoran_scatter <- tibble(County = hunan$County, z = z_gdppc,\n                        lag_z = lag.listw(rswm_q, z_gdppc))\nscatter_fit <- lm(lag_z ~ z, data = moran_scatter)\nstopifnot(abs(unname(coef(scatter_fit)[2]) -\n              unname(moran_result$estimate[1])) < 1e-10)\nggplot(moran_scatter, aes(z, lag_z)) +\n  geom_hline(yintercept = 0, colour = \"grey65\", linetype = 2) +\n  geom_vline(xintercept = 0, colour = \"grey65\", linetype = 2) +\n  geom_point(colour = \"#356a92\", size = 2) +\n  geom_smooth(method = \"lm\", se = FALSE, colour = \"#b94948\") +\n  labs(x = \"Standardised county GDPPC\", y = \"W × standardised GDPPC\",\n       title = \"Moran scatterplot\",\n       subtitle = paste(\"Regression slope =\", round(coef(scatter_fit)[2], 4))) +\n  theme_minimal(base_size = 12)\n```\n\n::: {.cell-output-display}\n![Standardised GDPPC against its weighted spatial lag.](index_files/figure-html/a-moran-scatter-1.png){width=1600}\n:::\n:::\n\n\nThe regression slope equals Moran's I for these row-standardised weights. Points in the upper-right and lower-left quadrants contribute to positive association; opposite quadrants suggest spatial contrasts. Quadrants alone do not establish a statistically significant local cluster.\n\n### Monte Carlo distribution and the ggplot2 challenge\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmoran_sim <- tibble(statistic = moran_perm$res[seq_len(999)])\nkable(tibble(Mean = mean(moran_sim$statistic),\n  Variance = var(moran_sim$statistic), Minimum = min(moran_sim$statistic),\n  Maximum = max(moran_sim$statistic)), digits = 6,\n  caption = \"Moran's I: 999 simulated values only\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Moran's I: 999 simulated values only\n\n|      Mean| Variance|   Minimum|  Maximum|\n|---------:|--------:|---------:|--------:|\n| -0.015046| 0.004372| -0.183385| 0.275927|\n\n\n\nPermutation reference distribution, excluding the observed statistic from the histogram.\n:::\n\n```{.r .cell-code}\nggplot(moran_sim, aes(statistic)) +\n  geom_histogram(bins = 25, fill = \"#779db7\", colour = \"white\") +\n  geom_vline(xintercept = -1 / (nrow(hunan) - 1), linetype = 2,\n             colour = \"#4d5965\") +\n  geom_vline(xintercept = unname(moran_perm$statistic), colour = \"#b94948\",\n             linewidth = 1) +\n  labs(x = \"Permuted Moran's I\", y = \"Frequency\",\n       title = \"Random-label reference distribution\",\n       subtitle = \"Red: observed I; dashed: theoretical null expectation\") +\n  theme_minimal(base_size = 12)\n```\n\n::: {.cell-output-display}\n![Permutation reference distribution, excluding the observed statistic from the histogram.](index_files/figure-html/a-moran-permutation-1.png){width=1600}\n:::\n:::\n\n\nThe observed statistic is compared with a distribution generated by reassigning GDPPC values to counties while retaining the neighbourhood structure. The dashed reference is the exact null expectation, −1/(n−1), rather than zero. The histogram and summary use only the 999 simulated statistics; the final observed value in the simulation object is excluded.\n\n## 6. Geary's C: differences between neighbours\n\n### Analytical and permutation tests\n\nGeary's C focuses on squared differences between neighbouring values. Its null expectation is one: C below one suggests positive association, while C above one suggests negative association. In `spdep`, `alternative = \"greater\"` tests the positive-association direction through the deviate (expectation minus observed C), so this alternative seeks **a C smaller than one**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngeary_result <- geary.test(hunan$GDPPC, listw = rswm_q,\n  alternative = \"greater\", zero.policy = TRUE)\ngeary_result\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tGeary C test under randomisation\n\ndata:  hunan$GDPPC \nweights: rswm_q   \n\nGeary C statistic standard deviate = 3.6108, p-value = 0.0001526\nalternative hypothesis: Expectation greater than statistic\nsample estimates:\nGeary C statistic       Expectation          Variance \n        0.6907223         1.0000000         0.0073364 \n```\n\n\n:::\n\n```{.r .cell-code}\nset.seed(1234)\ngeary_perm <- geary.mc(hunan$GDPPC, listw = rswm_q, nsim = 999,\n  alternative = \"greater\", zero.policy = TRUE)\ngeary_perm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Geary C\n\ndata:  hunan$GDPPC \nweights: rswm_q  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.69072, observed rank = 1, p-value = 0.001\nalternative hypothesis: greater\n```\n\n\n:::\n:::\n\n\nThe observed C is **0.69072**. The analytical p-value is 0.000153 and the permutation p-value is 0.001. The permutation test also supports similarity between neighbouring counties.\n\n### Simulated values\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngeary_sim <- tibble(statistic = geary_perm$res[seq_len(999)])\nkable(tibble(Mean = mean(geary_sim$statistic),\n  Variance = var(geary_sim$statistic), Minimum = min(geary_sim$statistic),\n  Maximum = max(geary_sim$statistic)), digits = 6,\n  caption = \"Geary's C: 999 simulated values only\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Geary's C: 999 simulated values only\n\n|     Mean| Variance|  Minimum|  Maximum|\n|--------:|--------:|--------:|--------:|\n| 1.004402| 0.007436| 0.714189| 1.272236|\n\n\n\nGeary's C permutation distribution with its observed and null reference lines.\n:::\n\n```{.r .cell-code}\nggplot(geary_sim, aes(statistic)) +\n  geom_histogram(bins = 25, fill = \"#779db7\", colour = \"white\") +\n  geom_vline(xintercept = 1, linetype = 2, colour = \"#4d5965\") +\n  geom_vline(xintercept = unname(geary_perm$statistic), colour = \"#b94948\",\n             linewidth = 1) +\n  labs(x = \"Permuted Geary's C\", y = \"Frequency\",\n       title = \"Random-label reference distribution\",\n       subtitle = \"Red: observed C; dashed: null expectation of 1\") +\n  theme_minimal(base_size = 12)\n```\n\n::: {.cell-output-display}\n![Geary's C permutation distribution with its observed and null reference lines.](index_files/figure-html/a-geary-permutation-1.png){width=1600}\n:::\n:::\n\n\nThe reference distribution is centred close to one. Comparing both statistics is useful because Moran's I measures covariance, while Geary's C gives greater emphasis to neighbour-to-neighbour differences. Agreement strengthens the description of the pattern; it does not remove dependence on the chosen weights.\n\n## 7. Spatial correlograms\n\nThese lags are **graph orders**, not kilometre bands. Order two links counties reached in two steps, excluding counties already linked at a shorter order; subsequent orders extend this graph distance. Each estimate describes a different neighbourhood relation.\n\n### Moran's I over six orders\n\n\n::: {.cell}\n\n```{.r .cell-code}\nMI_corr <- sp.correlogram(wm_q, hunan$GDPPC, order = 6,\n                         method = \"I\", style = \"W\", zero.policy = TRUE)\nplot(MI_corr, main = \"Moran's I across six neighbour orders\")\n```\n\n::: {.cell-output-display}\n![Moran's I correlogram over six Queen neighbour orders.](index_files/figure-html/a-moran-correlogram-1.png){width=1600}\n:::\n\n```{.r .cell-code}\nprint(MI_corr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatial correlogram for hunan$GDPPC \nmethod: Moran's I\n         estimate expectation   variance standard deviate Pr(I) two sided    \n1 (88)  0.3007500  -0.0114943  0.0043484           4.7351     0.000002189 ***\n2 (88)  0.2060084  -0.0114943  0.0020962           4.7505     0.000002029 ***\n3 (88)  0.0668273  -0.0114943  0.0014602           2.0496        0.040400 *  \n4 (88)  0.0299470  -0.0114943  0.0011717           1.2107        0.226015    \n5 (88) -0.1530471  -0.0114943  0.0012440          -4.0134     0.000059840 ***\n6 (88) -0.1187070  -0.0114943  0.0016791          -2.6164        0.008886 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n### Geary's C over six orders\n\n\n::: {.cell}\n\n```{.r .cell-code}\nGC_corr <- sp.correlogram(wm_q, hunan$GDPPC, order = 6,\n                         method = \"C\", style = \"W\", zero.policy = TRUE)\nplot(GC_corr, main = \"Geary's C across six neighbour orders\")\n```\n\n::: {.cell-output-display}\n![Geary's C correlogram over the same neighbour orders.](index_files/figure-html/a-geary-correlogram-1.png){width=1600}\n:::\n\n```{.r .cell-code}\nprint(GC_corr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatial correlogram for hunan$GDPPC \nmethod: Geary's C\n        estimate expectation  variance standard deviate Pr(I) two sided    \n1 (88) 0.6907223   1.0000000 0.0073364          -3.6108       0.0003052 ***\n2 (88) 0.7630197   1.0000000 0.0049126          -3.3811       0.0007220 ***\n3 (88) 0.9397299   1.0000000 0.0049005          -0.8610       0.3892612    \n4 (88) 1.0098462   1.0000000 0.0039631           0.1564       0.8757128    \n5 (88) 1.2008204   1.0000000 0.0035568           3.3673       0.0007592 ***\n6 (88) 1.0773386   1.0000000 0.0058042           1.0151       0.3100407    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe printed reports provide two-sided p-values, whereas the earlier global tests deliberately used one-sided positive-association alternatives. I also report Benjamini–Hochberg (BH) adjusted p-values within each set of six correlogram tests, to distinguish exploratory lag comparisons from a single test.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglobal_results <- tibble(Statistic = c(\"Moran's I\", \"Geary's C\"),\n  Observed = c(unname(moran_result$estimate[1]), unname(geary_result$estimate[1])),\n  Null_expectation = c(unname(moran_result$estimate[2]), unname(geary_result$estimate[2])),\n  Analytical_p = c(moran_result$p.value, geary_result$p.value),\n  Permutation_p = c(moran_perm$p.value, geary_perm$p.value),\n  Permutations = 999L, Seed = 1234L)\ncorrelogram_results <- bind_rows(\n  as_tibble(MI_corr$res, .name_repair = \"minimal\") |>\n    setNames(c(\"Estimate\", \"Expectation\", \"Variance\")) |>\n    mutate(Statistic = \"Moran's I\", Order = row_number()),\n  as_tibble(GC_corr$res, .name_repair = \"minimal\") |>\n    setNames(c(\"Estimate\", \"Expectation\", \"Variance\")) |>\n    mutate(Statistic = \"Geary's C\", Order = row_number())) |>\n  mutate(Z = (Estimate - Expectation) / sqrt(Variance),\n         P_two_sided = 2 * pnorm(abs(Z), lower.tail = FALSE)) |>\n  group_by(Statistic) |>\n  mutate(P_BH = p.adjust(P_two_sided, method = \"BH\")) |>\n  ungroup()\ndir.create(\"handson4A/results\", recursive = TRUE, showWarnings = FALSE)\nwrite_csv(global_results, \"handson4A/results/global-tests.csv\")\nwrite_csv(correlogram_results, \"handson4A/results/correlograms.csv\")\nkable(global_results, digits = 6, caption = \"Global autocorrelation results\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Global autocorrelation results\n\n|Statistic | Observed| Null_expectation| Analytical_p| Permutation_p| Permutations| Seed|\n|:---------|--------:|----------------:|------------:|-------------:|------------:|----:|\n|Moran's I | 0.300750|        -0.011494|     0.000001|         0.001|          999| 1234|\n|Geary's C | 0.690722|         1.000000|     0.000153|         0.001|          999| 1234|\n\n\n:::\n\n```{.r .cell-code}\nkable(correlogram_results, digits = 6,\n      caption = \"Correlogram estimates and BH adjustment within each six-lag family\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Correlogram estimates and BH adjustment within each six-lag family\n\n|  Estimate| Expectation| Variance|Statistic | Order|         Z| P_two_sided|     P_BH|\n|---------:|-----------:|--------:|:---------|-----:|---------:|-----------:|--------:|\n|  0.300750|   -0.011494| 0.004348|Moran's I |     1|  4.735132|    0.000002| 0.000007|\n|  0.206008|   -0.011494| 0.002096|Moran's I |     2|  4.750547|    0.000002| 0.000007|\n|  0.066827|   -0.011494| 0.001460|Moran's I |     3|  2.049635|    0.040400| 0.048480|\n|  0.029947|   -0.011494| 0.001172|Moran's I |     4|  1.210688|    0.226015| 0.226015|\n| -0.153047|   -0.011494| 0.001244|Moran's I |     5| -4.013439|    0.000060| 0.000120|\n| -0.118707|   -0.011494| 0.001679|Moran's I |     6| -2.616422|    0.008886| 0.013328|\n|  0.690722|    1.000000| 0.007336|Geary's C |     1| -3.610830|    0.000305| 0.001518|\n|  0.763020|    1.000000| 0.004913|Geary's C |     2| -3.381081|    0.000722| 0.001518|\n|  0.939730|    1.000000| 0.004901|Geary's C |     3| -0.860958|    0.389261| 0.467113|\n|  1.009846|    1.000000| 0.003963|Geary's C |     4|  0.156406|    0.875713| 0.875713|\n|  1.200820|    1.000000| 0.003557|Geary's C |     5|  3.367273|    0.000759| 0.001518|\n|  1.077339|    1.000000| 0.005804|Geary's C |     6|  1.015137|    0.310041| 0.465061|\n\n\n:::\n:::\n\n\nFor Moran's I, the nominally significant orders are 1, 2, 3, 5, 6; after BH adjustment they are 1, 2, 3, 5, 6. Positive estimates at short orders and negative estimates at some longer orders describe similarity nearby and contrast across broader parts of the province. A nonsignificant order does not prove spatial independence.\n\n## 8. Reflection and reproducibility\n\nGlobal measures provide evidence about the arrangement of county GDPPC values, rather than a test of equal development or a causal explanation. Raw GDPPC contains unusually high values, and the result could change with a transformation, another indicator, or a different neighbourhood definition. The analysis refers to the 2012 snapshot and these 88 administrative units.\n\nNext, [Exercise 5B](../handson4B/index.qmd) examines the locations of local clusters, outliers, hot spots and cold spots.\n\n- [Download the R analysis](R/analysis.R)\n- [Download global test results](results/global-tests.csv)\n- [Download correlogram results](results/correlograms.csv)\n\nOpen `ISSS626-GAA.Rproj` and run `source(\"handson4A/R/analysis.R\")` from the project root. To regenerate the page with fresh computation, run `quarto render handson4A/index.qmd`. The script uses seed 1234 and 999 permutations for each global Monte Carlo test.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkable(tibble(Package = c(\"sf\", \"spdep\", \"tmap\", \"dplyr\", \"readr\", \"ggplot2\"),\n  Version = vapply(c(\"sf\", \"spdep\", \"tmap\", \"dplyr\", \"readr\", \"ggplot2\"),\n                   function(p) as.character(packageVersion(p)), character(1))))\n```\n\n::: {.cell-output-display}\n\n\n|Package |Version |\n|:-------|:-------|\n|sf      |1.1.3   |\n|spdep   |1.4.2   |\n|tmap    |4.4.1   |\n|dplyr   |1.2.1   |\n|readr   |2.2.0   |\n|ggplot2 |4.0.3   |\n\n\n:::\n\n```{.r .cell-code}\nR.version.string\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"R version 4.5.3 (2026-03-11 ucrt)\"\n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}