<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Zhenhua Liu">
<meta name="dcterms.date" content="2026-09-19">

<title>Hands-on Exercise 2B – ISSS626-GAA</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-d89924325737da961fd3c7ac1ec1be2d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed exercise-page quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">ISSS626-GAA</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Hands-on Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercise">    
        <li>
    <a class="dropdown-item" href="../hands-on-exercise-1a/index.html">
 <span class="dropdown-text">Hands-on Exercise 1A</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../hands-on-exercise-1b/index.html">
 <span class="dropdown-text">Hands-on Exercise 1B</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../handson2A/index.html">
 <span class="dropdown-text">Hands-on Exercise 2A</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../handson2B/index.html">
 <span class="dropdown-text">Hands-on Exercise 2B</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#setup-and-reproducible-preparation" id="toc-setup-and-reproducible-preparation" class="nav-link" data-scroll-target="#setup-and-reproducible-preparation">1. Setup and reproducible preparation</a></li>
  <li><a href="#study-windows-and-the-random-reference-model" id="toc-study-windows-and-the-random-reference-model" class="nav-link" data-scroll-target="#study-windows-and-the-random-reference-model">2. Study windows and the random reference model</a></li>
  <li><a href="#simulation-envelopes-and-edge-correction" id="toc-simulation-envelopes-and-edge-correction" class="nav-link" data-scroll-target="#simulation-envelopes-and-edge-correction">3. Simulation envelopes and edge correction</a></li>
  <li><a href="#g-distance-from-one-site-to-its-nearest-neighbour" id="toc-g-distance-from-one-site-to-its-nearest-neighbour" class="nav-link" data-scroll-target="#g-distance-from-one-site-to-its-nearest-neighbour">4. G: distance from one site to its nearest neighbour</a></li>
  <li><a href="#f-distance-from-empty-space-to-a-site" id="toc-f-distance-from-empty-space-to-a-site" class="nav-link" data-scroll-target="#f-distance-from-empty-space-to-a-site">5. F: distance from empty space to a site</a></li>
  <li><a href="#k-cumulative-neighbours-across-distance" id="toc-k-cumulative-neighbours-across-distance" class="nav-link" data-scroll-target="#k-cumulative-neighbours-across-distance">6. K: cumulative neighbours across distance</a></li>
  <li><a href="#l-a-centred-comparison-with-randomness" id="toc-l-a-centred-comparison-with-randomness" class="nav-link" data-scroll-target="#l-a-centred-comparison-with-randomness">7. L: a centred comparison with randomness</a></li>
  <li><a href="#global-comparison-and-numerical-interpretation" id="toc-global-comparison-and-numerical-interpretation" class="nav-link" data-scroll-target="#global-comparison-and-numerical-interpretation">8. Global comparison and numerical interpretation</a></li>
  <li><a href="#sensitivity-to-co-located-records" id="toc-sensitivity-to-co-located-records" class="nav-link" data-scroll-target="#sensitivity-to-co-located-records">9. Sensitivity to co-located records</a></li>
  <li><a href="#what-i-learned-and-limitations" id="toc-what-i-learned-and-limitations" class="nav-link" data-scroll-target="#what-i-learned-and-limitations">10. What I learned and limitations</a></li>
  <li><a href="#reproducibility-and-references" id="toc-reproducibility-and-references" class="nav-link" data-scroll-target="#reproducibility-and-references">Reproducibility and references</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Hands-on Exercise 2B</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
<p class="subtitle lead">Second-order point patterns: G, F, K and L functions</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Zhenhua Liu </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 19, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">Overview</h2>
<p><a href="../handson2A/index.html">Exercise 2A</a> mapped the intensity of childcare service records. Here I ask a different question: how does the spacing of childcare <strong>locations</strong> in Choa Chu Kang and Tampines compare with a uniform random pattern inside the same planning boundaries?</p>
<p>Following <a href="https://r4gdsa.netlify.app/chap05.html">course Chapter 5</a>, I examine G, F, K and L functions in that order, then compare observed curves with Monte Carlo simulations. G and F describe nearest-neighbour and empty-space distributions; K and L summarise cumulative interpoint relationships. These descriptions can reveal departures from a reference model, but do not identify the causal process that produced the locations.</p>
</section>
<section id="setup-and-reproducible-preparation" class="level2">
<h2 class="anchored" data-anchor-id="setup-and-reproducible-preparation">1. Setup and reproducible preparation</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Linking to GEOS 3.14.1, GDAL 3.12.1, PROJ 9.7.1; sf_use_s2() is TRUE</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(spatstat.geom)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: spatstat.data</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: spatstat.univar</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>spatstat.univar 3.2-0</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>spatstat.geom 3.8-3</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(spatstat.explore)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: spatstat.random</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>spatstat.random 3.5-1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: nlme</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'nlme'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    collapse</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>spatstat.explore 3.8-2</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(spatstat.random)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(terra)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>terra 1.9.50</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'terra'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:spatstat.geom':

    area, delaunay, is.empty, rescale, rotate, shift, where.max,
    where.min</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tmap)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 method overwritten by 'stars':
  method                  from
  st_interpolate_aw.stars sf  </code></pre>
</div>
</div>
<p>I reuse the <a href="https://data.gov.sg/datasets/d_5d668e3f544335f8028f546827b773b4/view">ECDA childcare snapshot</a> and <a href="https://data.gov.sg/datasets/d_8594ae9ff96d0c708bc2af633048edfb/view">MP2019 subzone boundary</a> from 2A. The childcare layer describes <strong>December 2021</strong>, even though the portal was updated in 2026. Reusing the input files makes the comparison temporally consistent. It does not make the inventory current.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>raw_dir <span class="ot">&lt;-</span> <span class="st">"handson2A/data/raw"</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>required <span class="ot">&lt;-</span> <span class="fu">file.path</span>(raw_dir, <span class="fu">c</span>(<span class="st">"childcare.geojson"</span>, <span class="st">"mp19-subzone.geojson"</span>))</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">all</span>(<span class="fu">file.exists</span>(required))) <span class="fu">stop</span>(<span class="st">"Run source('handson2A/R/download-data.R') first."</span>)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>childcare_raw <span class="ot">&lt;-</span> <span class="fu">st_read</span>(required[<span class="dv">1</span>], <span class="at">quiet =</span> <span class="cn">TRUE</span>)</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>subzones_raw <span class="ot">&lt;-</span> <span class="fu">st_read</span>(required[<span class="dv">2</span>], <span class="at">quiet =</span> <span class="cn">TRUE</span>)</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>input_audit <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">dataset =</span> <span class="fu">c</span>(<span class="st">"Child Care Services"</span>, <span class="st">"MP2019 subzones"</span>),</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">records =</span> <span class="fu">c</span>(<span class="fu">nrow</span>(childcare_raw), <span class="fu">nrow</span>(subzones_raw)),</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">geometry =</span> <span class="fu">c</span>(<span class="fu">as.character</span>(<span class="fu">unique</span>(<span class="fu">st_geometry_type</span>(childcare_raw))),</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>               <span class="fu">as.character</span>(<span class="fu">unique</span>(<span class="fu">st_geometry_type</span>(subzones_raw)))),</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">epsg =</span> <span class="fu">c</span>(<span class="fu">st_crs</span>(childcare_raw)<span class="sc">$</span>epsg, <span class="fu">st_crs</span>(subzones_raw)<span class="sc">$</span>epsg),</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">empty =</span> <span class="fu">c</span>(<span class="fu">sum</span>(<span class="fu">st_is_empty</span>(childcare_raw)), <span class="fu">sum</span>(<span class="fu">st_is_empty</span>(subzones_raw))),</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">invalid =</span> <span class="fu">c</span>(<span class="fu">sum</span>(<span class="sc">!</span><span class="fu">st_is_valid</span>(childcare_raw)), <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">st_is_valid</span>(subzones_raw)))</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>input_audit</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>              dataset records     geometry epsg empty invalid
1 Child Care Services    1925        POINT 4326     0       0
2     MP2019 subzones     332 MULTIPOLYGON 4326     0       6</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="sc">!</span><span class="fu">any</span>(<span class="fu">st_is_empty</span>(childcare_raw)), <span class="sc">!</span><span class="fu">any</span>(<span class="fu">st_is_empty</span>(subzones_raw)),</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>          <span class="fu">all</span>(<span class="fu">st_geometry_type</span>(childcare_raw) <span class="sc">==</span> <span class="st">"POINT"</span>))</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>childcare <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(childcare_raw, <span class="dv">3414</span>)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>subzones <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(<span class="fu">st_make_valid</span>(subzones_raw), <span class="dv">3414</span>)</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>subzones <span class="ot">&lt;-</span> <span class="fu">filter</span>(subzones, SUBZONE_N <span class="sc">!=</span> <span class="st">"SOUTHERN GROUP"</span>,</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>                   <span class="sc">!</span>PLN_AREA_N <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"WESTERN ISLANDS"</span>, <span class="st">"NORTH-EASTERN ISLANDS"</span>))</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">st_crs</span>(childcare) <span class="sc">==</span> <span class="fu">st_crs</span>(subzones), <span class="sc">!</span><span class="fu">st_is_longlat</span>(childcare))</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>singapore <span class="ot">&lt;-</span> <span class="fu">st_union</span>(subzones)</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>sg_window <span class="ot">&lt;-</span> <span class="fu">as.owin</span>(singapore)</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>xy <span class="ot">&lt;-</span> <span class="fu">st_coordinates</span>(childcare)</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>inside <span class="ot">&lt;-</span> <span class="fu">inside.owin</span>(xy[, <span class="dv">1</span>], xy[, <span class="dv">2</span>], sg_window)</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>duplicate_location <span class="ot">&lt;-</span> <span class="fu">duplicated</span>(<span class="fu">as.data.frame</span>(xy))</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Co-located records may be different operators. Keep them for service intensity.</span></span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>childcare_ppp <span class="ot">&lt;-</span> <span class="fu">ppp</span>(xy[inside, <span class="dv">1</span>], xy[inside, <span class="dv">2</span>], <span class="at">window =</span> sg_window,</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>                     <span class="at">checkdup =</span> <span class="cn">FALSE</span>)</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a><span class="fu">unitname</span>(childcare_ppp) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"metre"</span>, <span class="st">"metres"</span>)</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>childcare_unique <span class="ot">&lt;-</span> <span class="fu">unique</span>(childcare_ppp)</span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>quality_audit <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">measure =</span> <span class="fu">c</span>(<span class="st">"Imported records"</span>, <span class="st">"Retained subzones"</span>, <span class="st">"Outside study window"</span>,</span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a>              <span class="st">"Records at repeated coordinates (beyond first)"</span>, <span class="st">"Records in window"</span>,</span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a>              <span class="st">"Distinct locations in window"</span>, <span class="st">"Study area (km2)"</span>),</span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">value =</span> <span class="fu">c</span>(<span class="fu">nrow</span>(childcare), <span class="fu">nrow</span>(subzones), <span class="fu">sum</span>(<span class="sc">!</span>inside), <span class="fu">sum</span>(duplicate_location),</span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a>            <span class="fu">npoints</span>(childcare_ppp), <span class="fu">npoints</span>(childcare_unique), <span class="fu">area.owin</span>(sg_window) <span class="sc">/</span> <span class="fl">1e6</span>)</span>
<span id="cb27-24"><a href="#cb27-24" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-25"><a href="#cb27-25" aria-hidden="true" tabindex="-1"></a>quality_audit</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                         measure     value
1                               Imported records 1925.0000
2                              Retained subzones  327.0000
3                           Outside study window    0.0000
4 Records at repeated coordinates (beyond first)  187.0000
5                              Records in window 1925.0000
6                   Distinct locations in window 1738.0000
7                               Study area (km2)  669.5167</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dir.create</span>(<span class="st">"handson2A/data/derived"</span>, <span class="at">recursive =</span> <span class="cn">TRUE</span>, <span class="at">showWarnings =</span> <span class="cn">FALSE</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">saveRDS</span>(subzones, <span class="st">"handson2A/data/derived/subzones-clean.rds"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The shared preparation transforms both layers to EPSG:3414, checks geometry and exclusions, and constructs polygonal observation windows. This page executes that preparation itself; it does not depend on objects left in an earlier R session.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>area_names <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"PUNGGOL"</span>, <span class="st">"TAMPINES"</span>, <span class="st">"CHOA CHU KANG"</span>, <span class="st">"JURONG WEST"</span>)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>areas <span class="ot">&lt;-</span> <span class="fu">lapply</span>(area_names, <span class="cf">function</span>(nm) <span class="fu">st_union</span>(<span class="fu">filter</span>(subzones, PLN_AREA_N <span class="sc">==</span> nm)))</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(areas) <span class="ot">&lt;-</span> area_names</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>area_windows <span class="ot">&lt;-</span> <span class="fu">lapply</span>(areas, as.owin)</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>area_patterns <span class="ot">&lt;-</span> <span class="fu">lapply</span>(area_windows, <span class="cf">function</span>(w) childcare_ppp[w])</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>area_summary <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">planning_area =</span> area_names,</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">records =</span> <span class="fu">vapply</span>(area_patterns, npoints, <span class="fu">integer</span>(<span class="dv">1</span>)),</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">locations =</span> <span class="fu">vapply</span>(area_patterns, <span class="cf">function</span>(x) <span class="fu">npoints</span>(<span class="fu">unique</span>(x)), <span class="fu">integer</span>(<span class="dv">1</span>)),</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">km2 =</span> <span class="fu">vapply</span>(area_windows, area.owin, <span class="fu">numeric</span>(<span class="dv">1</span>)) <span class="sc">/</span> <span class="fl">1e6</span></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">records_per_km2 =</span> records <span class="sc">/</span> km2)</span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>area_summary</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>              planning_area records locations       km2 records_per_km2
PUNGGOL             PUNGGOL      72        65  9.374274        7.680595
TAMPINES           TAMPINES     117       105 20.795431        5.626236
CHOA CHU KANG CHOA CHU KANG      74        67  6.117294       12.096852
JURONG WEST     JURONG WEST     110        99 14.680536        7.492914</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Which events are being analysed?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Which events are being analysed?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Several childcare records share exactly the same coordinate. The principal analysis here collapses these to distinct sites because a simple point-process model assumes separate event locations. This is an explicit change of unit, not a claim that the original records are erroneous. A final sensitivity analysis restores every record. The record-based KDE in 2A remains unchanged.</p>
</div>
</div>
</section>
<section id="study-windows-and-the-random-reference-model" class="level2">
<h2 class="anchored" data-anchor-id="study-windows-and-the-random-reference-model">2. Study windows and the random reference model</h2>
<p>Under the null model, the observed number of sites is fixed and each location is independently uniform within its planning-area polygon. This is <strong>conditional complete spatial randomness (CSR)</strong>. The alternative is departure from that model in the selected distance range. Keeping the same boundary and count avoids confounding location pattern with different totals or observation areas.</p>
<p>I preselect <strong>0–500 m</strong> and 129 equally spaced distances for both areas, before examining the curves. This focuses the comparison on neighbourhood-scale spacing and avoids searching many distance ranges for a favourable result. Distances are straight-line metres, not walking routes. A 500 m separation therefore has no automatic interpretation as a service catchment.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Simple point-process diagnostics use distinct sites; records remain in 2A's KDE.</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>patterns <span class="ot">&lt;-</span> <span class="fu">lapply</span>(area_patterns[<span class="fu">c</span>(<span class="st">"CHOA CHU KANG"</span>, <span class="st">"TAMPINES"</span>)], unique)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>nsim <span class="ot">&lt;-</span> <span class="dv">199</span>L</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>distance_grid <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">500</span>, <span class="at">length.out =</span> <span class="dv">129</span>)</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>functions <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">G =</span> Gest, <span class="at">F =</span> Fest, <span class="at">K =</span> Kest, <span class="at">L =</span> Lest)</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>corrections <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">G =</span> <span class="st">"km"</span>, <span class="at">F =</span> <span class="st">"km"</span>, <span class="at">K =</span> <span class="st">"Ripley"</span>, <span class="at">L =</span> <span class="st">"Ripley"</span>)</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">20260921</span>)</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Conditional CSR: each simulation preserves the area's number of distinct sites.</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>simulations <span class="ot">&lt;-</span> <span class="fu">lapply</span>(patterns, <span class="cf">function</span>(x)</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lapply</span>(<span class="fu">seq_len</span>(nsim), <span class="cf">function</span>(i) <span class="fu">runifpoint</span>(<span class="fu">npoints</span>(x), <span class="at">win =</span> <span class="fu">Window</span>(x))))</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>estimates <span class="ot">&lt;-</span> <span class="fu">lapply</span>(patterns, <span class="cf">function</span>(x) <span class="fu">lapply</span>(<span class="fu">names</span>(functions), <span class="cf">function</span>(fn)</span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>  functions[[fn]](x, <span class="at">r =</span> distance_grid, <span class="at">correction =</span> corrections[[fn]])))</span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (nm <span class="cf">in</span> <span class="fu">names</span>(estimates)) <span class="fu">names</span>(estimates[[nm]]) <span class="ot">&lt;-</span> <span class="fu">names</span>(functions)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>ℹ tmap modes "plot" - "view"
ℹ toggle with `tmap::ttm()`</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>comparison_maps <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="fu">names</span>(patterns), <span class="cf">function</span>(nm) {</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  sites <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(<span class="fu">data.frame</span>(<span class="at">x =</span> patterns[[nm]]<span class="sc">$</span>x, <span class="at">y =</span> patterns[[nm]]<span class="sc">$</span>y),</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"x"</span>, <span class="st">"y"</span>), <span class="at">crs =</span> <span class="dv">3414</span>)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(areas[[nm]]) <span class="sc">+</span> <span class="fu">tm_borders</span>(<span class="at">col =</span> <span class="st">"#465d91"</span>, <span class="at">lwd =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tm_shape</span>(sites) <span class="sc">+</span> <span class="fu">tm_dots</span>(<span class="at">col =</span> <span class="st">"#465d91"</span>, <span class="at">size =</span> <span class="fl">0.06</span>) <span class="sc">+</span></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tm_title</span>(tools<span class="sc">::</span><span class="fu">toTitleCase</span>(<span class="fu">tolower</span>(nm))) <span class="sc">+</span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tm_scalebar</span>(<span class="at">position =</span> <span class="fu">tm_pos_in</span>(<span class="st">"left"</span>, <span class="st">"bottom"</span>))</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(comparison_maps[[<span class="dv">1</span>]], comparison_maps[[<span class="dv">2</span>]], <span class="at">ncol =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/area-map-1.png" class="img-fluid figure-img" alt="Maps of distinct childcare sites in Choa Chu Kang and Tampines." width="1350"></p>
<figcaption>Distinct childcare sites and the actual observation windows. Each panel has its own map scale.</figcaption>
</figure>
</div>
</div>
</div>
<p>The analysis uses <strong>67 sites</strong> in Choa Chu Kang and <strong>105 sites</strong> in Tampines. Both polygons include land that is not equally plausible for childcare facilities. Rejection of this homogeneous model could reflect land use or population gradients, as well as genuine interaction between providers.</p>
</section>
<section id="simulation-envelopes-and-edge-correction" class="level2">
<h2 class="anchored" data-anchor-id="simulation-envelopes-and-edge-correction">3. Simulation envelopes and edge correction</h2>
<p>Points near an observation boundary may have unobserved neighbours outside it. For G and F, I use Kaplan–Meier correction to handle censored distances. For K and L, I use Ripley’s isotropic edge correction. I apply the same estimator to the observed pattern and every simulation. For G I also display the course’s border estimator as a sensitivity comparison.</p>
<p>The 199 simulated patterns in each area are reused across all four functions. This makes differences between diagnostics easier to interpret because they are not caused by unrelated simulation draws.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>envelopes <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="fu">names</span>(patterns), <span class="cf">function</span>(nm) {</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  result <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="fu">names</span>(functions), <span class="cf">function</span>(fn) {</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">envelope</span>(patterns[[nm]], <span class="at">fun =</span> functions[[fn]],</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">r =</span> distance_grid, <span class="at">correction =</span> corrections[[fn]],</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">simulate =</span> simulations[[nm]], <span class="at">nsim =</span> nsim, <span class="at">nrank =</span> <span class="dv">5</span>,</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">global =</span> <span class="cn">FALSE</span>, <span class="at">use.theory =</span> <span class="cn">TRUE</span>, <span class="at">savefuns =</span> <span class="cn">TRUE</span>, <span class="at">verbose =</span> <span class="cn">FALSE</span>)</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>  })</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">names</span>(result) <span class="ot">&lt;-</span> <span class="fu">names</span>(functions)</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>  result</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(envelopes) <span class="ot">&lt;-</span> <span class="fu">names</span>(patterns)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-style-default callout-important callout-titled" title="An envelope is not automatically a global test">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>An envelope is not automatically a global test
</div>
</div>
<div class="callout-body-container callout-body">
<p>These plots show <strong>95% pointwise</strong> envelopes: with 199 simulations and <code>nrank = 5</code>, the two-sided level at one preselected distance is 2 × 5 / 200 = 0.05. Scanning the whole curve for any crossing changes that error rate. I therefore report a separate maximum-deviation Monte Carlo test over the full 0–500 m interval and apply Holm adjustment across the eight area/function comparisons.</p>
<p>The course’s 99-simulation, rank-one pointwise envelope has level 0.02 at a single distance, not 0.001. Our 199-simulation Monte Carlo p-value has resolution 0.005 and cannot support a claim of p &lt; 0.001. I use a stated 5% threshold rather than repeating that mismatch.</p>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>plot_comparison <span class="ot">&lt;-</span> <span class="cf">function</span>(fn) {</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  old <span class="ot">&lt;-</span> <span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">3</span>, <span class="dv">1</span>))</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">on.exit</span>(<span class="fu">par</span>(old))</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (nm <span class="cf">in</span> <span class="fu">names</span>(envelopes)) {</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>    e <span class="ot">&lt;-</span> envelopes[[nm]][[fn]]</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (fn <span class="sc">==</span> <span class="st">"L"</span>) {</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">plot</span>(e, . <span class="sc">-</span> r <span class="sc">~</span> r, <span class="at">main =</span> tools<span class="sc">::</span><span class="fu">toTitleCase</span>(<span class="fu">tolower</span>(nm)),</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>           <span class="at">xlab =</span> <span class="st">"Distance r (m)"</span>, <span class="at">ylab =</span> <span class="st">"L(r) - r (m)"</span>, <span class="at">legend =</span> <span class="cn">FALSE</span>)</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>    } <span class="cf">else</span> {</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>      <span class="fu">plot</span>(e, <span class="at">main =</span> tools<span class="sc">::</span><span class="fu">toTitleCase</span>(<span class="fu">tolower</span>(nm)),</span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>           <span class="at">xlab =</span> <span class="st">"Distance r (m)"</span>, <span class="at">ylab =</span> <span class="cf">if</span> (fn <span class="sc">==</span> <span class="st">"K"</span>) <span class="st">"K(r) (m²)"</span> <span class="cf">else</span> <span class="fu">paste0</span>(fn, <span class="st">"(r)"</span>),</span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>           <span class="at">legend =</span> <span class="cn">FALSE</span>)</span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">legend</span>(<span class="st">"topleft"</span>, <span class="fu">c</span>(<span class="st">"Observed"</span>, <span class="st">"CSR reference"</span>, <span class="st">"95% pointwise envelope"</span>),</span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a>           <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="cn">NA</span>), <span class="at">pch =</span> <span class="fu">c</span>(<span class="cn">NA</span>, <span class="cn">NA</span>, <span class="dv">15</span>),</span>
<span id="cb37-16"><a href="#cb37-16" aria-hidden="true" tabindex="-1"></a>           <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"black"</span>, <span class="st">"red"</span>, <span class="st">"grey80"</span>), <span class="at">cex =</span> <span class="fl">0.65</span>, <span class="at">bty =</span> <span class="st">"n"</span>)</span>
<span id="cb37-17"><a href="#cb37-17" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb37-18"><a href="#cb37-18" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="g-distance-from-one-site-to-its-nearest-neighbour" class="level2">
<h2 class="anchored" data-anchor-id="g-distance-from-one-site-to-its-nearest-neighbour">4. G: distance from one site to its nearest neighbour</h2>
<p>G(r) is the probability that a typical site has another site within r metres. Under homogeneous Poisson CSR its reference curve is <span class="math inline">\(G_0(r)=1-\exp(-\lambda\pi r^2)\)</span>, where <span class="math inline">\(\lambda\)</span> is sites per square metre. An observed curve above the reference indicates more short nearest-neighbour distances; below it indicates fewer. This direction describes spacing, not proof that operators attract or repel one another.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>G_border <span class="ot">&lt;-</span> <span class="fu">Gest</span>(patterns[[<span class="st">"CHOA CHU KANG"</span>]], <span class="at">r =</span> distance_grid, <span class="at">correction =</span> <span class="st">"border"</span>)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>G_km <span class="ot">&lt;-</span> estimates[[<span class="st">"CHOA CHU KANG"</span>]][[<span class="st">"G"</span>]]</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">distance_m =</span> <span class="fu">c</span>(<span class="dv">100</span>, <span class="dv">250</span>, <span class="dv">500</span>),</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">border =</span> <span class="fu">approx</span>(G_border<span class="sc">$</span>r, G_border<span class="sc">$</span>rs, <span class="at">xout =</span> <span class="fu">c</span>(<span class="dv">100</span>, <span class="dv">250</span>, <span class="dv">500</span>))<span class="sc">$</span>y,</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">Kaplan_Meier =</span> <span class="fu">approx</span>(G_km<span class="sc">$</span>r, G_km<span class="sc">$</span>km, <span class="at">xout =</span> <span class="fu">c</span>(<span class="dv">100</span>, <span class="dv">250</span>, <span class="dv">500</span>))<span class="sc">$</span>y)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  distance_m    border Kaplan_Meier
1        100 0.2874060    0.2867671
2        250 0.9302326    0.9360480
3        500 1.0000000    1.0000000</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_comparison</span>(<span class="st">"G"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/g-function-1.png" class="img-fluid figure-img" alt="Nearest-neighbour distribution curves for Choa Chu Kang and Tampines against CSR envelopes." width="1350"></p>
<figcaption>G-function estimates and 95% pointwise simulation envelopes, using Kaplan–Meier correction.</figcaption>
</figure>
</div>
</div>
</div>
<p>The border-versus-Kaplan–Meier table is a reminder that edge treatment changes the estimate, especially when many nearest-neighbour distances are censored. The simulation plots use Kaplan–Meier consistently in both areas. A steep early rise means many sites already have a close neighbour; levelling near one leaves little additional information at larger distances.</p>
</section>
<section id="f-distance-from-empty-space-to-a-site" class="level2">
<h2 class="anchored" data-anchor-id="f-distance-from-empty-space-to-a-site">5. F: distance from empty space to a site</h2>
<p>F(r) starts at an arbitrary location in the study window and measures the distance to the nearest site. A low F relative to CSR means more empty space far from a site. Clusters can therefore produce a high G but a low F: sites have close neighbours while the gaps between clusters remain large.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_comparison</span>(<span class="st">"F"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/f-function-1.png" class="img-fluid figure-img" alt="Empty-space distribution curves for the two planning areas." width="1350"></p>
<figcaption>Empty-space functions with Kaplan–Meier correction and 95% pointwise envelopes.</figcaption>
</figure>
</div>
</div>
</div>
<p>Unlike G, F gives weight to the whole polygon rather than starting at the observed childcare sites. Low-density industrial or open areas can therefore strongly affect this diagnostic. The raster approximation used internally by <code>Fest()</code> and the finite number of sites also limit precision. I do not interpret F as the proportion of residents who can access childcare.</p>
</section>
<section id="k-cumulative-neighbours-across-distance" class="level2">
<h2 class="anchored" data-anchor-id="k-cumulative-neighbours-across-distance">6. K: cumulative neighbours across distance</h2>
<p>K(r) is the expected number of other events within r of a typical event, normalised by intensity. Its CSR reference is <span class="math inline">\(\pi r^2\)</span> and its units here are square metres. Values above the reference indicate an excess of neighbours within that distance. K is cumulative: an excess established at small distances can remain visible at larger distances.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_comparison</span>(<span class="st">"K"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/k-function-1.png" class="img-fluid figure-img" alt="Cumulative K-function curves with simulation envelopes in both areas." width="1350"></p>
<figcaption>Ripley-corrected K curves in m², with the CSR reference πr².</figcaption>
</figure>
</div>
</div>
</div>
<p>I plot K directly rather than subtracting r. Subtracting metres from square metres is dimensionally inconsistent and does not centre the CSR expectation at zero. The transformed L function below provides the appropriate centred view in metre units.</p>
</section>
<section id="l-a-centred-comparison-with-randomness" class="level2">
<h2 class="anchored" data-anchor-id="l-a-centred-comparison-with-randomness">7. L: a centred comparison with randomness</h2>
<p>The transformation <span class="math inline">\(L(r)=\sqrt{K(r)/\pi}\)</span> has CSR reference r. Consequently, <strong>L(r) − r</strong> has a zero reference: positive values indicate excess cumulative neighbours and negative values indicate fewer. L repackages K for easier reading; it is not an independent source of evidence.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_comparison</span>(<span class="st">"L"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/l-function-1.png" class="img-fluid figure-img" alt="Centred L-function curves for Choa Chu Kang and Tampines." width="1350"></p>
<figcaption>Centred L curves; zero is the homogeneous CSR reference. Shading is pointwise, not a simultaneous band.</figcaption>
</figure>
</div>
</div>
</div>
<p>The height of L(r) − r is an effect-size description in metres, not a p-value. I examine its direction alongside the explicit simulation results below, rather than declaring significance from a visually prominent peak.</p>
</section>
<section id="global-comparison-and-numerical-interpretation" class="level2">
<h2 class="anchored" data-anchor-id="global-comparison-and-numerical-interpretation">8. Global comparison and numerical interpretation</h2>
<p>For each observed or simulated curve, I compute a single maximum absolute deviation from the same CSR reference across the preselected distance grid. The Monte Carlo p-value is <span class="math inline">\((1+b)/(1+199)\)</span>, where b is the number of simulated deviations at least as large as the observed one. Counting ties as exceedances is conservative. The reference is fixed by the area’s count, geometry and distance grid, so it is applied identically to all realisations.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># A fixed reference and a preselected distance interval make one statistic per curve.</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare the observed maximum deviation against the same statistic for every simulation.</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>deviation_test <span class="ot">&lt;-</span> <span class="cf">function</span>(e) {</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>  simulated <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">attr</span>(e, <span class="st">"simfuns"</span>))</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>  simulated <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(simulated[, <span class="fu">startsWith</span>(<span class="fu">names</span>(simulated), <span class="st">"sim"</span>), <span class="at">drop =</span> <span class="cn">FALSE</span>])</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>  valid <span class="ot">&lt;-</span> <span class="fu">is.finite</span>(e<span class="sc">$</span>obs) <span class="sc">&amp;</span> <span class="fu">is.finite</span>(e<span class="sc">$</span>theo) <span class="sc">&amp;</span></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">apply</span>(simulated, <span class="dv">1</span>, <span class="cf">function</span>(v) <span class="fu">all</span>(<span class="fu">is.finite</span>(v)))</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="sc">!</span><span class="fu">all</span>(valid)) <span class="fu">stop</span>(<span class="st">"Undefined estimates on the selected distance grid; inspect the window."</span>)</span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>  observed <span class="ot">&lt;-</span> <span class="fu">max</span>(<span class="fu">abs</span>(e<span class="sc">$</span>obs <span class="sc">-</span> e<span class="sc">$</span>theo))</span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>  null_deviations <span class="ot">&lt;-</span> <span class="fu">apply</span>(<span class="fu">abs</span>(<span class="fu">sweep</span>(simulated, <span class="dv">1</span>, e<span class="sc">$</span>theo, <span class="st">"-"</span>)), <span class="dv">2</span>, max)</span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="at">deviation =</span> observed, <span class="at">p =</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="fu">sum</span>(null_deviations <span class="sc">&gt;=</span> observed)) <span class="sc">/</span></span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a>      (<span class="dv">1</span> <span class="sc">+</span> <span class="fu">ncol</span>(simulated)))</span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb44-14"><a href="#cb44-14" aria-hidden="true" tabindex="-1"></a>test_results <span class="ot">&lt;-</span> <span class="fu">do.call</span>(rbind, <span class="fu">lapply</span>(<span class="fu">names</span>(envelopes), <span class="cf">function</span>(nm)</span>
<span id="cb44-15"><a href="#cb44-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">do.call</span>(rbind, <span class="fu">lapply</span>(<span class="fu">names</span>(functions), <span class="cf">function</span>(fn) {</span>
<span id="cb44-16"><a href="#cb44-16" aria-hidden="true" tabindex="-1"></a>    test <span class="ot">&lt;-</span> <span class="fu">deviation_test</span>(envelopes[[nm]][[fn]])</span>
<span id="cb44-17"><a href="#cb44-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">data.frame</span>(<span class="at">area =</span> nm, <span class="at">function_name =</span> fn,</span>
<span id="cb44-18"><a href="#cb44-18" aria-hidden="true" tabindex="-1"></a>               <span class="at">maximum_deviation =</span> <span class="fu">unname</span>(test[<span class="st">"deviation"</span>]), <span class="at">p =</span> <span class="fu">unname</span>(test[<span class="st">"p"</span>]))</span>
<span id="cb44-19"><a href="#cb44-19" aria-hidden="true" tabindex="-1"></a>  }))))</span>
<span id="cb44-20"><a href="#cb44-20" aria-hidden="true" tabindex="-1"></a>test_results<span class="sc">$</span>p_holm <span class="ot">&lt;-</span> <span class="fu">p.adjust</span>(test_results<span class="sc">$</span>p, <span class="at">method =</span> <span class="st">"holm"</span>)</span>
<span id="cb44-21"><a href="#cb44-21" aria-hidden="true" tabindex="-1"></a>test_results<span class="sc">$</span>decision_5pct <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(test_results<span class="sc">$</span>p_holm <span class="sc">&lt;=</span> <span class="fl">0.05</span>,</span>
<span id="cb44-22"><a href="#cb44-22" aria-hidden="true" tabindex="-1"></a>                                    <span class="st">"Reject conditional CSR"</span>, <span class="st">"Do not reject conditional CSR"</span>)</span>
<span id="cb44-23"><a href="#cb44-23" aria-hidden="true" tabindex="-1"></a>test_results</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>           area function_name maximum_deviation     p p_holm
1 CHOA CHU KANG             G      1.487001e-01 0.295  0.295
2 CHOA CHU KANG             F      7.742027e-02 0.040  0.120
3 CHOA CHU KANG             K      1.466084e+05 0.010  0.040
4 CHOA CHU KANG             L      4.489467e+01 0.125  0.250
5      TAMPINES             G      2.805708e-01 0.005  0.040
6      TAMPINES             F      2.825835e-01 0.005  0.040
7      TAMPINES             K      7.171651e+05 0.005  0.040
8      TAMPINES             L      1.941802e+02 0.005  0.040
                  decision_5pct
1 Do not reject conditional CSR
2 Do not reject conditional CSR
3        Reject conditional CSR
4 Do not reject conditional CSR
5        Reject conditional CSR
6        Reject conditional CSR
7        Reject conditional CSR
8        Reject conditional CSR</code></pre>
</div>
</div>
<p>After Holm adjustment, <strong>5 of the eight comparisons</strong> reject conditional CSR at 5%. The decision column is the formal summary. Failure to reject means the chosen diagnostic and distance range do not establish a departure; it does not prove that a pattern is random. Because G, F, K and L are correlated, these are not eight independent votes.</p>
<p>To connect the curves to numbers, I also report their values at a preselected <strong>250 m</strong> distance. This table describes effect direction; the pointwise bounds are not substituted for the global p-values above.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>distance_summary <span class="ot">&lt;-</span> <span class="fu">do.call</span>(rbind, <span class="fu">lapply</span>(<span class="fu">names</span>(envelopes), <span class="cf">function</span>(nm)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">do.call</span>(rbind, <span class="fu">lapply</span>(<span class="fu">names</span>(functions), <span class="cf">function</span>(fn) {</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>    e <span class="ot">&lt;-</span> envelopes[[nm]][[fn]]</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>    at <span class="ot">&lt;-</span> <span class="fu">which.min</span>(<span class="fu">abs</span>(e<span class="sc">$</span>r <span class="sc">-</span> <span class="dv">250</span>))</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">data.frame</span>(<span class="at">area =</span> nm, <span class="at">function_name =</span> fn, <span class="at">distance_m =</span> e<span class="sc">$</span>r[at],</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>               <span class="at">observed =</span> e<span class="sc">$</span>obs[at], <span class="at">CSR =</span> e<span class="sc">$</span>theo[at],</span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>               <span class="at">envelope_low =</span> e<span class="sc">$</span>lo[at], <span class="at">envelope_high =</span> e<span class="sc">$</span>hi[at])</span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>  }))))</span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a>distance_summary</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>           area function_name distance_m     observed          CSR envelope_low
1 CHOA CHU KANG             G        250 9.360480e-01 8.835775e-01 7.543427e-01
2 CHOA CHU KANG             F        250 8.086293e-01 8.835775e-01 8.104985e-01
3 CHOA CHU KANG             K        250 2.274072e+05 1.963495e+05 1.541013e+05
4 CHOA CHU KANG             L        250 2.690464e+02 2.500000e+02 2.214768e+02
5      TAMPINES             G        250 8.517829e-01 6.289451e-01 4.951311e-01
6      TAMPINES             F        250 5.018720e-01 6.289451e-01 5.798752e-01
7      TAMPINES             K        250 4.403853e+05 1.963495e+05 1.389060e+05
8      TAMPINES             L        250 3.744048e+02 2.500000e+02 2.102740e+02
  envelope_high
1  9.719023e-01
2  9.424743e-01
3  2.511338e+05
4  2.827337e+02
5  7.575023e-01
6  6.686147e-01
7  2.561935e+05
8  2.855677e+02</code></pre>
</div>
</div>
<p><strong>Choa Chu Kang:</strong> at 250 m, G is 0.936 (CSR 0.884), F is 0.809 (CSR 0.884), and L(r) − r is 19.0 m. The centred L value indicates more cumulative neighbours relative to the reference at this distance.</p>
<p><strong>Tampines:</strong> at 250 m, G is 0.852 (CSR 0.629), F is 0.502 (CSR 0.629), and L(r) − r is 124.4 m. The centred L value indicates more cumulative neighbours relative to the reference at this distance.</p>
</section>
<section id="sensitivity-to-co-located-records" class="level2">
<h2 class="anchored" data-anchor-id="sensitivity-to-co-located-records">9. Sensitivity to co-located records</h2>
<p>I repeat the L diagnostic with every original service record and a matching fixed-count CSR simulation. The main site-based result and this record-based result answer different questions. Their difference measures how much co-location affects apparent clustering.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">20260922</span>)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>sensitivity <span class="ot">&lt;-</span> <span class="fu">do.call</span>(rbind, <span class="fu">lapply</span>(<span class="fu">names</span>(patterns), <span class="cf">function</span>(nm) {</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>  record_pattern <span class="ot">&lt;-</span> area_patterns[[nm]]</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>  e <span class="ot">&lt;-</span> <span class="fu">envelope</span>(record_pattern, Lest, <span class="at">r =</span> distance_grid, <span class="at">correction =</span> <span class="st">"Ripley"</span>,</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">fix.n =</span> <span class="cn">TRUE</span>, <span class="at">nsim =</span> nsim, <span class="at">nrank =</span> <span class="dv">5</span>, <span class="at">use.theory =</span> <span class="cn">TRUE</span>,</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">savefuns =</span> <span class="cn">TRUE</span>, <span class="at">verbose =</span> <span class="cn">FALSE</span>)</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>  idx <span class="ot">&lt;-</span> <span class="fu">which.min</span>(<span class="fu">abs</span>(distance_grid <span class="sc">-</span> <span class="dv">250</span>))</span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">area =</span> nm, <span class="at">records =</span> <span class="fu">npoints</span>(record_pattern), <span class="at">sites =</span> <span class="fu">npoints</span>(patterns[[nm]]),</span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">L_minus_r_records_250m =</span> e<span class="sc">$</span>obs[idx] <span class="sc">-</span> e<span class="sc">$</span>r[idx],</span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">L_minus_r_sites_250m =</span> envelopes[[nm]]<span class="sc">$</span>L<span class="sc">$</span>obs[idx] <span class="sc">-</span> e<span class="sc">$</span>r[idx],</span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a>             <span class="at">records_global_p =</span> <span class="fu">unname</span>(<span class="fu">deviation_test</span>(e)[<span class="st">"p"</span>]))</span>
<span id="cb48-12"><a href="#cb48-12" aria-hidden="true" tabindex="-1"></a>}))</span>
<span id="cb48-13"><a href="#cb48-13" aria-hidden="true" tabindex="-1"></a>sensitivity</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>           area records sites L_minus_r_records_250m L_minus_r_sites_250m
1 CHOA CHU KANG      74    67               24.08712             19.04641
2      TAMPINES     117   105              173.22354            124.40483
  records_global_p
1            0.010
2            0.005</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dir.create</span>(<span class="st">"handson2B/data/derived"</span>, <span class="at">recursive =</span> <span class="cn">TRUE</span>, <span class="at">showWarnings =</span> <span class="cn">FALSE</span>)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(test_results, <span class="st">"handson2B/data/derived/csr-tests.csv"</span>, <span class="at">row.names =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Co-located records add zero-distance pairs. The table shows the resulting change in L(r) − r at 250 m instead of assuming that all apparent aggregation comes from this issue. These additional unadjusted sensitivity p-values are descriptive checks, separate from the predefined family of eight tests.</p>
</section>
<section id="what-i-learned-and-limitations" class="level2">
<h2 class="anchored" data-anchor-id="what-i-learned-and-limitations">10. What I learned and limitations</h2>
<p>Choosing the event unit came before choosing the function. Distinct childcare sites and individual service records produce different nearest-neighbour relationships, even though they appear almost identical on a national map. G and F also showed why starting at a service location and starting at an arbitrary piece of land are different perspectives.</p>
<p>The main limitation is the homogeneous reference. Childcare is unlikely to locate uniformly across industrial, residential and open land. Rejecting CSR does not separate this first-order heterogeneity from second-order interaction. An inhomogeneous model with population or land-use covariates would be a logical next step. Capacity, travel networks, historical boundary changes, coordinate precision and cross-boundary access are also outside this analysis.</p>
</section>
<section id="reproducibility-and-references" class="level2">
<h2 class="anchored" data-anchor-id="reproducibility-and-references">Reproducibility and references</h2>
<p>The executed sections are in <a href="R/analysis.R"><code>R/analysis.R</code></a>; shared input preparation is in <a href="../handson2A/R/prepare.R"><code>../handson2A/R/prepare.R</code></a>. Data sources and checksums are documented in <a href="../handson2A/data/README.md"><code>../handson2A/data/README.md</code></a>. Run <code>source("handson2A/R/download-data.R")</code> once and then <code>quarto render . --execute</code> from the repository root. Fixed seeds, 199 simulations, explicit corrections, and a declared distance grid make the Monte Carlo comparisons reproducible within the recorded software environment. The page fails if estimates are undefined on the requested grid.</p>
<p>References: <a href="https://r4gdsa.netlify.app/chap05.html">course Chapter 5</a>, <a href="https://spatstat.org/">spatstat</a>, and the <a href="https://search.r-project.org/CRAN/refmans/spatstat.explore/html/envelope.html">simulation-envelope documentation</a>. The latter distinguishes pointwise and simultaneous testing and documents <code>nrank</code>, <code>fix.n</code> and saved simulation functions.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>R version 4.5.3 (2026-03-11 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 11 x64 (build 26200)

Matrix products: default
  LAPACK version 3.12.1

locale:
[1] LC_COLLATE=English_United States.utf8 
[2] LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

time zone: Asia/Shanghai
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] tmap_4.4-1             terra_1.9-50           spatstat.explore_3.8-2
 [4] nlme_3.1-168           spatstat.random_3.5-1  spatstat.geom_3.8-3   
 [7] spatstat.univar_3.2-0  spatstat.data_3.1-9    dplyr_1.2.1           
[10] sf_1.1-3              

loaded via a namespace (and not attached):
 [1] xfun_0.60             raster_3.6-32         htmlwidgets_1.6.4    
 [4] spatstat.sparse_3.2-0 lattice_0.22-9        vctrs_0.7.3          
 [7] tools_4.5.3           crosstalk_1.2.2       spatstat.utils_3.2-5 
[10] generics_0.1.4        parallel_4.5.3        goftest_1.2-3        
[13] tibble_3.3.1          proxy_0.4-29          pkgconfig_2.0.3      
[16] Matrix_1.7-4          KernSmooth_2.23-26    data.table_1.18.6.1  
[19] leaflet_2.2.3         lifecycle_1.0.5       compiler_4.5.3       
[22] deldir_2.0-4          codetools_0.2-20      leafsync_0.1.0       
[25] leaflegend_1.2.8      stars_0.7-3           htmltools_0.5.9      
[28] class_7.3-23          yaml_2.3.12           pillar_1.11.1        
[31] classInt_0.4-11       lwgeom_0.2-17         wk_0.9.5             
[34] abind_1.4-8           tidyselect_1.2.1      digest_0.6.39        
[37] polyclip_1.10-7       fastmap_1.2.0         grid_4.5.3           
[40] colorspace_2.1-3      cli_3.6.6             logger_0.4.3         
[43] magrittr_2.0.5        maptiles_0.12.0       base64enc_0.1-6      
[46] XML_3.99-0.24         cols4all_0.10         leafem_0.2.5         
[49] e1071_1.7-17          tensor_1.5.1          sp_2.2-3             
[52] rmarkdown_2.31        otel_0.2.0            png_0.1-9            
[55] evaluate_1.0.5        knitr_1.51            tmaptools_3.3        
[58] s2_1.1.12             rlang_1.3.0           Rcpp_1.1.2           
[61] glue_1.8.1            DBI_1.3.0             jsonlite_2.0.0       
[64] R6_2.6.1              spacesXYZ_1.6-0       units_1.0-1          </code></pre>
</div>
</div>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const cellDetails = window.document.querySelectorAll(".cell details.code-fold");
        for (let i=0; i<cellDetails.length; i++) {
          const details = cellDetails[i];
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell div.sourceCode.cell-code");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb52" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Hands-on Exercise 2B"</span></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a><span class="an">subtitle:</span><span class="co"> "Second-order point patterns: G, F, K and L functions"</span></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Zhenhua Liu"</span></span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "2026-09-19"</span></span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a><span class="an">body-classes:</span><span class="co"> exercise-page</span></span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a><span class="an">toc:</span><span class="co"> true</span></span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a><span class="an">toc-location:</span><span class="co"> right</span></span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a><span class="an">code-fold:</span><span class="co"> false</span></span>
<span id="cb52-10"><a href="#cb52-10" aria-hidden="true" tabindex="-1"></a><span class="an">code-tools:</span><span class="co"> true</span></span>
<span id="cb52-11"><a href="#cb52-11" aria-hidden="true" tabindex="-1"></a><span class="an">execute:</span></span>
<span id="cb52-12"><a href="#cb52-12" aria-hidden="true" tabindex="-1"></a><span class="co">  freeze: false</span></span>
<span id="cb52-13"><a href="#cb52-13" aria-hidden="true" tabindex="-1"></a><span class="co">  echo: true</span></span>
<span id="cb52-14"><a href="#cb52-14" aria-hidden="true" tabindex="-1"></a><span class="co">  warning: true</span></span>
<span id="cb52-15"><a href="#cb52-15" aria-hidden="true" tabindex="-1"></a><span class="co">  message: false</span></span>
<span id="cb52-16"><a href="#cb52-16" aria-hidden="true" tabindex="-1"></a><span class="co">  error: false</span></span>
<span id="cb52-17"><a href="#cb52-17" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb52-18"><a href="#cb52-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-21"><a href="#cb52-21" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb52-22"><a href="#cb52-22" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: register-code</span></span>
<span id="cb52-23"><a href="#cb52-23" aria-hidden="true" tabindex="-1"></a><span class="co">#| include: false</span></span>
<span id="cb52-24"><a href="#cb52-24" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">read_chunk</span>(<span class="st">"handson2A/R/prepare.R"</span>)</span>
<span id="cb52-25"><a href="#cb52-25" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">read_chunk</span>(<span class="st">"handson2B/R/analysis.R"</span>)</span>
<span id="cb52-26"><a href="#cb52-26" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">fig.width =</span> <span class="dv">9</span>, <span class="at">fig.height =</span> <span class="dv">5</span>, <span class="at">dpi =</span> <span class="dv">150</span>)</span>
<span id="cb52-27"><a href="#cb52-27" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb52-28"><a href="#cb52-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-29"><a href="#cb52-29" aria-hidden="true" tabindex="-1"></a><span class="fu">## Overview</span></span>
<span id="cb52-30"><a href="#cb52-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-31"><a href="#cb52-31" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Exercise 2A</span><span class="co">](../handson2A/index.qmd)</span> mapped the intensity of childcare service</span>
<span id="cb52-32"><a href="#cb52-32" aria-hidden="true" tabindex="-1"></a>records. Here I ask a different question: how does the spacing of childcare</span>
<span id="cb52-33"><a href="#cb52-33" aria-hidden="true" tabindex="-1"></a>**locations** in Choa Chu Kang and Tampines compare with a uniform random</span>
<span id="cb52-34"><a href="#cb52-34" aria-hidden="true" tabindex="-1"></a>pattern inside the same planning boundaries?</span>
<span id="cb52-35"><a href="#cb52-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-36"><a href="#cb52-36" aria-hidden="true" tabindex="-1"></a>Following <span class="co">[</span><span class="ot">course Chapter 5</span><span class="co">](https://r4gdsa.netlify.app/chap05.html)</span>, I examine</span>
<span id="cb52-37"><a href="#cb52-37" aria-hidden="true" tabindex="-1"></a>G, F, K and L functions in that order, then compare observed curves with Monte</span>
<span id="cb52-38"><a href="#cb52-38" aria-hidden="true" tabindex="-1"></a>Carlo simulations. G and F describe nearest-neighbour and empty-space</span>
<span id="cb52-39"><a href="#cb52-39" aria-hidden="true" tabindex="-1"></a>distributions; K and L summarise cumulative interpoint relationships. These</span>
<span id="cb52-40"><a href="#cb52-40" aria-hidden="true" tabindex="-1"></a>descriptions can reveal departures from a reference model, but do not identify</span>
<span id="cb52-41"><a href="#cb52-41" aria-hidden="true" tabindex="-1"></a>the causal process that produced the locations.</span>
<span id="cb52-42"><a href="#cb52-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-43"><a href="#cb52-43" aria-hidden="true" tabindex="-1"></a><span class="fu">## 1. Setup and reproducible preparation</span></span>
<span id="cb52-44"><a href="#cb52-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-47"><a href="#cb52-47" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb52-48"><a href="#cb52-48" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: packages</span></span>
<span id="cb52-49"><a href="#cb52-49" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb52-50"><a href="#cb52-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-51"><a href="#cb52-51" aria-hidden="true" tabindex="-1"></a>I reuse the <span class="co">[</span><span class="ot">ECDA childcare snapshot</span><span class="co">](https://data.gov.sg/datasets/d_5d668e3f544335f8028f546827b773b4/view)</span></span>
<span id="cb52-52"><a href="#cb52-52" aria-hidden="true" tabindex="-1"></a>and <span class="co">[</span><span class="ot">MP2019 subzone boundary</span><span class="co">](https://data.gov.sg/datasets/d_8594ae9ff96d0c708bc2af633048edfb/view)</span></span>
<span id="cb52-53"><a href="#cb52-53" aria-hidden="true" tabindex="-1"></a>from 2A. The childcare layer describes **December 2021**, even though the portal</span>
<span id="cb52-54"><a href="#cb52-54" aria-hidden="true" tabindex="-1"></a>was updated in 2026. Reusing the input files makes the comparison temporally</span>
<span id="cb52-55"><a href="#cb52-55" aria-hidden="true" tabindex="-1"></a>consistent. It does not make the inventory current.</span>
<span id="cb52-56"><a href="#cb52-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-59"><a href="#cb52-59" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb52-60"><a href="#cb52-60" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: import</span></span>
<span id="cb52-61"><a href="#cb52-61" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb52-62"><a href="#cb52-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-65"><a href="#cb52-65" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb52-66"><a href="#cb52-66" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: prepare-window</span></span>
<span id="cb52-67"><a href="#cb52-67" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb52-68"><a href="#cb52-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-69"><a href="#cb52-69" aria-hidden="true" tabindex="-1"></a>The shared preparation transforms both layers to EPSG:3414, checks geometry and</span>
<span id="cb52-70"><a href="#cb52-70" aria-hidden="true" tabindex="-1"></a>exclusions, and constructs polygonal observation windows. This page executes</span>
<span id="cb52-71"><a href="#cb52-71" aria-hidden="true" tabindex="-1"></a>that preparation itself; it does not depend on objects left in an earlier R session.</span>
<span id="cb52-72"><a href="#cb52-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-75"><a href="#cb52-75" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb52-76"><a href="#cb52-76" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: planning-areas</span></span>
<span id="cb52-77"><a href="#cb52-77" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb52-78"><a href="#cb52-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-79"><a href="#cb52-79" aria-hidden="true" tabindex="-1"></a>::: {.callout-note title="Which events are being analysed?"}</span>
<span id="cb52-80"><a href="#cb52-80" aria-hidden="true" tabindex="-1"></a>Several childcare records share exactly the same coordinate. The principal</span>
<span id="cb52-81"><a href="#cb52-81" aria-hidden="true" tabindex="-1"></a>analysis here collapses these to distinct sites because a simple point-process</span>
<span id="cb52-82"><a href="#cb52-82" aria-hidden="true" tabindex="-1"></a>model assumes separate event locations. This is an explicit change of unit,</span>
<span id="cb52-83"><a href="#cb52-83" aria-hidden="true" tabindex="-1"></a>not a claim that the original records are erroneous. A final sensitivity analysis</span>
<span id="cb52-84"><a href="#cb52-84" aria-hidden="true" tabindex="-1"></a>restores every record. The record-based KDE in 2A remains unchanged.</span>
<span id="cb52-85"><a href="#cb52-85" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb52-86"><a href="#cb52-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-87"><a href="#cb52-87" aria-hidden="true" tabindex="-1"></a><span class="fu">## 2. Study windows and the random reference model</span></span>
<span id="cb52-88"><a href="#cb52-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-89"><a href="#cb52-89" aria-hidden="true" tabindex="-1"></a>Under the null model, the observed number of sites is fixed and each location is</span>
<span id="cb52-90"><a href="#cb52-90" aria-hidden="true" tabindex="-1"></a>independently uniform within its planning-area polygon. This is **conditional</span>
<span id="cb52-91"><a href="#cb52-91" aria-hidden="true" tabindex="-1"></a>complete spatial randomness (CSR)**. The alternative is departure from that</span>
<span id="cb52-92"><a href="#cb52-92" aria-hidden="true" tabindex="-1"></a>model in the selected distance range. Keeping the same boundary and count</span>
<span id="cb52-93"><a href="#cb52-93" aria-hidden="true" tabindex="-1"></a>avoids confounding location pattern with different totals or observation areas.</span>
<span id="cb52-94"><a href="#cb52-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-95"><a href="#cb52-95" aria-hidden="true" tabindex="-1"></a>I preselect **0–500 m** and 129 equally spaced distances for both areas, before</span>
<span id="cb52-96"><a href="#cb52-96" aria-hidden="true" tabindex="-1"></a>examining the curves. This focuses the comparison on neighbourhood-scale</span>
<span id="cb52-97"><a href="#cb52-97" aria-hidden="true" tabindex="-1"></a>spacing and avoids searching many distance ranges for a favourable result.</span>
<span id="cb52-98"><a href="#cb52-98" aria-hidden="true" tabindex="-1"></a>Distances are straight-line metres, not walking routes. A 500 m separation</span>
<span id="cb52-99"><a href="#cb52-99" aria-hidden="true" tabindex="-1"></a>therefore has no automatic interpretation as a service catchment.</span>
<span id="cb52-100"><a href="#cb52-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-103"><a href="#cb52-103" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb52-104"><a href="#cb52-104" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: second-order-setup</span></span>
<span id="cb52-105"><a href="#cb52-105" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb52-106"><a href="#cb52-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-109"><a href="#cb52-109" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb52-110"><a href="#cb52-110" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: area-map</span></span>
<span id="cb52-111"><a href="#cb52-111" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 6</span></span>
<span id="cb52-112"><a href="#cb52-112" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Distinct childcare sites and the actual observation windows. Each panel has its own map scale."</span></span>
<span id="cb52-113"><a href="#cb52-113" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-alt: "Maps of distinct childcare sites in Choa Chu Kang and Tampines."</span></span>
<span id="cb52-114"><a href="#cb52-114" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb52-115"><a href="#cb52-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-116"><a href="#cb52-116" aria-hidden="true" tabindex="-1"></a>The analysis uses **`r npoints(patterns[['CHOA CHU KANG']])` sites** in Choa Chu</span>
<span id="cb52-117"><a href="#cb52-117" aria-hidden="true" tabindex="-1"></a>Kang and **`r npoints(patterns[['TAMPINES']])` sites** in Tampines. Both polygons</span>
<span id="cb52-118"><a href="#cb52-118" aria-hidden="true" tabindex="-1"></a>include land that is not equally plausible for childcare facilities. Rejection</span>
<span id="cb52-119"><a href="#cb52-119" aria-hidden="true" tabindex="-1"></a>of this homogeneous model could reflect land use or population gradients,</span>
<span id="cb52-120"><a href="#cb52-120" aria-hidden="true" tabindex="-1"></a>as well as genuine interaction between providers.</span>
<span id="cb52-121"><a href="#cb52-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-122"><a href="#cb52-122" aria-hidden="true" tabindex="-1"></a><span class="fu">## 3. Simulation envelopes and edge correction</span></span>
<span id="cb52-123"><a href="#cb52-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-124"><a href="#cb52-124" aria-hidden="true" tabindex="-1"></a>Points near an observation boundary may have unobserved neighbours outside it.</span>
<span id="cb52-125"><a href="#cb52-125" aria-hidden="true" tabindex="-1"></a>For G and F, I use Kaplan–Meier correction to handle censored distances. For K</span>
<span id="cb52-126"><a href="#cb52-126" aria-hidden="true" tabindex="-1"></a>and L, I use Ripley's isotropic edge correction. I apply the same estimator to</span>
<span id="cb52-127"><a href="#cb52-127" aria-hidden="true" tabindex="-1"></a>the observed pattern and every simulation. For G I also display the course's</span>
<span id="cb52-128"><a href="#cb52-128" aria-hidden="true" tabindex="-1"></a>border estimator as a sensitivity comparison.</span>
<span id="cb52-129"><a href="#cb52-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-130"><a href="#cb52-130" aria-hidden="true" tabindex="-1"></a>The 199 simulated patterns in each area are reused across all four functions.</span>
<span id="cb52-131"><a href="#cb52-131" aria-hidden="true" tabindex="-1"></a>This makes differences between diagnostics easier to interpret because they</span>
<span id="cb52-132"><a href="#cb52-132" aria-hidden="true" tabindex="-1"></a>are not caused by unrelated simulation draws.</span>
<span id="cb52-133"><a href="#cb52-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-136"><a href="#cb52-136" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb52-137"><a href="#cb52-137" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: envelope-method</span></span>
<span id="cb52-138"><a href="#cb52-138" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb52-139"><a href="#cb52-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-140"><a href="#cb52-140" aria-hidden="true" tabindex="-1"></a>::: {.callout-important title="An envelope is not automatically a global test"}</span>
<span id="cb52-141"><a href="#cb52-141" aria-hidden="true" tabindex="-1"></a>These plots show **95% pointwise** envelopes: with 199 simulations and</span>
<span id="cb52-142"><a href="#cb52-142" aria-hidden="true" tabindex="-1"></a><span class="in">`nrank = 5`</span>, the two-sided level at one preselected distance is</span>
<span id="cb52-143"><a href="#cb52-143" aria-hidden="true" tabindex="-1"></a>2 × 5 / 200 = 0.05. Scanning the whole curve for any crossing changes that</span>
<span id="cb52-144"><a href="#cb52-144" aria-hidden="true" tabindex="-1"></a>error rate. I therefore report a separate maximum-deviation Monte Carlo test</span>
<span id="cb52-145"><a href="#cb52-145" aria-hidden="true" tabindex="-1"></a>over the full 0–500 m interval and apply Holm adjustment across the eight</span>
<span id="cb52-146"><a href="#cb52-146" aria-hidden="true" tabindex="-1"></a>area/function comparisons.</span>
<span id="cb52-147"><a href="#cb52-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-148"><a href="#cb52-148" aria-hidden="true" tabindex="-1"></a>The course's 99-simulation, rank-one pointwise envelope has level 0.02 at a</span>
<span id="cb52-149"><a href="#cb52-149" aria-hidden="true" tabindex="-1"></a>single distance, not 0.001. Our 199-simulation Monte Carlo p-value has resolution</span>
<span id="cb52-150"><a href="#cb52-150" aria-hidden="true" tabindex="-1"></a>0.005 and cannot support a claim of p <span class="dv">&amp;lt;</span> 0.001. I use a stated 5% threshold</span>
<span id="cb52-151"><a href="#cb52-151" aria-hidden="true" tabindex="-1"></a>rather than repeating that mismatch.</span>
<span id="cb52-152"><a href="#cb52-152" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb52-153"><a href="#cb52-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-156"><a href="#cb52-156" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb52-157"><a href="#cb52-157" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: plot-helper</span></span>
<span id="cb52-158"><a href="#cb52-158" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: true</span></span>
<span id="cb52-159"><a href="#cb52-159" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb52-160"><a href="#cb52-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-161"><a href="#cb52-161" aria-hidden="true" tabindex="-1"></a><span class="fu">## 4. G: distance from one site to its nearest neighbour</span></span>
<span id="cb52-162"><a href="#cb52-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-163"><a href="#cb52-163" aria-hidden="true" tabindex="-1"></a>G(r) is the probability that a typical site has another site within r metres.</span>
<span id="cb52-164"><a href="#cb52-164" aria-hidden="true" tabindex="-1"></a>Under homogeneous Poisson CSR its reference curve is</span>
<span id="cb52-165"><a href="#cb52-165" aria-hidden="true" tabindex="-1"></a>$G_0(r)=1-\exp(-\lambda\pi r^2)$, where $\lambda$ is sites per square metre.</span>
<span id="cb52-166"><a href="#cb52-166" aria-hidden="true" tabindex="-1"></a>An observed curve above the reference indicates more short nearest-neighbour</span>
<span id="cb52-167"><a href="#cb52-167" aria-hidden="true" tabindex="-1"></a>distances; below it indicates fewer. This direction describes spacing, not</span>
<span id="cb52-168"><a href="#cb52-168" aria-hidden="true" tabindex="-1"></a>proof that operators attract or repel one another.</span>
<span id="cb52-169"><a href="#cb52-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-172"><a href="#cb52-172" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb52-173"><a href="#cb52-173" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: g-function</span></span>
<span id="cb52-174"><a href="#cb52-174" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "G-function estimates and 95% pointwise simulation envelopes, using Kaplan–Meier correction."</span></span>
<span id="cb52-175"><a href="#cb52-175" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-alt: "Nearest-neighbour distribution curves for Choa Chu Kang and Tampines against CSR envelopes."</span></span>
<span id="cb52-176"><a href="#cb52-176" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb52-177"><a href="#cb52-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-178"><a href="#cb52-178" aria-hidden="true" tabindex="-1"></a>The border-versus-Kaplan–Meier table is a reminder that edge treatment changes</span>
<span id="cb52-179"><a href="#cb52-179" aria-hidden="true" tabindex="-1"></a>the estimate, especially when many nearest-neighbour distances are censored.</span>
<span id="cb52-180"><a href="#cb52-180" aria-hidden="true" tabindex="-1"></a>The simulation plots use Kaplan–Meier consistently in both areas. A steep early</span>
<span id="cb52-181"><a href="#cb52-181" aria-hidden="true" tabindex="-1"></a>rise means many sites already have a close neighbour; levelling near one leaves</span>
<span id="cb52-182"><a href="#cb52-182" aria-hidden="true" tabindex="-1"></a>little additional information at larger distances.</span>
<span id="cb52-183"><a href="#cb52-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-184"><a href="#cb52-184" aria-hidden="true" tabindex="-1"></a><span class="fu">## 5. F: distance from empty space to a site</span></span>
<span id="cb52-185"><a href="#cb52-185" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-186"><a href="#cb52-186" aria-hidden="true" tabindex="-1"></a>F(r) starts at an arbitrary location in the study window and measures the</span>
<span id="cb52-187"><a href="#cb52-187" aria-hidden="true" tabindex="-1"></a>distance to the nearest site. A low F relative to CSR means more empty space</span>
<span id="cb52-188"><a href="#cb52-188" aria-hidden="true" tabindex="-1"></a>far from a site. Clusters can therefore produce a high G but a low F: sites</span>
<span id="cb52-189"><a href="#cb52-189" aria-hidden="true" tabindex="-1"></a>have close neighbours while the gaps between clusters remain large.</span>
<span id="cb52-190"><a href="#cb52-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-193"><a href="#cb52-193" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb52-194"><a href="#cb52-194" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: f-function</span></span>
<span id="cb52-195"><a href="#cb52-195" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Empty-space functions with Kaplan–Meier correction and 95% pointwise envelopes."</span></span>
<span id="cb52-196"><a href="#cb52-196" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-alt: "Empty-space distribution curves for the two planning areas."</span></span>
<span id="cb52-197"><a href="#cb52-197" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb52-198"><a href="#cb52-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-199"><a href="#cb52-199" aria-hidden="true" tabindex="-1"></a>Unlike G, F gives weight to the whole polygon rather than starting at the</span>
<span id="cb52-200"><a href="#cb52-200" aria-hidden="true" tabindex="-1"></a>observed childcare sites. Low-density industrial or open areas can therefore</span>
<span id="cb52-201"><a href="#cb52-201" aria-hidden="true" tabindex="-1"></a>strongly affect this diagnostic. The raster approximation used internally by</span>
<span id="cb52-202"><a href="#cb52-202" aria-hidden="true" tabindex="-1"></a><span class="in">`Fest()`</span> and the finite number of sites also limit precision. I do not interpret</span>
<span id="cb52-203"><a href="#cb52-203" aria-hidden="true" tabindex="-1"></a>F as the proportion of residents who can access childcare.</span>
<span id="cb52-204"><a href="#cb52-204" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-205"><a href="#cb52-205" aria-hidden="true" tabindex="-1"></a><span class="fu">## 6. K: cumulative neighbours across distance</span></span>
<span id="cb52-206"><a href="#cb52-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-207"><a href="#cb52-207" aria-hidden="true" tabindex="-1"></a>K(r) is the expected number of other events within r of a typical event,</span>
<span id="cb52-208"><a href="#cb52-208" aria-hidden="true" tabindex="-1"></a>normalised by intensity. Its CSR reference is $\pi r^2$ and its units here are</span>
<span id="cb52-209"><a href="#cb52-209" aria-hidden="true" tabindex="-1"></a>square metres. Values above the reference indicate an excess of neighbours</span>
<span id="cb52-210"><a href="#cb52-210" aria-hidden="true" tabindex="-1"></a>within that distance. K is cumulative: an excess established at small distances</span>
<span id="cb52-211"><a href="#cb52-211" aria-hidden="true" tabindex="-1"></a>can remain visible at larger distances.</span>
<span id="cb52-212"><a href="#cb52-212" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-215"><a href="#cb52-215" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb52-216"><a href="#cb52-216" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: k-function</span></span>
<span id="cb52-217"><a href="#cb52-217" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Ripley-corrected K curves in m², with the CSR reference πr²."</span></span>
<span id="cb52-218"><a href="#cb52-218" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-alt: "Cumulative K-function curves with simulation envelopes in both areas."</span></span>
<span id="cb52-219"><a href="#cb52-219" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb52-220"><a href="#cb52-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-221"><a href="#cb52-221" aria-hidden="true" tabindex="-1"></a>I plot K directly rather than subtracting r. Subtracting metres from square</span>
<span id="cb52-222"><a href="#cb52-222" aria-hidden="true" tabindex="-1"></a>metres is dimensionally inconsistent and does not centre the CSR expectation</span>
<span id="cb52-223"><a href="#cb52-223" aria-hidden="true" tabindex="-1"></a>at zero. The transformed L function below provides the appropriate centred</span>
<span id="cb52-224"><a href="#cb52-224" aria-hidden="true" tabindex="-1"></a>view in metre units.</span>
<span id="cb52-225"><a href="#cb52-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-226"><a href="#cb52-226" aria-hidden="true" tabindex="-1"></a><span class="fu">## 7. L: a centred comparison with randomness</span></span>
<span id="cb52-227"><a href="#cb52-227" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-228"><a href="#cb52-228" aria-hidden="true" tabindex="-1"></a>The transformation $L(r)=\sqrt{K(r)/\pi}$ has CSR reference r. Consequently,</span>
<span id="cb52-229"><a href="#cb52-229" aria-hidden="true" tabindex="-1"></a>**L(r) − r** has a zero reference: positive values indicate excess cumulative</span>
<span id="cb52-230"><a href="#cb52-230" aria-hidden="true" tabindex="-1"></a>neighbours and negative values indicate fewer. L repackages K for easier</span>
<span id="cb52-231"><a href="#cb52-231" aria-hidden="true" tabindex="-1"></a>reading; it is not an independent source of evidence.</span>
<span id="cb52-232"><a href="#cb52-232" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-235"><a href="#cb52-235" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb52-236"><a href="#cb52-236" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: l-function</span></span>
<span id="cb52-237"><a href="#cb52-237" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Centred L curves; zero is the homogeneous CSR reference. Shading is pointwise, not a simultaneous band."</span></span>
<span id="cb52-238"><a href="#cb52-238" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-alt: "Centred L-function curves for Choa Chu Kang and Tampines."</span></span>
<span id="cb52-239"><a href="#cb52-239" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb52-240"><a href="#cb52-240" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-241"><a href="#cb52-241" aria-hidden="true" tabindex="-1"></a>The height of L(r) − r is an effect-size description in metres, not a p-value.</span>
<span id="cb52-242"><a href="#cb52-242" aria-hidden="true" tabindex="-1"></a>I examine its direction alongside the explicit simulation results below,</span>
<span id="cb52-243"><a href="#cb52-243" aria-hidden="true" tabindex="-1"></a>rather than declaring significance from a visually prominent peak.</span>
<span id="cb52-244"><a href="#cb52-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-245"><a href="#cb52-245" aria-hidden="true" tabindex="-1"></a><span class="fu">## 8. Global comparison and numerical interpretation</span></span>
<span id="cb52-246"><a href="#cb52-246" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-247"><a href="#cb52-247" aria-hidden="true" tabindex="-1"></a>For each observed or simulated curve, I compute a single maximum absolute</span>
<span id="cb52-248"><a href="#cb52-248" aria-hidden="true" tabindex="-1"></a>deviation from the same CSR reference across the preselected distance grid.</span>
<span id="cb52-249"><a href="#cb52-249" aria-hidden="true" tabindex="-1"></a>The Monte Carlo p-value is $(1+b)/(1+199)$, where b is the number of simulated</span>
<span id="cb52-250"><a href="#cb52-250" aria-hidden="true" tabindex="-1"></a>deviations at least as large as the observed one. Counting ties as exceedances</span>
<span id="cb52-251"><a href="#cb52-251" aria-hidden="true" tabindex="-1"></a>is conservative. The reference is fixed by the area's count, geometry and</span>
<span id="cb52-252"><a href="#cb52-252" aria-hidden="true" tabindex="-1"></a>distance grid, so it is applied identically to all realisations.</span>
<span id="cb52-253"><a href="#cb52-253" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-256"><a href="#cb52-256" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb52-257"><a href="#cb52-257" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: global-tests</span></span>
<span id="cb52-258"><a href="#cb52-258" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb52-259"><a href="#cb52-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-260"><a href="#cb52-260" aria-hidden="true" tabindex="-1"></a>After Holm adjustment, **<span class="in">`r sum(test_results$p_holm &lt;= 0.05)`</span> of the eight</span>
<span id="cb52-261"><a href="#cb52-261" aria-hidden="true" tabindex="-1"></a>comparisons** reject conditional CSR at 5%. The decision column is the formal</span>
<span id="cb52-262"><a href="#cb52-262" aria-hidden="true" tabindex="-1"></a>summary. Failure to reject means the chosen diagnostic and distance range do</span>
<span id="cb52-263"><a href="#cb52-263" aria-hidden="true" tabindex="-1"></a>not establish a departure; it does not prove that a pattern is random.</span>
<span id="cb52-264"><a href="#cb52-264" aria-hidden="true" tabindex="-1"></a>Because G, F, K and L are correlated, these are not eight independent votes.</span>
<span id="cb52-265"><a href="#cb52-265" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-266"><a href="#cb52-266" aria-hidden="true" tabindex="-1"></a>To connect the curves to numbers, I also report their values at a preselected</span>
<span id="cb52-267"><a href="#cb52-267" aria-hidden="true" tabindex="-1"></a>**250 m** distance. This table describes effect direction; the pointwise bounds</span>
<span id="cb52-268"><a href="#cb52-268" aria-hidden="true" tabindex="-1"></a>are not substituted for the global p-values above.</span>
<span id="cb52-269"><a href="#cb52-269" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-272"><a href="#cb52-272" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb52-273"><a href="#cb52-273" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: distance-summary</span></span>
<span id="cb52-274"><a href="#cb52-274" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb52-275"><a href="#cb52-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-278"><a href="#cb52-278" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb52-279"><a href="#cb52-279" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: computed-interpretation</span></span>
<span id="cb52-280"><a href="#cb52-280" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb52-281"><a href="#cb52-281" aria-hidden="true" tabindex="-1"></a><span class="co">#| results: asis</span></span>
<span id="cb52-282"><a href="#cb52-282" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (nm <span class="cf">in</span> <span class="fu">names</span>(envelopes)) {</span>
<span id="cb52-283"><a href="#cb52-283" aria-hidden="true" tabindex="-1"></a>  e <span class="ot">&lt;-</span> envelopes[[nm]]</span>
<span id="cb52-284"><a href="#cb52-284" aria-hidden="true" tabindex="-1"></a>  j <span class="ot">&lt;-</span> <span class="fu">which.min</span>(<span class="fu">abs</span>(e<span class="sc">$</span>L<span class="sc">$</span>r <span class="sc">-</span> <span class="dv">250</span>))</span>
<span id="cb52-285"><a href="#cb52-285" aria-hidden="true" tabindex="-1"></a>  delta <span class="ot">&lt;-</span> e<span class="sc">$</span>L<span class="sc">$</span>obs[j] <span class="sc">-</span> e<span class="sc">$</span>L<span class="sc">$</span>r[j]</span>
<span id="cb52-286"><a href="#cb52-286" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"**%s:** at 250 m, G is %.3f (CSR %.3f), F is %.3f (CSR %.3f), and L(r) − r is %.1f m. The centred L value indicates %s cumulative neighbours relative to the reference at this distance.</span><span class="sc">\n\n</span><span class="st">"</span>,</span>
<span id="cb52-287"><a href="#cb52-287" aria-hidden="true" tabindex="-1"></a>    tools<span class="sc">::</span><span class="fu">toTitleCase</span>(<span class="fu">tolower</span>(nm)), e<span class="sc">$</span>G<span class="sc">$</span>obs[j], e<span class="sc">$</span>G<span class="sc">$</span>theo[j], e<span class="sc">$</span>F<span class="sc">$</span>obs[j],</span>
<span id="cb52-288"><a href="#cb52-288" aria-hidden="true" tabindex="-1"></a>    e<span class="sc">$</span>F<span class="sc">$</span>theo[j], delta, <span class="cf">if</span> (delta <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="st">"more"</span> <span class="cf">else</span> <span class="st">"fewer"</span>))</span>
<span id="cb52-289"><a href="#cb52-289" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb52-290"><a href="#cb52-290" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb52-291"><a href="#cb52-291" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-292"><a href="#cb52-292" aria-hidden="true" tabindex="-1"></a><span class="fu">## 9. Sensitivity to co-located records</span></span>
<span id="cb52-293"><a href="#cb52-293" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-294"><a href="#cb52-294" aria-hidden="true" tabindex="-1"></a>I repeat the L diagnostic with every original service record and a matching</span>
<span id="cb52-295"><a href="#cb52-295" aria-hidden="true" tabindex="-1"></a>fixed-count CSR simulation. The main site-based result and this record-based</span>
<span id="cb52-296"><a href="#cb52-296" aria-hidden="true" tabindex="-1"></a>result answer different questions. Their difference measures how much</span>
<span id="cb52-297"><a href="#cb52-297" aria-hidden="true" tabindex="-1"></a>co-location affects apparent clustering.</span>
<span id="cb52-298"><a href="#cb52-298" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-301"><a href="#cb52-301" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb52-302"><a href="#cb52-302" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: duplicate-sensitivity</span></span>
<span id="cb52-303"><a href="#cb52-303" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb52-304"><a href="#cb52-304" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-305"><a href="#cb52-305" aria-hidden="true" tabindex="-1"></a>Co-located records add zero-distance pairs. The table shows the resulting</span>
<span id="cb52-306"><a href="#cb52-306" aria-hidden="true" tabindex="-1"></a>change in L(r) − r at 250 m instead of assuming that all apparent aggregation</span>
<span id="cb52-307"><a href="#cb52-307" aria-hidden="true" tabindex="-1"></a>comes from this issue. These additional unadjusted sensitivity p-values are</span>
<span id="cb52-308"><a href="#cb52-308" aria-hidden="true" tabindex="-1"></a>descriptive checks, separate from the predefined family of eight tests.</span>
<span id="cb52-309"><a href="#cb52-309" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-310"><a href="#cb52-310" aria-hidden="true" tabindex="-1"></a><span class="fu">## 10. What I learned and limitations</span></span>
<span id="cb52-311"><a href="#cb52-311" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-312"><a href="#cb52-312" aria-hidden="true" tabindex="-1"></a>Choosing the event unit came before choosing the function. Distinct childcare</span>
<span id="cb52-313"><a href="#cb52-313" aria-hidden="true" tabindex="-1"></a>sites and individual service records produce different nearest-neighbour</span>
<span id="cb52-314"><a href="#cb52-314" aria-hidden="true" tabindex="-1"></a>relationships, even though they appear almost identical on a national map.</span>
<span id="cb52-315"><a href="#cb52-315" aria-hidden="true" tabindex="-1"></a>G and F also showed why starting at a service location and starting at an</span>
<span id="cb52-316"><a href="#cb52-316" aria-hidden="true" tabindex="-1"></a>arbitrary piece of land are different perspectives.</span>
<span id="cb52-317"><a href="#cb52-317" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-318"><a href="#cb52-318" aria-hidden="true" tabindex="-1"></a>The main limitation is the homogeneous reference. Childcare is unlikely to</span>
<span id="cb52-319"><a href="#cb52-319" aria-hidden="true" tabindex="-1"></a>locate uniformly across industrial, residential and open land. Rejecting CSR</span>
<span id="cb52-320"><a href="#cb52-320" aria-hidden="true" tabindex="-1"></a>does not separate this first-order heterogeneity from second-order interaction.</span>
<span id="cb52-321"><a href="#cb52-321" aria-hidden="true" tabindex="-1"></a>An inhomogeneous model with population or land-use covariates would be a</span>
<span id="cb52-322"><a href="#cb52-322" aria-hidden="true" tabindex="-1"></a>logical next step. Capacity, travel networks, historical boundary changes,</span>
<span id="cb52-323"><a href="#cb52-323" aria-hidden="true" tabindex="-1"></a>coordinate precision and cross-boundary access are also outside this analysis.</span>
<span id="cb52-324"><a href="#cb52-324" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-325"><a href="#cb52-325" aria-hidden="true" tabindex="-1"></a><span class="fu">## Reproducibility and references</span></span>
<span id="cb52-326"><a href="#cb52-326" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-327"><a href="#cb52-327" aria-hidden="true" tabindex="-1"></a>The executed sections are in <span class="co">[</span><span class="ot">`R/analysis.R`</span><span class="co">](R/analysis.R)</span>; shared input</span>
<span id="cb52-328"><a href="#cb52-328" aria-hidden="true" tabindex="-1"></a>preparation is in <span class="co">[</span><span class="ot">`../handson2A/R/prepare.R`</span><span class="co">](../handson2A/R/prepare.R)</span>.</span>
<span id="cb52-329"><a href="#cb52-329" aria-hidden="true" tabindex="-1"></a>Data sources and checksums are documented in</span>
<span id="cb52-330"><a href="#cb52-330" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">`../handson2A/data/README.md`</span><span class="co">](../handson2A/data/README.md)</span>.</span>
<span id="cb52-331"><a href="#cb52-331" aria-hidden="true" tabindex="-1"></a>Run <span class="in">`source("handson2A/R/download-data.R")`</span> once and then</span>
<span id="cb52-332"><a href="#cb52-332" aria-hidden="true" tabindex="-1"></a><span class="in">`quarto render . --execute`</span> from the repository root. Fixed seeds, 199</span>
<span id="cb52-333"><a href="#cb52-333" aria-hidden="true" tabindex="-1"></a>simulations, explicit corrections, and a declared distance grid make the</span>
<span id="cb52-334"><a href="#cb52-334" aria-hidden="true" tabindex="-1"></a>Monte Carlo comparisons reproducible within the recorded software environment.</span>
<span id="cb52-335"><a href="#cb52-335" aria-hidden="true" tabindex="-1"></a>The page fails if estimates are undefined on the requested grid.</span>
<span id="cb52-336"><a href="#cb52-336" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-337"><a href="#cb52-337" aria-hidden="true" tabindex="-1"></a>References: <span class="co">[</span><span class="ot">course Chapter 5</span><span class="co">](https://r4gdsa.netlify.app/chap05.html)</span>,</span>
<span id="cb52-338"><a href="#cb52-338" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">spatstat</span><span class="co">](https://spatstat.org/)</span>, and the</span>
<span id="cb52-339"><a href="#cb52-339" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">simulation-envelope documentation</span><span class="co">](https://search.r-project.org/CRAN/refmans/spatstat.explore/html/envelope.html)</span>.</span>
<span id="cb52-340"><a href="#cb52-340" aria-hidden="true" tabindex="-1"></a>The latter distinguishes pointwise and simultaneous testing and documents</span>
<span id="cb52-341"><a href="#cb52-341" aria-hidden="true" tabindex="-1"></a><span class="in">`nrank`</span>, <span class="in">`fix.n`</span> and saved simulation functions.</span>
<span id="cb52-342"><a href="#cb52-342" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-345"><a href="#cb52-345" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb52-346"><a href="#cb52-346" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: session-info</span></span>
<span id="cb52-347"><a href="#cb52-347" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb52-348"><a href="#cb52-348" aria-hidden="true" tabindex="-1"></a><span class="fu">sessionInfo</span>()</span>
<span id="cb52-349"><a href="#cb52-349" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>