{
  "hash": "c9da6490013bb31d6e591b88b46f10ea",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"in-class6\"\nsubtitle: \"Emerging Hot Spot Analysis · Hunan GDP per capita, 2005–2021\"\nauthor: \"Zhenhua Liu\"\ndate: \"2026-10-03\"\nbody-classes: exercise-page\ntoc: true\ntoc-location: right\ncode-tools: true\nexecute:\n  freeze: auto\n  error: false\n---\n\n\n\n## 1. Question and packages\n\nHow has the geography of high and low GDP per capita clustering changed across Hunan? This exercise follows [Chapter 11: Emerging Hot Spot Analysis](https://r4gdsa.netlify.app/chap11#the-data): build a space-time cube, calculate annual local statistics, test their trends, and map emerging hot spot classes. The inputs are the actual Hunan datasets supplied for this coursework.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(sf)\nlibrary(sfdep)\nlibrary(tmap)\nlibrary(dplyr)\nlibrary(tidyr)\nlibrary(readr)\nlibrary(ggplot2)\nlibrary(Kendall)\nlibrary(plotly)\nlibrary(knitr)\nspdep::set.coresOption(NULL)\ntmap_mode(\"plot\")\noptions(scipen = 5)\ntheme_set(theme_minimal(base_size = 12) +\n  theme(plot.background = element_rect(fill = \"#faf7f0\", colour = NA),\n        panel.grid.minor = element_blank(),\n        plot.title = element_text(colour = \"#8f3f2d\", face = \"bold\")))\n```\n:::\n\n\nI use a fixed random seed of **1234** and one worker. The annual calculation uses 499 permutations; the main EHSA calculation retains the chapter's **99 simulations**. A separate 999-simulation run checks how stable the resulting classes are.\n\n## 2. Import and validate the data\n\nThe county polygons are shared with [Hands-on Exercise 5A](../handson4A/index.qmd). The time series is **Hunan_GDPPC.csv**, rather than the single-year Hunan_2012.csv used previously. I transform the polygons to **WGS 84 / UTM zone 50N (EPSG:32650)**, with distances in metres, and order counties before constructing the cube.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan <- st_read(\"handson4/data/geospatial\", layer = \"Hunan\", quiet = TRUE) |>\n  st_transform(32650) |>\n  arrange(County)\nGDPPC <- read_csv(\"in-class6/data/aspatial/Hunan_GDPPC.csv\",\n  col_types = cols(Year = col_integer(), County = col_character(),\n                   GDPPC = col_double()))\nyears <- sort(unique(GDPPC$Year))\nstopifnot(nrow(hunan) == 88L, !anyDuplicated(hunan$County),\n  !anyDuplicated(GDPPC[c(\"County\", \"Year\")]),\n  setequal(hunan$County, GDPPC$County), identical(years, 2005:2021),\n  nrow(GDPPC) == nrow(hunan) * length(years),\n  !anyNA(GDPPC), all(is.finite(GDPPC$GDPPC)), all(GDPPC$GDPPC > 0),\n  all(st_is_valid(hunan)), st_crs(hunan)$epsg == 32650)\nkable(head(GDPPC), caption = \"Actual Hunan GDP per capita observations\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Actual Hunan GDP per capita observations\n\n| Year|County    | GDPPC|\n|----:|:---------|-----:|\n| 2005|Longshan  |  3469|\n| 2005|Changsha  | 24612|\n| 2005|Wangcheng | 14659|\n| 2005|Ningxiang | 11687|\n| 2005|Liuyang   | 13406|\n| 2005|Zhuzhou   |  8546|\n\n\n:::\n:::\n\n\nValidation checks unique county–year keys, matching county names, positive finite values, valid polygons, and a complete annual sequence. No observations are imputed or invented. The supplied boundaries are treated as fixed across years; the CSV does not document an inflation adjustment, so I do not treat the values as inflation-adjusted income.\n\n## 3. Create the space-time cube\n\n\n::: {.cell}\n\n```{.r .cell-code}\nGDPPC_st <- spacetime(GDPPC, hunan, .loc_col = \"County\", .time_col = \"Year\")\nstopifnot(is_spacetime_cube(GDPPC_st))\nis_spacetime_cube(GDPPC_st)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code}\ncube_summary <- tibble(Counties = nrow(hunan), Years = length(years),\n                      First_year = min(years), Last_year = max(years),\n                      Observations = nrow(GDPPC))\nkable(cube_summary, caption = \"Validated, complete space-time cube\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Validated, complete space-time cube\n\n| Counties| Years| First_year| Last_year| Observations|\n|--------:|-----:|----------:|---------:|------------:|\n|       88|    17|       2005|      2021|         1496|\n\n\n:::\n:::\n\n\nThe cube contains **88 counties × 17 years = 1,496 observations**. Each county has one record for every year from 2005 to 2021. `is_spacetime_cube()` returns TRUE.\n\n## 4. Spatial neighbours and annual Gi* calculation\n\nThe first calculation reproduces the chapter's Queen-contiguity neighbour lists and inverse-distance weights. Queen neighbours share an edge or a vertex. After attaching neighbours and weights, I preserve their alignment with the polygon row order within every year.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nGDPPC_nb <- GDPPC_st |>\n  activate(\"geometry\") |>\n  mutate(nb = include_self(st_contiguity(geometry)),\n         wt = st_inverse_distance(nb, geometry, scale = 1, alpha = 1),\n         .before = 1) |>\n  set_nbs(\"nb\") |>\n  set_wts(\"wt\")\ngeo_nb <- attr(GDPPC_nb, \"geometry\")$nb\ngeo_wt <- attr(GDPPC_nb, \"geometry\")$wt\nstopifnot(all(vapply(geo_wt, function(w) all(is.finite(w)), logical(1))),\n  all(vapply(seq_along(geo_nb), function(i) {\n    geo_wt[[i]][match(i, geo_nb[[i]])] == 0\n  }, logical(1))))\nsummary(geo_nb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 536 \nPercentage nonzero weights: 6.921488 \nAverage number of links: 6.090909 \nLink number distribution:\n\n 2  3  4  5  6  7  8  9 10 12 \n 2  2 12 16 24 14 11  4  2  1 \n2 least connected regions:\n41 72 with 2 links\n1 most connected region:\n64 with 12 links\n```\n\n\n:::\n:::\n\n\n::: {.callout-note}\n### Reading the two analyses correctly\n\nThe installed `sfdep` inverse-distance function uses polygon points on surface and assigns **zero weight to zero distances**, including the focal county. I retain that behaviour for the chapter's annual diagnostic. It therefore has a zero diagonal despite using `local_gstar_perm()`.\n\nThe later EHSA call receives the original cube and constructs its own **row-standardised Queen weights including the focal county**, plus a one-year lag. The annual diagnostic and the full EHSA result use different neighbourhood definitions and should be interpreted separately.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\ngi_stars <- GDPPC_nb |>\n  group_by(Year) |>\n  mutate(gi_star = local_gstar_perm(GDPPC, nb, wt, nsim = 499,\n                                   alternative = \"two.sided\", iseed = 1234)) |>\n  unnest(gi_star) |>\n  ungroup()\nstopifnot(nrow(gi_stars) == nrow(GDPPC), all(is.finite(gi_stars$gi_star)))\nkable(gi_stars |> select(County, Year, GDPPC, gi_star, p_sim) |> head(),\n      digits = 4, caption = \"Annual local statistics; unadjusted permutation p-values\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Annual local statistics; unadjusted permutation p-values\n\n|County    | Year| GDPPC| gi_star| p_sim|\n|:---------|----:|-----:|-------:|-----:|\n|Anhua     | 2005|  4411| -1.1495| 0.636|\n|Anren     | 2005|  7423|  1.6667| 0.124|\n|Anxiang   | 2005|  8184|  0.3981| 0.668|\n|Baojing   | 2005|  4612| -1.4449| 0.312|\n|Chaling   | 2005|  8040|  0.5670| 0.576|\n|Changning | 2005|  7906|  0.5501| 0.484|\n\n\n:::\n:::\n\n\nThese scores describe clustering relative to the other counties in each year. A change in a clustering score is different from a change in a county's raw GDPPC. The displayed annual permutation p-values are unadjusted.\n\n## 5. Changsha's local clustering trend\n\n### Static time series\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncbg <- gi_stars |>\n  filter(County == \"Changsha\") |>\n  arrange(Year) |>\n  select(County, Year, gi_star)\nchangsha_plot <- ggplot(cbg, aes(Year, gi_star)) +\n  geom_line(colour = \"#9a432e\", linewidth = 0.9) +\n  geom_point(colour = \"#9a432e\", size = 2) +\n  scale_x_continuous(breaks = seq(2005, 2021, 2)) +\n  labs(title = \"Changsha: annual local clustering statistic\",\n       x = \"Year\", y = \"Local Gi* score (guide's inverse-distance weights)\")\nchangsha_plot\n```\n\n::: {.cell-output-display}\n![Changsha's annual local score under the chapter's inverse-distance specification.](index_files/figure-html/c6-changsha-1.png){width=1600}\n:::\n:::\n\n\n### Interactive time series\n\nHover over the points to inspect each year. Use the chart toolbar to zoom or reset the view.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplotly(changsha_plot, tooltip = c(\"x\", \"y\")) |>\n  layout(paper_bgcolor = \"#faf7f0\", plot_bgcolor = \"#faf7f0\") |>\n  config(displaylogo = FALSE, responsive = TRUE)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-58b471fb514b0e5e771d\" style=\"width:100%;height:390px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-58b471fb514b0e5e771d\">{\"x\":{\"data\":[{\"x\":[2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021],\"y\":[5.0282995066289047,5.1692011079782345,5.2958892892912894,5.6039537096873993,6.2788862246004742,5.9357455762937326,5.7508709054298892,5.6942475830114576,5.7085054237054784,5.7608121561733521,6.097127241257188,6.0036547779673146,6.2028053540357906,6.0371816202738318,6.5794321718855278,5.7669155664195504,5.7486534794156494],\"text\":[\"Year: 2005<br />gi_star: 5.028300\",\"Year: 2006<br />gi_star: 5.169201\",\"Year: 2007<br />gi_star: 5.295889\",\"Year: 2008<br />gi_star: 5.603954\",\"Year: 2009<br />gi_star: 6.278886\",\"Year: 2010<br />gi_star: 5.935746\",\"Year: 2011<br />gi_star: 5.750871\",\"Year: 2012<br />gi_star: 5.694248\",\"Year: 2013<br />gi_star: 5.708505\",\"Year: 2014<br />gi_star: 5.760812\",\"Year: 2015<br />gi_star: 6.097127\",\"Year: 2016<br />gi_star: 6.003655\",\"Year: 2017<br />gi_star: 6.202805\",\"Year: 2018<br />gi_star: 6.037182\",\"Year: 2019<br />gi_star: 6.579432\",\"Year: 2020<br />gi_star: 5.766916\",\"Year: 2021<br />gi_star: 5.748653\"],\"type\":\"scatter\",\"mode\":\"lines+markers\",\"line\":{\"width\":3.4015748031496069,\"color\":\"rgba(154,67,46,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(154,67,46,1)\",\"opacity\":1,\"size\":7.559055118110237,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(154,67,46,1)\"}},\"frame\":null}],\"layout\":{\"margin\":{\"t\":43.098381070983812,\"r\":7.9701120797011216,\"b\":40.647571606475722,\"l\":47.023661270236623},\"paper_bgcolor\":\"#faf7f0\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":15.940224159402243},\"title\":{\"text\":\"<b> Changsha: annual local clustering statistic <\\/b>\",\"font\":{\"color\":\"rgba(143,63,45,1)\",\"family\":\"\",\"size\":19.128268991282692},\"x\":0,\"xref\":\"paper\"},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[2004.2,2021.8],\"tickmode\":\"array\",\"ticktext\":[\"2005\",\"2007\",\"2009\",\"2011\",\"2013\",\"2015\",\"2017\",\"2019\",\"2021\"],\"tickvals\":[2005,2007,2009,2011,2013,2015,2017,2019,2021],\"categoryorder\":\"array\",\"categoryarray\":[\"2005\",\"2007\",\"2009\",\"2011\",\"2013\",\"2015\",\"2017\",\"2019\",\"2021\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.9850560398505608,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":12.7521793275218},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.72455564360919278,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"Year\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":15.940224159402243}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[4.9507428733660737,6.6569888051483588],\"tickmode\":\"array\",\"ticktext\":[\"5.0\",\"5.5\",\"6.0\",\"6.5\"],\"tickvals\":[5,5.5,6,6.5],\"categoryorder\":\"array\",\"categoryarray\":[\"5.0\",\"5.5\",\"6.0\",\"6.5\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.9850560398505608,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":12.7521793275218},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0.72455564360919278,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"Local Gi* score (guide's inverse-distance weights)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":15.940224159402243}},\"hoverformat\":\".2f\"},\"shapes\":[],\"showlegend\":false,\"legend\":{\"bgcolor\":null,\"bordercolor\":null,\"borderwidth\":0,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":12.7521793275218}},\"hovermode\":\"closest\",\"barmode\":\"relative\",\"plot_bgcolor\":\"#faf7f0\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false,\"displaylogo\":false,\"responsive\":true},\"source\":\"A\",\"attrs\":{\"1a6c46137806\":{\"x\":{},\"y\":{},\"type\":\"scatter\"},\"1a6c307c2558\":{\"x\":{},\"y\":{}}},\"cur_data\":\"1a6c46137806\",\"visdat\":{\"1a6c46137806\":[\"function (y) \",\"x\"],\"1a6c307c2558\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n### Mann–Kendall test\n\nThe null hypothesis is no monotonic trend in the annual score. Positive Kendall's tau indicates an upward tendency; negative tau indicates a downward tendency. A trend in a positive score can mean strengthening high-value clustering, while an upward trend in a negative score can mean weakening low-value clustering.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchangsha_mk <- cbg |>\n  summarise(mk = list(unclass(Kendall::MannKendall(gi_star)))) |>\n  unnest_wider(mk)\nkable(changsha_mk, digits = 6, caption = \"Changsha Mann–Kendall test (sl is the p-value)\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Changsha Mann–Kendall test (sl is the p-value)\n\n|      tau|       sl|  S|   D|     varS|\n|--------:|--------:|--:|---:|--------:|\n| 0.485294| 0.007417| 66| 136| 589.3333|\n\n\n:::\n\n```{.r .cell-code}\ncounty_mk <- gi_stars |>\n  arrange(County, Year) |>\n  group_by(County) |>\n  summarise(mk = list(unclass(Kendall::MannKendall(gi_star))), .groups = \"drop\") |>\n  unnest_wider(mk) |>\n  mutate(p_bh = p.adjust(sl, method = \"BH\"))\ntop_trends <- county_mk |> arrange(sl, desc(abs(tau))) |> slice_head(n = 10)\nkable(top_trends, digits = 6, caption = \"Ten smallest trend p-values; BH adjustment across 88 counties\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Ten smallest trend p-values; BH adjustment across 88 counties\n\n|County     |       tau|       sl|    S|   D|     varS|     p_bh|\n|:----------|---------:|--------:|----:|---:|--------:|--------:|\n|Shuangfeng |  0.867647| 0.000001|  118| 136| 589.3333| 0.000042|\n|Xiangtan   |  0.867647| 0.000001|  118| 136| 589.3333| 0.000042|\n|Xiangxiang |  0.867647| 0.000001|  118| 136| 589.3333| 0.000042|\n|Chengbu    | -0.823529| 0.000005| -112| 136| 589.3333| 0.000085|\n|Dongan     | -0.823529| 0.000005| -112| 136| 589.3333| 0.000085|\n|Wugang     | -0.808824| 0.000007| -110| 136| 589.3333| 0.000104|\n|Huayuan    | -0.794118| 0.000010| -108| 136| 589.3333| 0.000115|\n|Shaoshan   |  0.794118| 0.000010|  108| 136| 589.3333| 0.000115|\n|Liuyang    |  0.779412| 0.000015|  106| 136| 589.3333| 0.000149|\n|Zhuzhou    |  0.764706| 0.000022|  104| 136| 589.3333| 0.000149|\n\n\n:::\n:::\n\n\nFor Changsha, **tau = 0.485** and **p = 0.00742**. At the unadjusted 5% level, this supports a monotonic trend; the estimated direction is upward.\n\nAcross all counties, **42** annual-score trends have raw p < 0.05, and **38** remain below 0.05 after Benjamini–Hochberg adjustment across the 88 county tests. The top-ten table ranks by p-value, then decreasing absolute tau. These are trend rankings rather than EHSA classifications.\n\n## 6. Emerging hot spot analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nehsa <- emerging_hotspot_analysis(x = GDPPC_st, .var = \"GDPPC\",\n  k = 1, nsim = 99, threshold = 0.01, include_gi = TRUE)\n# Record the cube's geometry order when attaching per-bin statistics.\nbin_results <- bind_cols(\n  tibble(County = rep(attr(GDPPC_st, \"geometry\")$County, times = length(years)),\n         Year = rep(years, each = nrow(hunan))),\n  as_tibble(attr(ehsa, \"gi_star\")))\nbin_summary <- bin_results |>\n  group_by(County) |>\n  summarise(mk_tau = as.numeric(MannKendall(gi_star)$tau),\n    mk_p = as.numeric(MannKendall(gi_star)$sl),\n    hot_years = sum(gi_star > 0 & p_sim <= 0.01),\n    cold_years = sum(gi_star < 0 & p_sim <= 0.01), .groups = \"drop\")\nehsa <- as_tibble(ehsa) |>\n  left_join(bin_summary, by = c(\"location\" = \"County\")) |>\n  mutate(p_bh = p.adjust(p_value, method = \"BH\"))\nstopifnot(nrow(ehsa) == 88L, !anyNA(ehsa),\n  all(abs(ehsa$tau - ehsa$mk_tau) < 1e-7),\n  all(abs(ehsa$p_value - ehsa$mk_p) < 1e-7))\nclass_counts <- ehsa |> count(classification, sort = TRUE)\nkable(class_counts, caption = \"EHSA classes: 99 simulations, k = 1, threshold = 0.01\")\n```\n\n::: {.cell-output-display}\n\n\nTable: EHSA classes: 99 simulations, k = 1, threshold = 0.01\n\n|classification      |  n|\n|:-------------------|--:|\n|sporadic coldspot   | 46|\n|sporadic hotspot    | 22|\n|oscilating hotspot  | 13|\n|no pattern detected |  4|\n|oscilating coldspot |  2|\n|consecutive hotspot |  1|\n\n\n:::\n:::\n\n\nThe main analysis uses **k = 1**, so neighbourhoods incorporate the current year and the preceding year. The earliest year has no preceding observation. I make the package's default **classification threshold of 0.01** explicit and retain the underlying bin statistics for inspection. I also verify that each reported county trend matches a Mann–Kendall test of its own ordered bin scores.\n\n::: {.callout-note}\n### Significance and simulation resolution\n\nIn the installed `sfdep` implementation, classification uses unadjusted `p_sim` and Mann–Kendall p-values. It does **not** automatically apply the FDR correction mentioned in the chapter overview. Its bin `p_sim` is the smaller simulated tail probability. With 99 simulations the smallest attainable value is 0.01, exactly the classification threshold, making a simulation sensitivity check useful.\n\nThe returned `p_value` is the county's **trend-test p-value**, not a bin-level hot spot p-value. BH values reported here adjust county trend tests only. This classroom implementation should not be described as identical to ArcGIS EHSA.\n:::\n\nThe [sfdep reference](https://search.r-project.org/CRAN/refmans/sfdep/html/emerging_hotspot_analysis.html) documents the defaults and time-lag neighbourhoods. The behaviour above was additionally checked against the installed package functions.\n\n### Distribution of classes\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(class_counts, aes(n, reorder(classification, n))) +\n  geom_col(fill = \"#9a432e\", width = 0.7) +\n  geom_text(aes(label = n), hjust = -0.2) +\n  scale_x_continuous(expand = expansion(mult = c(0, 0.12))) +\n  labs(title = \"Distribution of emerging hot spot classes\",\n       x = \"Number of counties\", y = NULL)\n```\n\n::: {.cell-output-display}\n![County counts for the primary 99-simulation EHSA run.](index_files/figure-html/c6-distribution-1.png){width=1600}\n:::\n:::\n\n\nThe most frequent class in this run is **sporadic coldspot**, with **46 counties**. Counts reflect this dataset, seed, neighbourhood, threshold, and package version.\n\n### Full classification map\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan_ehsa <- hunan |> left_join(ehsa, by = c(\"County\" = \"location\"))\nclasses <- sort(unique(ehsa$classification))\nclass_colours <- c(\"consecutive coldspot\" = \"#889d86\",\n  \"consecutive hotspot\" = \"#bd6e38\", \"diminishing coldspot\" = \"#b3bb9c\",\n  \"diminishing hotspot\" = \"#c99177\", \"historical coldspot\" = \"#d6dbc8\",\n  \"historical hotspot\" = \"#e1c3b0\", \"intensifying coldspot\" = \"#3f5f4b\",\n  \"intensifying hotspot\" = \"#742d24\", \"new coldspot\" = \"#567a63\",\n  \"new hotspot\" = \"#b84328\", \"no pattern detected\" = \"#ded9d0\",\n  \"oscilating coldspot\" = \"#8f8c5e\", \"oscilating hotspot\" = \"#a07944\",\n  \"persistent coldspot\" = \"#607560\", \"persistent hotspot\" = \"#934e36\",\n  \"sporadic coldspot\" = \"#a1b39a\", \"sporadic hotspot\" = \"#dda17e\")\nhunan_ehsa$classification <- factor(hunan_ehsa$classification, levels = classes)\nehsa_map <- tm_shape(hunan_ehsa) +\n  tm_polygons(fill = \"classification\", col = \"#fffaf2\", lwd = 0.5,\n    fill.scale = tm_scale_categorical(values = unname(class_colours[classes]),\n                                      levels = classes, levels.drop = FALSE),\n    fill.legend = tm_legend(title = \"EHSA class\", position = tm_pos_out())) +\n  tm_layout(bg.color = \"#faf7f0\", frame = FALSE) +\n  tm_title(\"Hunan · All EHSA classifications\")\nehsa_map\n```\n\n::: {.cell-output-display}\n![All 88 county classifications. Terracotta tones denote hot spot classes; green tones denote cold spot classes; grey denotes no detected pattern.](index_files/figure-html/c6-map-1.png){width=1600}\n:::\n:::\n\n\n### Map filtered by significant trends\n\n\n::: {.cell}\n\n```{.r .cell-code}\nehsa_sig <- hunan_ehsa |> filter(p_value < 0.05)\ntm_shape(hunan_ehsa) +\n  tm_polygons(fill = \"#ded9d0\", col = \"#fffaf2\", lwd = 0.5) +\n  tm_shape(ehsa_sig) +\n  tm_polygons(fill = \"classification\", col = \"#fffaf2\", lwd = 0.5,\n    fill.scale = tm_scale_categorical(values = unname(class_colours[classes]),\n                                      levels = classes, levels.drop = FALSE),\n    fill.legend = tm_legend(title = \"Class (trend p < 0.05)\", position = tm_pos_out())) +\n  tm_layout(bg.color = \"#faf7f0\", frame = FALSE) +\n  tm_title(\"Hunan · Counties with a significant Gi* trend\")\n```\n\n::: {.cell-output-display}\n![The chapter's additional filter: colour counties with an unadjusted Mann–Kendall trend p-value below 0.05.](index_files/figure-html/c6-filtered-map-1.png){width=1600}\n:::\n:::\n\n\nThis filtered map colours **44 counties**. Grey counties fail the displayed trend filter; some may still have a persistent hot or cold spot classification in the full map. A persistent cluster can have no significant monotonic trend. **36 counties** pass a separate BH-adjusted 5% trend criterion.\n\n## 7. Interpreting the classes\n\nThe [ArcGIS classification reference](https://doc.esri.com/en/arcgis-pro/latest/tool-reference/space-time-pattern-mining/learnmoreemerging.html) provides the conceptual taxonomy below. The maps retain the labels actually returned by `sfdep`; its detailed classification rules can differ from ArcGIS.\n\n| Family | Conceptual meaning |\n|---|---|\n| New | Significant clustering appears at the final time step. |\n| Consecutive | Clustering occupies an uninterrupted final run. |\n| Intensifying | Frequent clustering grows stronger with a significant trend. |\n| Persistent | Frequent clustering has no significant intensity trend. |\n| Diminishing | Frequent clustering weakens with a significant trend. |\n| Sporadic | Intermittent clustering occurs on one side of the distribution. |\n| Oscillating | The history contains both hot and cold clustering. |\n| Historical | Frequent past clustering is absent in the latest period. |\n| No pattern detected | The classification rules identify no named pattern. |\n\nHere “hot” refers to a neighbourhood of relatively high GDPPC, and “cold” to relatively low GDPPC. Neither label measures GDP growth directly. These county-level patterns do not establish a causal explanation for regional inequality or describe every household within a county.\n\n## 8. Simulation sensitivity and limitations\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nehsa_999 <- emerging_hotspot_analysis(x = GDPPC_st, .var = \"GDPPC\",\n  k = 1, nsim = 999, threshold = 0.01)\nsensitivity <- ehsa |>\n  select(location, class_99 = classification) |>\n  left_join(as_tibble(ehsa_999) |>\n    select(location, class_999 = classification), by = \"location\") |>\n  mutate(changed = class_99 != class_999)\nstopifnot(nrow(sensitivity) == 88L, !anyNA(sensitivity),\n  all(abs(ehsa$tau - ehsa_999$tau[match(ehsa$location, ehsa_999$location)]) < 1e-7))\nkable(sensitivity |> count(class_99, class_999, changed, sort = TRUE),\n  caption = \"Class stability when increasing simulations from 99 to 999\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Class stability when increasing simulations from 99 to 999\n\n|class_99            |class_999           |changed |  n|\n|:-------------------|:-------------------|:-------|--:|\n|sporadic coldspot   |sporadic coldspot   |FALSE   | 46|\n|sporadic hotspot    |sporadic hotspot    |FALSE   | 21|\n|oscilating hotspot  |oscilating hotspot  |FALSE   | 12|\n|no pattern detected |oscilating coldspot |TRUE    |  4|\n|oscilating coldspot |oscilating coldspot |FALSE   |  2|\n|consecutive hotspot |sporadic hotspot    |TRUE    |  1|\n|oscilating hotspot  |sporadic hotspot    |TRUE    |  1|\n|sporadic hotspot    |consecutive hotspot |TRUE    |  1|\n\n\n:::\n:::\n\n\nIncreasing simulations from 99 to 999 changes **7 of 88 classifications**; **81** remain unchanged. The observed scores and their trend statistics remain the same because only the simulated bin-level evidence changes. The main maps continue to show the chapter's 99-simulation run.\n\nNeighbour definitions, threshold choices, multiple testing and the treatment of temporal dependence all affect interpretation. The standard Mann–Kendall test used here does not correct for serial correlation. With only 17 annual observations, these results are an exploratory description of the supplied series.\n\n## 9. Results and reproduction\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndir.create(\"in-class6/results\", recursive = TRUE, showWarnings = FALSE)\nwrite_csv(gi_stars |> select(-nb, -wt), \"in-class6/results/annual-gi.csv\")\nwrite_csv(county_mk, \"in-class6/results/annual-mann-kendall.csv\")\nwrite_csv(ehsa, \"in-class6/results/ehsa-99.csv\")\nwrite_csv(bin_results, \"in-class6/results/ehsa-bin-statistics.csv\")\nwrite_csv(sensitivity, \"in-class6/results/class-sensitivity.csv\")\npackage_versions <- tibble(package = c(\"R\", \"sf\", \"sfdep\", \"spdep\", \"tmap\",\n  \"Kendall\", \"plotly\", \"dplyr\"), version = c(as.character(getRversion()),\n  vapply(c(\"sf\", \"sfdep\", \"spdep\", \"tmap\", \"Kendall\", \"plotly\", \"dplyr\"),\n         function(p) as.character(packageVersion(p)), character(1))))\nwrite_csv(package_versions, \"in-class6/results/package-versions.csv\")\nkable(package_versions, caption = \"Reproduction environment\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Reproduction environment\n\n|package |version |\n|:-------|:-------|\n|R       |4.5.3   |\n|sf      |1.1.3   |\n|sfdep   |0.2.5   |\n|spdep   |1.4.2   |\n|tmap    |4.4.1   |\n|Kendall |2.2.2   |\n|plotly  |4.12.1  |\n|dplyr   |1.2.1   |\n\n\n:::\n:::\n\n\nRun `source(\"in-class6/R/analysis.R\")` from the project root, then render this page. Package versions and the seed are recorded so the analysis can be checked independently.\n\n- [Analysis script](R/analysis.R)\n- [Input time series](data/aspatial/Hunan_GDPPC.csv) and [data provenance](data/README.md)\n- [Annual Gi* results](results/annual-gi.csv)\n- [Annual-score Mann–Kendall tests](results/annual-mann-kendall.csv)\n- [Primary EHSA classes and trends](results/ehsa-99.csv)\n- [EHSA bin statistics](results/ehsa-bin-statistics.csv)\n- [99 versus 999 simulation comparison](results/class-sensitivity.csv)\n- [Package versions](results/package-versions.csv)\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/htmltools-fill-0.5.9/fill.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"../site_libs/plotly-binding-4.12.1/plotly.js\"></script>\n<script src=\"../site_libs/typedarray-0.1/typedarray.min.js\"></script>\n<script src=\"../site_libs/jquery-3.5.1/jquery.min.js\"></script>\n<link href=\"../site_libs/crosstalk-1.2.2/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/crosstalk-1.2.2/js/crosstalk.min.js\"></script>\n<link href=\"../site_libs/plotly-htmlwidgets-css-2.25.2/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/plotly-main-2.25.2/plotly-latest.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}