{
  "hash": "de72b7283f252854fc5a208be19d99be",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Hands-on Exercise 4\"\nsubtitle: \"Spatial weights and their applications in Hunan\"\nauthor: \"Zhenhua Liu\"\ndate: \"2026-09-19\"\nbody-classes: exercise-page\ntoc: true\ntoc-location: right\ncode-tools: true\nexecute:\n  freeze: auto\n  error: false\n---\n\n## 1. Objective and setup\n\nThis exercise studies how the definition of a county's neighbourhood changes a spatial summary of GDP per capita (GDPPC). I construct contiguity and distance neighbours, assign weights, and compare four spatial summaries using Hunan's 2012 county data. The workflow follows [course Chapter 8](https://r4gdsa.netlify.app/chap08.html).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(sf)\nlibrary(spdep)\nlibrary(tmap)\nlibrary(dplyr)\nlibrary(readr)\nlibrary(knitr)\ntmap_mode(\"plot\")\n```\n:::\n\n\n## 2. Import and join the data\n\nThe shapefile stores county polygons in WGS 84. The CSV contains development indicators for 2012. Both inputs are included in this project under `handson4/data`, from the [instructor's Lesson 4 data](https://github.com/tskam/ISSS626-AY2026-27Aug/tree/master/lesson/Lesson04/data). An explicit county key prevents accidental matching on unrelated columns.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan <- st_read(\"handson4/data/geospatial\", layer = \"Hunan\", quiet = TRUE)\nhunan2012 <- read_csv(\"handson4/data/aspatial/Hunan_2012.csv\",\n                      show_col_types = FALSE)\nstopifnot(!anyDuplicated(hunan$County), !anyDuplicated(hunan2012$County))\nhunan <- left_join(hunan, hunan2012, by = \"County\") |>\n  select(NAME_2, ID_3, NAME_3, County, GDPPC)\nstopifnot(nrow(hunan) == 88L, !anyNA(hunan$GDPPC),\n          all(st_is_valid(hunan)))\nkable(head(st_drop_geometry(hunan)), caption = \"Joined county attributes\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Joined county attributes\n\n|NAME_2  |  ID_3|NAME_3  |County  | GDPPC|\n|:-------|-----:|:-------|:-------|-----:|\n|Changde | 21098|Anxiang |Anxiang | 23667|\n|Changde | 21100|Hanshou |Hanshou | 20981|\n|Changde | 21101|Jinshi  |Jinshi  | 34592|\n|Changde | 21102|Li      |Li      | 24473|\n|Changde | 21103|Linli   |Linli   | 25554|\n|Changde | 21104|Shimen  |Shimen  | 27137|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbasemap <- tm_shape(hunan) + tm_polygons(fill = \"grey95\") +\n  tm_text(\"NAME_3\", size = 0.45)\ngdppc <- tm_shape(hunan) +\n  tm_polygons(fill = \"GDPPC\",\n    fill.scale = tm_scale_intervals(style = \"quantile\", n = 5,\n                                    values = \"brewer.blues\"),\n    fill.legend = tm_legend(title = \"GDP per capita\"))\ntmap_arrange(basemap, gdppc, ncol = 2)\n```\n\n::: {.cell-output-display}\n![County reference map and GDP per capita in 2012.](index_files/figure-html/gdppc-map-1.png){width=960}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkable(st_drop_geometry(hunan) |> arrange(desc(GDPPC)) |> head(5),\n      caption = \"Five counties with the highest recorded GDPPC\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Five counties with the highest recorded GDPPC\n\n|NAME_2   |  ID_3|NAME_3        |County        | GDPPC|\n|:--------|-----:|:-------------|:-------------|-----:|\n|Changsha | 21107|Changsha      |Changsha      | 88656|\n|Changsha | 21111|Wangcheng     |Wangcheng     | 70666|\n|Chenzhou | 21122|Zixing        |Zixing        | 65706|\n|Loudi    | 21143|Lengshuijiang |Lengshuijiang | 64257|\n|Changsha | 21109|Liuyang       |Liuyang       | 63118|\n\n\n:::\n:::\n\n\nThe highest recorded GDPPC is in Changsha (88,656), while the lowest is in Guidong (8,497). The choropleth shows county values; it does not establish statistically significant clusters.\n\n## 3. Contiguity neighbours\n\nQueen neighbours share at least a boundary point; rook neighbours share a boundary segment. I use projected polygons for planar boundary topology and centroid calculation. Centroids are then transformed back to longitude/latitude for great-circle distances in kilometres.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan_utm <- st_transform(hunan, 32649)\nwm_q <- poly2nb(hunan_utm, queen = TRUE)\nwm_r <- poly2nb(hunan_utm, queen = FALSE)\ncentres <- st_transform(st_centroid(st_geometry(hunan_utm)), 4326)\ncoords <- st_coordinates(centres)\n\ndescribe_nb <- function(x, label) {\n  tibble(Method = label, Regions = length(x),\n         Directed_links = sum(card(x)),\n         Minimum = min(card(x)), Mean = mean(card(x)),\n         Maximum = max(card(x)), Isolates = sum(card(x) == 0))\n}\nkable(bind_rows(describe_nb(wm_q, \"Queen\"), describe_nb(wm_r, \"Rook\")),\n      digits = 2)\n```\n\n::: {.cell-output-display}\n\n\n|Method | Regions| Directed_links| Minimum| Mean| Maximum| Isolates|\n|:------|-------:|--------------:|-------:|----:|-------:|--------:|\n|Queen  |      88|            448|       1| 5.09|      11|        0|\n|Rook   |      88|            440|       1| 5.00|      10|        0|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndraw_nb <- function(nb, title) {\n  plot(st_geometry(hunan), border = \"grey75\", main = title, axes = TRUE)\n  plot(nb, coords, add = TRUE, col = \"#315e91\", pch = 16, cex = 0.35)\n}\npar(mfrow = c(1, 2), mar = c(2, 2, 3, 1))\ndraw_nb(wm_q, \"Queen contiguity\")\ndraw_nb(wm_r, \"Rook contiguity\")\n```\n\n::: {.cell-output-display}\n![Queen and rook connections between county centroids.](index_files/figure-html/contiguity-graphs-1.png){width=960}\n:::\n:::\n\n\nQueen contiguity gives 448 directed links, compared with 440 for rook contiguity. A reciprocal pair contributes two directed links. Queen includes corner contacts, so its graph is at least as inclusive as the rook graph.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnb1 <- wm_q[[1]]\nkable(st_drop_geometry(hunan)[nb1, c(\"County\", \"GDPPC\")],\n      caption = paste(\"Queen neighbours of\", hunan$County[1]))\n```\n\n::: {.cell-output-display}\n\n\nTable: Queen neighbours of Anxiang\n\n|   |County  | GDPPC|\n|:--|:-------|-----:|\n|2  |Hanshou | 20981|\n|3  |Jinshi  | 34592|\n|4  |Li      | 24473|\n|57 |Nan     | 21311|\n|85 |Taoyuan | 22879|\n\n\n:::\n:::\n\n\n## 4. Distance and nearest-neighbour weights\n\nA fixed distance includes every centroid within the threshold. I first find each county's closest neighbour, then round the largest of these distances up to a kilometre. This ensures that every county has at least one neighbour; it does not by itself guarantee a fully connected graph. Unlike a fixed radius, six-nearest-neighbour selection gives every county exactly six outgoing links.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nk1 <- knn2nb(knearneigh(coords, k = 1, longlat = TRUE))\nnearest_km <- unlist(nbdists(k1, coords, longlat = TRUE))\ncutoff_km <- ceiling(max(nearest_km))\nwm_dist <- dnearneigh(coords, d1 = 0, d2 = cutoff_km, longlat = TRUE)\nknn6 <- knn2nb(knearneigh(coords, k = 6, longlat = TRUE))\nstopifnot(all(card(wm_dist) > 0), all(card(knn6) == 6))\nkable(tibble(Minimum_nearest_km = min(nearest_km),\n             Maximum_nearest_km = max(nearest_km), Threshold_km = cutoff_km),\n      digits = 2)\n```\n\n::: {.cell-output-display}\n\n\n| Minimum_nearest_km| Maximum_nearest_km| Threshold_km|\n|------------------:|------------------:|------------:|\n|              24.79|              58.36|           59|\n\n\n:::\n\n```{.r .cell-code}\nkable(bind_rows(describe_nb(wm_dist, \"Fixed distance\"),\n               describe_nb(knn6, \"6 nearest neighbours\")), digits = 2)\n```\n\n::: {.cell-output-display}\n\n\n|Method               | Regions| Directed_links| Minimum| Mean| Maximum| Isolates|\n|:--------------------|-------:|--------------:|-------:|----:|-------:|--------:|\n|Fixed distance       |      88|            298|       1| 3.39|       6|        0|\n|6 nearest neighbours |      88|            528|       6| 6.00|       6|        0|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(1, 2), mar = c(2, 2, 3, 1))\ndraw_nb(wm_dist, paste(\"Within\", cutoff_km, \"km\"))\ndraw_nb(knn6, \"6 nearest neighbours\")\n```\n\n::: {.cell-output-display}\n![Fixed radius versus six-nearest-neighbour connections.](index_files/figure-html/distance-graphs-1.png){width=960}\n:::\n:::\n\n\nThe distance graph allows varying neighbour counts. The k-nearest-neighbour graph fixes the count but can be asymmetric: county A may select B without B selecting A. Small differences from tutorial distance results can arise because this exercise calculates centroids in a projected CRS and consistently uses great-circle distances.\n\n## 5. Inverse-distance and row-standardised weights\n\nFor queen neighbours, inverse distance assigns greater weight to closer centroids. A `B` style with a supplied `glist` retains these raw weights; it does **not** normalise their row sums. `W` divides each row by its sum. Without a `glist`, `B` supplies unit weights and `W` supplies equal weights summing to one.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndist_km <- nbdists(wm_q, coords, longlat = TRUE)\nstopifnot(all(unlist(dist_km) > 0), all(card(wm_q) > 0))\nids <- lapply(dist_km, function(d) 1 / d)\nidw_raw <- nb2listw(wm_q, glist = ids, style = \"B\")\nidw_w <- nb2listw(wm_q, glist = ids, style = \"W\")\nqueen_w <- nb2listw(wm_q, style = \"W\")\nqueen_b <- nb2listw(wm_q, style = \"B\")\nstopifnot(all(abs(vapply(queen_w$weights, sum, numeric(1)) - 1) < 1e-10),\n          all(abs(vapply(idw_w$weights, sum, numeric(1)) - 1) < 1e-10))\nkable(tibble(Neighbour = hunan$County[nb1], Distance_km = dist_km[[1]],\n             IDW_raw = idw_raw$weights[[1]],\n             IDW_standardised = idw_w$weights[[1]],\n             Queen_standardised = queen_w$weights[[1]]), digits = 4)\n```\n\n::: {.cell-output-display}\n\n\n|Neighbour | Distance_km| IDW_raw| IDW_standardised| Queen_standardised|\n|:---------|-----------:|-------:|----------------:|------------------:|\n|Hanshou   |     65.1219|  0.0154|           0.1368|                0.2|\n|Jinshi    |     25.5337|  0.0392|           0.3489|                0.2|\n|Li        |     54.9058|  0.0182|           0.1622|                0.2|\n|Nan       |     35.6070|  0.0281|           0.2502|                0.2|\n|Taoyuan   |     87.3641|  0.0114|           0.1020|                0.2|\n\n\n:::\n:::\n\n\n## 6. Four applications of spatial weights\n\nLet $x_i$ be county $i$'s GDPPC and $N_i$ its queen neighbours. A neighbour average excludes the focal county; a spatial window includes it. Sums are sensitive to how many counties are included. Adding GDP per capita values is a mathematical demonstration and must not be interpreted as total regional GDP.\n\n| Summary | Counties included | Calculation |\n|---|---|---|\n| Neighbour mean | Neighbours only | $\\sum_{j\\in N_i}x_j/|N_i|$ |\n| Neighbour sum | Neighbours only | $\\sum_{j\\in N_i}x_j$ |\n| Window mean | Neighbours and focal county | $(x_i+\\sum_{j\\in N_i}x_j)/(|N_i|+1)$ |\n| Window sum | Neighbours and focal county | $x_i+\\sum_{j\\in N_i}x_j$ |\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqueen_self <- include.self(wm_q)\nwindow_w <- nb2listw(queen_self, style = \"W\")\nwindow_b <- nb2listw(queen_self, style = \"B\")\nhunan$Neighbour_mean <- lag.listw(queen_w, hunan$GDPPC)\nhunan$Neighbour_sum <- lag.listw(queen_b, hunan$GDPPC)\nhunan$Window_mean <- lag.listw(window_w, hunan$GDPPC)\nhunan$Window_sum <- lag.listw(window_b, hunan$GDPPC)\nhunan$IDW_mean <- lag.listw(idw_w, hunan$GDPPC)\nstopifnot(isTRUE(all.equal(hunan$Neighbour_mean[1], mean(hunan$GDPPC[nb1]))),\n          isTRUE(all.equal(hunan$Window_sum, hunan$Neighbour_sum + hunan$GDPPC)))\nkable(head(st_drop_geometry(hunan) |>\n  select(County, GDPPC, Neighbour_mean, Neighbour_sum, Window_mean, Window_sum)),\n  digits = 2)\n```\n\n::: {.cell-output-display}\n\n\n|County  | GDPPC| Neighbour_mean| Neighbour_sum| Window_mean| Window_sum|\n|:-------|-----:|--------------:|-------------:|-----------:|----------:|\n|Anxiang | 23667|       24847.20|        124236|    24650.50|     147903|\n|Hanshou | 20981|       22724.80|        113624|    22434.17|     134605|\n|Jinshi  | 34592|       24143.25|         96573|    26233.00|     131165|\n|Li      | 24473|       27737.50|        110950|    27084.60|     135423|\n|Linli   | 25554|       27270.25|        109081|    26927.00|     134635|\n|Shimen  | 27137|       21248.80|        106244|    22230.17|     133381|\n\n\n:::\n:::\n\n\nFor Anxiang, the neighbour mean is 2.48472\\times 10^{4}. Including its own GDPPC of 2.3667\\times 10^{4} changes the window mean to 2.46505\\times 10^{4}. This provides a direct arithmetic check of the spatial lag.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean_fields <- c(\"GDPPC\", \"Neighbour_mean\", \"Window_mean\", \"IDW_mean\")\nmean_breaks <- pretty(range(unlist(st_drop_geometry(hunan)[mean_fields])), n = 5)\nmap_field <- function(field, title, breaks) {\n  tm_shape(hunan) + tm_polygons(fill = field,\n    fill.scale = tm_scale_intervals(style = \"fixed\", breaks = breaks,\n                                   values = \"brewer.blues\"),\n    fill.legend = tm_legend(title = title))\n}\nmean_maps <- Map(function(f, title) map_field(f, title, mean_breaks),\n                 mean_fields, c(\"GDPPC\", \"Neighbour mean\", \"Window mean\", \"IDW mean\"))\ndo.call(tmap_arrange, c(mean_maps, list(ncol = 2)))\n```\n\n::: {.cell-output-display}\n![County GDPPC and three neighbourhood means, using common class boundaries.](index_files/figure-html/lag-maps-1.png){width=1056}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum_breaks <- pretty(range(c(hunan$Neighbour_sum, hunan$Window_sum)), n = 5)\ntmap_arrange(map_field(\"Neighbour_sum\", \"Neighbour sum\", sum_breaks),\n             map_field(\"Window_sum\", \"Window sum\", sum_breaks), ncol = 2)\n```\n\n::: {.cell-output-display}\n![Neighbour sum and window sum on a common scale; these are sums of rates, not total GDP.](index_files/figure-html/sum-maps-1.png){width=960}\n:::\n:::\n\n\n## 7. Interpretation\n\nNeighbourhood means reduce the influence of isolated extreme county values, whereas window means retain some influence from the focal county. Common map breaks make these changes comparable. IDW further distinguishes close from distant neighbours within the same queen graph. None of these operations supplies a significance test or proves a causal relationship.\n\nWeights encode an analytical assumption: shared borders, a fixed radius and a fixed neighbour count answer different questions. Counties at the provincial boundary have no observations for neighbours outside this dataset. These edge effects and the use of historical 2012 indicators limit interpretation of the maps as descriptions of present-day Hunan.\n\n## 8. Reproducibility\n\nThe analysis uses the bundled original shapefile and CSV, checks unique join keys and missing GDPPC values, and verifies weight sums and two lag identities. [In-class Exercise 4](../inlcass4/index.qmd) extends the same dataset to geographically weighted summaries.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.5.3 (2026-03-11 ucrt)\nPlatform: x86_64-w64-mingw32/x64\nRunning under: Windows 11 x64 (build 26200)\n\nMatrix products: default\n  LAPACK version 3.12.1\n\nlocale:\n[1] LC_COLLATE=English_United States.utf8 \n[2] LC_CTYPE=English_United States.utf8   \n[3] LC_MONETARY=English_United States.utf8\n[4] LC_NUMERIC=C                          \n[5] LC_TIME=English_United States.utf8    \n\ntime zone: Asia/Shanghai\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n[1] knitr_1.51   readr_2.2.0  dplyr_1.2.1  tmap_4.4-1   spdep_1.4-2 \n[6] spData_2.3.5 sf_1.1-3    \n\nloaded via a namespace (and not attached):\n [1] xfun_0.60           raster_3.6-32       htmlwidgets_1.6.4  \n [4] lattice_0.22-9      tzdb_0.5.0          vctrs_0.7.3        \n [7] tools_4.5.3         crosstalk_1.2.2     generics_0.1.4     \n[10] parallel_4.5.3      tibble_3.3.1        proxy_0.4-29       \n[13] pkgconfig_2.0.3     KernSmooth_2.23-26  data.table_1.18.6.1\n[16] leaflet_2.2.3       lifecycle_1.0.5     compiler_4.5.3     \n[19] deldir_2.0-4        terra_1.9-50        codetools_0.2-20   \n[22] leafsync_0.1.0      leaflegend_1.2.8    stars_0.7-3        \n[25] htmltools_0.5.9     class_7.3-23        yaml_2.3.12        \n[28] crayon_1.5.3        pillar_1.11.1       classInt_0.4-11    \n[31] lwgeom_0.2-17       wk_0.9.5            boot_1.3-32        \n[34] abind_1.4-8         tidyselect_1.2.1    digest_0.6.39      \n[37] fastmap_1.2.0       grid_4.5.3          colorspace_2.1-3   \n[40] cli_3.6.6           logger_0.4.3        magrittr_2.0.5     \n[43] maptiles_0.12.0     base64enc_0.1-6     XML_3.99-0.24      \n[46] cols4all_0.10       leafem_0.2.5        e1071_1.7-17       \n[49] withr_3.0.3         bit64_4.8.6         sp_2.2-3           \n[52] rmarkdown_2.31      bit_4.6.0           otel_0.2.0         \n[55] png_0.1-9           hms_1.1.4           evaluate_1.0.5     \n[58] tmaptools_3.3       s2_1.1.12           rlang_1.3.0        \n[61] Rcpp_1.1.2          glue_1.8.1          DBI_1.3.0          \n[64] vroom_1.7.1         jsonlite_2.0.0      R6_2.6.1           \n[67] spacesXYZ_1.6-0     units_1.0-1        \n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}